(function(){
'use strict';
const HOME=location.pathname==='/'||location.pathname==='/index.html';if(!HOME)return;
const VERSION='20260922-awareness1';
const isoLocal=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
const language=()=>{const raw=String(window.MATCH_LANG||document.documentElement.lang||navigator.language||'en').replace('_','-');return /^pt-BR/i.test(raw)?'pt-BR':'en';};
const addDays=(iso,n)=>{const d=new Date(iso+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const expand=(e,y)=>{const s=y+'-'+String(e.month).padStart(2,'0')+'-'+String(e.day).padStart(2,'0');return{id:e.key+'-'+y,key:e.key,year:y,name:e.name,startDate:s,endExclusive:addDays(s,e.durationDays||1),sourceName:e.sourceName,sourceUrl:e.sourceUrl,pageUrl:'/awareness/'+e.key+'-'+y+'/',ribbonColor:e.ribbonColor||'#7b4db3',theme:e.themeByYear?.[String(y)]||'',supportLine:e.supportLine||''};};
const active=(c,t)=>c&&t>=c.startDate&&t<c.endExclusive;
function copy(c){const l=language();if(c.copy?.[l])return c.copy[l];return l==='pt-BR'?{eyebrow:'DESTAQUE DE CONSCIENTIZAÇÃO',title:'MatchApp apoia '+c.name,body:c.supportLine||'Conscientização, respeito e informações confiáveis importam.',cta:'Saiba mais'}:{eyebrow:'AWARENESS SPOTLIGHT',title:'MatchApp supports '+c.name,body:c.supportLine||'Awareness, respect and reliable information matter.',cta:'Learn more'};}
function render(c){const t=copy(c);let a=document.getElementById('awareness-spotlight');if(!a){a=document.createElement('aside');a.id='awareness-spotlight';a.innerHTML='<div class="awareness-card"><span class="awareness-ribbon" aria-hidden="true"><svg viewBox="0 0 48 64"><path d="M18 4c9 0 16 6 16 15 0 8-6 15-13 22l6 17-9-8-8 8 7-21C12 30 8 24 8 18 8 10 12 4 18 4Z" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" style="color:var(--awareness)"/><path d="M18 7c7 0 13 5 13 12 0 6-5 12-12 19" fill="none" stroke="rgba(255,255,255,.38)" stroke-width="2.2" stroke-linecap="round"/></svg></span><span class="awareness-copy"><span class="awareness-eyebrow"></span><strong class="awareness-title"></strong><span class="awareness-body"></span></span><a class="awareness-cta"></a></div>';const h=document.getElementById('mh-topbox')||document.querySelector('.app-header,header');if(h)h.insertAdjacentElement('afterend',a);else document.body.prepend(a);}
a.setAttribute('role','note');a.setAttribute('aria-label',t.title);a.dataset.awarenessStart=c.startDate;a.dataset.awarenessEnd=c.endExclusive;a.style.setProperty('--awareness',c.ribbonColor||'#7b4db3');a.querySelector('.awareness-eyebrow').textContent=t.eyebrow;a.querySelector('.awareness-title').textContent=t.title;a.querySelector('.awareness-body').textContent=t.body;const link=a.querySelector('.awareness-cta');link.textContent=t.cta;link.href=c.pageUrl||c.sourceUrl;}
function hide(){document.getElementById('awareness-spotlight')?.remove();}
async function boot(){const today=isoLocal();try{const [cr,ar]=await Promise.all([fetch('/awareness/current.json?v='+VERSION,{cache:'no-store'}),fetch('/awareness/calendar.json?v='+VERSION,{cache:'no-store'})]);const current=cr.ok?(await cr.json()).campaign:null;if(active(current,today)){render(current);return;}if(!ar.ok){hide();return;}const cal=await ar.json(),y=Number(today.slice(0,4));const found=(cal.events||[]).flatMap(e=>[expand(e,y-1),expand(e,y),expand(e,y+1)]).filter(c=>active(c,today)).sort((a,b)=>a.startDate.localeCompare(b.startDate))[0];if(found)render(found);else hide();}catch(_){const a=document.getElementById('awareness-spotlight');if(a&&a.dataset.awarenessEnd&&today>=a.dataset.awarenessEnd)a.remove();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();