/* Translate only the adult chart presentation. Original song/artist identities stay intact. */
(function(){'use strict';
 const keys=['title','note','week','verified','release','watch','unavailable','source','guide','stale'];
 const copy={
 en:['Billboard Hot 100 · Official music videos','US song rankings, not a music-video chart. Checked daily against published chart sources.','Chart week','Verified','Video released','Watch official video','Official video not verified','Chart source','Music and entertainment guide','Previous verified chart; awaiting a newer source.'],
 pt:['Billboard Hot 100 · Videoclipes oficiais','Ranking de músicas dos EUA, não de videoclipes. Fontes publicadas consultadas diariamente.','Semana do ranking','Verificado','Videoclipe lançado','Assistir ao videoclipe oficial','Videoclipe oficial não verificado','Fonte do ranking','Guia de música e entretenimento','Último ranking verificado; aguardando uma fonte mais recente.'],
 es:['Billboard Hot 100 · Videoclips oficiales','Ranking de canciones de EE. UU., no de videoclips. Fuentes consultadas diariamente.','Semana del ranking','Verificado','Videoclip publicado','Ver videoclip oficial','Videoclip oficial no verificado','Fuente del ranking','Guía de música y entretenimiento','Último ranking verificado; esperando una fuente más reciente.'],
 fr:['Billboard Hot 100 · Clips officiels','Classement des chansons aux États-Unis, pas des clips. Sources consultées chaque jour.','Semaine du classement','Vérifié','Clip publié','Voir le clip officiel','Clip officiel non vérifié','Source du classement','Guide musique et divertissement','Dernier classement vérifié ; nouvelle source attendue.'],
 de:['Billboard Hot 100 · Offizielle Musikvideos','US-Songcharts, keine Videocharts. Quellen werden täglich geprüft.','Chartwoche','Geprüft','Video veröffentlicht','Offizielles Video ansehen','Offizielles Video nicht bestätigt','Chartquelle','Musik und Unterhaltung','Letzte bestätigte Charts; neue Quelle ausstehend.'],
 it:['Billboard Hot 100 · Video ufficiali','Classifica dei brani USA, non dei video. Fonti consultate ogni giorno.','Settimana','Verificato','Video pubblicato','Guarda il video ufficiale','Video ufficiale non verificato','Fonte','Guida musica e intrattenimento','Ultima classifica verificata; in attesa di una nuova fonte.'],
 tr:['Billboard Hot 100 · Resmî müzik videoları','ABD şarkı listesi; video listesi değildir. Kaynaklar her gün kontrol edilir.','Liste haftası','Doğrulandı','Video yayını','Resmî videoyu izle','Resmî video doğrulanmadı','Liste kaynağı','Müzik ve eğlence rehberi','Son doğrulanmış liste; yeni kaynak bekleniyor.'],
 ru:['Billboard Hot 100 · Официальные клипы','Чарт песен США, не клипов. Источники проверяются ежедневно.','Неделя чарта','Проверено','Клип опубликован','Смотреть официальный клип','Официальный клип не подтверждён','Источник чарта','Музыка и развлечения','Последний проверенный чарт; ожидается новый источник.'],
 ar:['Billboard Hot 100 · فيديوهات رسمية','ترتيب الأغاني في الولايات المتحدة وليس الفيديوهات. تُراجع المصادر يومياً.','أسبوع القائمة','تم التحقق','تاريخ الفيديو','شاهد الفيديو الرسمي','الفيديو الرسمي غير موثق','مصدر القائمة','دليل الموسيقى والترفيه','آخر قائمة موثقة؛ بانتظار مصدر أحدث.'],
 hi:['Billboard Hot 100 · आधिकारिक संगीत वीडियो','अमेरिकी गानों की सूची, वीडियो की रैंकिंग नहीं। स्रोत रोज़ जाँचे जाते हैं।','चार्ट सप्ताह','सत्यापित','वीडियो रिलीज़','आधिकारिक वीडियो देखें','आधिकारिक वीडियो सत्यापित नहीं','चार्ट स्रोत','संगीत और मनोरंजन गाइड','अंतिम सत्यापित सूची; नए स्रोत की प्रतीक्षा।'],
 id:['Billboard Hot 100 · Video musik resmi','Peringkat lagu AS, bukan video. Sumber diperiksa setiap hari.','Minggu tangga lagu','Diverifikasi','Video dirilis','Tonton video resmi','Video resmi belum diverifikasi','Sumber','Panduan musik dan hiburan','Daftar terverifikasi terakhir; menunggu sumber baru.'],
 ja:['Billboard Hot 100 · 公式ミュージックビデオ','米国の楽曲ランキングです。動画ランキングではありません。毎日公開情報を確認します。','チャート週','確認日','動画公開日','公式動画を見る','公式動画は未確認','情報源','音楽・エンタメガイド','最新の確認済みチャート。新しい情報を待っています。'],
 ko:['Billboard Hot 100 · 공식 뮤직비디오','미국 노래 순위이며 동영상 순위가 아닙니다. 매일 공개 자료를 확인합니다.','차트 주간','확인일','영상 공개일','공식 영상 보기','공식 영상 미확인','차트 출처','음악 및 엔터테인먼트 안내','최근 확인된 차트이며 새 자료를 기다리는 중입니다.'],
 zh:['Billboard Hot 100 · 官方音乐视频','美国歌曲榜，非视频榜。每天核查已发布的来源。','榜单周','核实日期','视频发布日期','观看官方视频','官方视频尚未核实','榜单来源','音乐与娱乐指南','最近核实的榜单，等待更新来源。']};
 const spotifyKeys=['spotifyTitle','spotifyNote','spotifyVideo','spotifyCollection','announced','openSpotify','spotifySource'];
 const spotifyCopy={
 en:['Spotify · Music videos','Official videos and video collections confirmed by Spotify. Open a song and choose Switch to video when available. Premium, account and country availability apply.','Official music video','Official video collection','Announced','Open in Spotify','Spotify announcement'],
 pt:['Spotify · Videoclipes','Vídeos e coleções oficiais confirmados pelo Spotify. Abra a música e escolha Mudar para vídeo quando disponível. Disponibilidade depende do Premium, da conta e do país.','Videoclipe oficial','Coleção oficial de vídeos','Anunciado','Abrir no Spotify','Anúncio do Spotify'],
 es:['Spotify · Videoclips','Vídeos y colecciones oficiales confirmados por Spotify. Abre la canción y elige Cambiar a vídeo si está disponible. Depende de Premium, la cuenta y el país.','Videoclip oficial','Colección oficial de vídeos','Anunciado','Abrir en Spotify','Anuncio de Spotify'],
 fr:['Spotify · Clips','Vidéos et collections officielles confirmées par Spotify. Ouvrez le titre et choisissez Passer à la vidéo si disponible. Premium, compte et pays peuvent limiter l’accès.','Clip officiel','Collection vidéo officielle','Annoncé','Ouvrir dans Spotify','Annonce Spotify'],
 de:['Spotify · Musikvideos','Von Spotify bestätigte Videos und Sammlungen. Beim Song Zu Video wechseln wählen, falls verfügbar. Premium, Konto und Land bestimmen die Verfügbarkeit.','Offizielles Musikvideo','Offizielle Videosammlung','Angekündigt','In Spotify öffnen','Spotify-Ankündigung'],
 it:['Spotify · Video musicali','Video e raccolte ufficiali confermati da Spotify. Apri il brano e scegli Passa al video se disponibile. Dipende da Premium, account e paese.','Video musicale ufficiale','Raccolta video ufficiale','Annunciato','Apri in Spotify','Annuncio Spotify'],
 tr:['Spotify · Müzik videoları','Spotify tarafından doğrulanan videolar ve koleksiyonlar. Varsa Videoya geç seçeneğini kullanın. Premium, hesap ve ülke koşulları geçerlidir.','Resmî müzik videosu','Resmî video koleksiyonu','Duyuruldu','Spotify’da aç','Spotify duyurusu'],
 ru:['Spotify · Музыкальные клипы','Видео и коллекции подтверждены Spotify. Выберите Переключиться на видео, если доступно. Доступ зависит от Premium, аккаунта и страны.','Официальный клип','Официальная видеоколлекция','Объявлено','Открыть Spotify','Объявление Spotify'],
 ar:['Spotify · فيديوهات موسيقية','فيديوهات ومجموعات أكدها Spotify. اختر التبديل إلى الفيديو إن توفر. يعتمد الوصول على Premium والحساب والبلد.','فيديو موسيقي رسمي','مجموعة فيديوهات رسمية','أُعلن','افتح Spotify','إعلان Spotify'],
 hi:['Spotify · संगीत वीडियो','Spotify द्वारा पुष्टि किए गए वीडियो और संग्रह। उपलब्ध हो तो वीडियो पर स्विच करें चुनें। Premium, खाते और देश के अनुसार उपलब्धता बदलती है।','आधिकारिक संगीत वीडियो','आधिकारिक वीडियो संग्रह','घोषणा','Spotify में खोलें','Spotify की घोषणा'],
 id:['Spotify · Video musik','Video dan koleksi resmi dikonfirmasi Spotify. Pilih Beralih ke video jika tersedia. Bergantung pada Premium, akun, dan negara.','Video musik resmi','Koleksi video resmi','Diumumkan','Buka Spotify','Pengumuman Spotify'],
 ja:['Spotify · ミュージックビデオ','Spotifyが確認した公式動画・コレクション。曲で利用可能なら動画に切り替えてください。Premium、アカウント、国により異なります。','公式ミュージックビデオ','公式動画コレクション','発表日','Spotifyで開く','Spotifyの発表'],
 ko:['Spotify · 뮤직비디오','Spotify가 확인한 공식 영상과 모음입니다. 가능하면 동영상으로 전환을 선택하세요. Premium, 계정 및 국가에 따라 다릅니다.','공식 뮤직비디오','공식 영상 모음','발표일','Spotify에서 열기','Spotify 발표'],
 zh:['Spotify · 音乐视频','Spotify确认的官方视频和合集。可用时选择切换到视频。受Premium、账户和地区限制。','官方音乐视频','官方视频合集','公告日期','在Spotify打开','Spotify公告']};
 function paint(){const language=String(window.MATCH_LANG||document.documentElement.lang||'en');const words=copy[language.split('-')[0]]||copy.en;document.querySelectorAll('.billboard-chart').forEach(root=>{root.querySelectorAll('[data-bb-copy]').forEach(el=>{const i=keys.indexOf(el.dataset.bbCopy);if(i>=0)el.textContent=words[i];else{const j=spotifyKeys.indexOf(el.dataset.bbCopy);if(j>=0)el.textContent=(spotifyCopy[language.split('-')[0]]||spotifyCopy.en)[j];}});root.querySelectorAll('time').forEach(el=>{if(Number.isFinite(Date.parse(el.dateTime)))el.textContent=new Intl.DateTimeFormat(language,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(el.dateTime));});const old=root.querySelector('.billboard-stale');if(old)old.hidden=Date.now()<=Date.parse(root.dataset.chartDate+'T00:00:00Z')+7*86400000;});}
 document.addEventListener('matchapp:langchange',paint);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',paint,{once:true});else paint();
})();
