/* Brazil-only billing presentation. BRL is shown only when Cloudflare reports Brazil and the server confirms an active verified BRL Stripe Price for that product. Stripe Checkout decides which eligible payment methods (including Pix when available) to present. */
(function(){'use strict';
const BRL={ad_free:'R$ 4,90',vip_monthly:'R$ 9,90',vip_annual:'R$ 79,90',business:'R$ 149,90',credits_25:'R$ 4,90',credits_75:'R$ 9,90',credits_200:'R$ 19,90',credits_500:'R$ 34,90',matches_5:'R$ 1,90',matches_25:'R$ 4,90',matches_50:'R$ 7,90'};const KEYS=Object.keys(BRL);let active=new Set();
async function country(){try{const r=await fetch('/cdn-cgi/trace',{cache:'no-store',credentials:'omit'});if(!r.ok)return'';const m=(await r.text()).match(/^loc=([A-Z]{2})$/m);return m?m[1]:'';}catch(_){return'';}}
async function availability(){const sb=window.supabaseClient;if(!sb?.functions?.invoke)return new Set();try{const {data,error}=await sb.functions.invoke('stripe-checkout',{body:{action:'availability',products:KEYS}});if(error||!data?.products)return new Set();return new Set(KEYS.filter(k=>data.products[k]===true));}catch(_){return new Set();}}
function keyOf(b){return b?.dataset?.matchPack||b?.dataset?.creditPack||b?.dataset?.match||b?.dataset?.pack||b?.id?.replace(/^btn-/,'')||'';}
function paint(){if(window.CREDIT_PACKS)window.CREDIT_PACKS.forEach(p=>{if(active.has(p.key))p.price=BRL[p.key];});if(window.MATCH_PACKS)window.MATCH_PACKS.forEach(p=>{if(active.has(p.key))p.price=BRL[p.key];});document.documentElement.dataset.billingMarket='BR';document.dispatchEvent(new CustomEvent('matchapp:billingmarket',{detail:{market:'BR',currency:active.size===KEYS.length?'brl':'mixed',prices:Object.fromEntries([...active].map(k=>[k,BRL[k]]))}}));const host=document.getElementById('purchase-hub');if(host&&active.size&&!host.querySelector('.brl-pix-note')){const note=document.createElement('div');note.className='brl-pix-note';note.setAttribute('role','note');note.textContent='🇧🇷 Preços em BRL · PIX aparece no Checkout quando elegível';host.insertBefore(note,host.children[2]||null);}document.querySelectorAll('[data-match-pack],[data-credit-pack],[data-match],[data-pack]').forEach(b=>{const k=keyOf(b);if(!active.has(k))return;const card=b.closest('.purchase-pack,.credit-pack');const price=card&&card.querySelector('b,.credit-pack-price');if(price)price.textContent=BRL[k];});}
function style(){if(document.getElementById('brl-pix-style'))return;const s=document.createElement('style');s.id='brl-pix-style';s.textContent='.brl-pix-note{margin:10px 0 16px;padding:9px 12px;border:1px solid #32d58355;border-radius:12px;background:#0d2a1d99;color:#b7f7d4;font-size:.82rem;font-weight:800;text-align:center}';document.head.appendChild(s);}
async function brCheckout(key,button){const sb=window.supabaseClient;if(!sb||!active.has(key))return;const session=await sb.auth.getSession();if(!session?.data?.session){window.showToast?.('Entre na sua conta para continuar.');window.openAuthModal?.();return;}const old=button.textContent;button.disabled=true;button.textContent='Abrindo pagamento em BRL…';try{const {data,error}=await sb.functions.invoke('stripe-checkout',{body:{product:key,lang:window.MATCH_LANG||'pt-BR',market:'BR',currency:'brl'}});if(error||!data?.url?.startsWith('https://checkout.stripe.com/'))throw new Error();location.assign(data.url);}catch(_){window.showToast?.('Pagamento em BRL indisponível no momento. Tente novamente.',true);button.disabled=false;button.textContent=old;}}
function capture(e){if(window.MatchBillingMarket?.market!=='BR')return;const b=e.target.closest('button');if(!b)return;const key=keyOf(b);if(!active.has(key))return;e.preventDefault();e.stopImmediatePropagation();brCheckout(key,b);}
window.MatchBillingMarket={market:'INTL',currency:'usd',prices:null,activeProducts:[],ready:null};window.MatchBillingMarket.ready=country().then(async c=>{if(c!=='BR')return window.MatchBillingMarket;window.MatchBillingMarket.market='BR';active=await availability();window.MatchBillingMarket.activeProducts=[...active];if(active.size){window.MatchBillingMarket.currency=active.size===KEYS.length?'brl':'mixed';window.MatchBillingMarket.prices=Object.fromEntries([...active].map(k=>[k,BRL[k]]));style();paint();setTimeout(paint,250);document.addEventListener('click',capture,true);}return window.MatchBillingMarket;});
})();
