(function(){'use strict';
 const tr=(k,f)=>{if(typeof window.t!=='function')return f;const v=window.t(k);return v&&v!==k?v:f;};
 function render(){const host=document.getElementById('credits-grid');if(!host)return;const credits=window.CREDIT_PACKS||[];host.innerHTML=credits.map(p=>`<article class="credit-pack${p.badge?' is-featured':''}">${p.badge?`<span class="credit-pack-badge">${p.badge}</span>`:''}<span class="credit-pack-amount">${p.credits}</span><span class="credit-pack-unit">Ask AI credits</span><span class="credit-pack-price">${p.price}</span><span class="credit-pack-each">1 credit = 1 Ask AI prompt</span><button type="button" class="credit-pack-btn" data-pack="${p.key}">Buy ${p.credits} Ask AI credits</button></article>`).join('');host.onclick=e=>{const b=e.target.closest('[data-pack]');if(b)window.buyCredits?.(b.dataset.pack);};
 let section=document.getElementById('match-packs-section');if(!section){section=document.createElement('section');section.id='match-packs-section';section.className='credits-section';host.parentElement?.insertAdjacentElement('afterend',section);}const matches=window.MATCH_PACKS||[];section.innerHTML=`<h2 class="credits-h">Buy more Matches</h2><p class="credits-lede">Extra Matches are for Match recommendations only. They never expire and do not include Ask AI prompts.</p><div class="credits-grid">${matches.map(p=>`<article class="credit-pack${p.badge?' is-featured':''}">${p.badge?`<span class="credit-pack-badge">${p.badge}</span>`:''}<span class="credit-pack-amount">${p.matches}</span><span class="credit-pack-unit">Extra Matches</span><span class="credit-pack-price">${p.price}</span><span class="credit-pack-each">Matches only · no Ask AI credits</span><button type="button" class="credit-pack-btn" data-match="${p.key}">Buy ${p.matches} Matches</button></article>`).join('')}</div>`;section.onclick=e=>{const b=e.target.closest('[data-match]');if(b)window.buyMatches?.(b.dataset.match);};}
 let last=null;window.renderCreditBadge=function(n){if(typeof n==='number')last=n;const line=document.getElementById('credit-balance-line');if(line){const v=document.getElementById('credit-balance-value');if(v)v.textContent=last??0;line.style.display=last>0?'inline-flex':'none';}let pill=document.getElementById('credit-badge');if(!last||last<=0){if(pill)pill.style.display='none';return;}if(!pill){const nav=document.querySelector('.app-header nav')||document.querySelector('.app-header');if(!nav)return;pill=document.createElement('a');pill.id='credit-badge';pill.className='credit-badge';pill.href='/pricing/pricing.html#credits';pill.title='Ask AI credit balance';nav.prepend(pill);}pill.innerHTML=`✨ Ask AI <strong>${last}</strong>`;pill.style.display='inline-flex';};
 async function refresh(){if(!window.isUserLoggedIn||!window.supabaseClient){window.renderCreditBadge(0);return;}try{const {data}=await window.supabaseClient.rpc('match_credits');if(data)window.renderCreditBadge(data.credits||0);}catch(_){}}
 window.refreshCreditBalance=refresh;
 function inject(){const host=document.getElementById('quota-message')||document.getElementById('limit-box');if(!host||host.querySelector('.credits-inline-cta'))return;const packs=(window.MATCH_PACKS||[]);const wrap=document.createElement('div');wrap.className='credits-inline-cta';wrap.innerHTML=`<p class="cic-lede">Out of Matches? Add a small non-expiring Match pack.</p><div class="cic-row">${packs.map(p=>`<button type="button" class="cic-pack" data-match="${p.key}"><strong>${p.matches}</strong><span>${p.price}</span></button>`).join('')}</div><a class="cic-sub" href="/pricing/pricing.html#match-packs-section">See Match packs →</a>`;wrap.onclick=e=>{const b=e.target.closest('[data-match]');if(b)window.buyMatches?.(b.dataset.match);};host.appendChild(wrap);}
 window.injectCreditsCTA=inject;
 function init(){render();refresh();}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();document.addEventListener('matchapp:authchange',refresh);document.addEventListener('matchapp:langchange',render);
})();
