(function(){'use strict';if(typeof I18N==='undefined')return;
 const descriptions={
 'pt-BR':[
  'Atletas de 45 países e regiões participam do festival multiesportivo no Japão. A abertura será em 19 de setembro e o encerramento em 4 de outubro; algumas competições começam antes.',
  'A TBS é uma emissora oficial no Japão. Consulte sua programação e seus vídeos oficiais. Em outros países, os direitos são diferentes: confira a emissora local. Não há transmissão gratuita mundial confirmada.',
  'A Fórmula 1 passa pelas muralhas antigas e retas à beira do mar de Baku. Treinos em 24 de setembro, classificação em 25 e corrida no sábado, dia 26.',
  'O F1 TV oferece transmissões e reprises por assinatura nos países disponíveis. Consulte o guia oficial de emissoras por país. O canal oficial da Fórmula 1 publica melhores momentos; não há promessa de corrida completa gratuita.',
  'O Mundial de League of Legends volta à América do Norte. O calendário da Riot informa 15 de outubro a 14 de novembro, com final em Nova York. Confira as etapas e partidas na programação oficial.',
  'LoL Esports reúne transmissões oficiais e programação por região. Seu canal oficial publica reprises selecionadas, melhores momentos e conteúdos especiais após as partidas. Idioma e disponibilidade podem variar.'
 ],
 es:['Atletas de 45 países y regiones compiten en Japón. La apertura será el 19 de septiembre y el cierre el 4 de octubre; algunas pruebas empiezan antes.','TBS es una emisora oficial en Japón. Consulta su programación y vídeos. En otros países, comprueba la emisora local. No hay transmisión gratuita mundial confirmada.','La Fórmula 1 recorre las murallas y rectas costeras de Bakú. Entrenamientos el 24 de septiembre, clasificación el 25 y carrera el sábado 26.','F1 TV ofrece directos y repeticiones por suscripción donde está disponible. Consulta la guía oficial de emisoras por país. El canal oficial publica resúmenes; no se promete una carrera completa gratis.','El Mundial de League of Legends vuelve a Norteamérica. El calendario de Riot indica del 15 de octubre al 14 de noviembre, con final en Nueva York. Consulta cada fase en la programación oficial.','LoL Esports ofrece emisiones oficiales y horarios regionales. Su canal oficial publica repeticiones seleccionadas y resúmenes después de los partidos. Idioma y disponibilidad pueden variar.'],
 fr:['Des athlètes de 45 pays et régions se réunissent au Japon. Ouverture le 19 septembre, clôture le 4 octobre ; certaines épreuves commencent avant.','TBS est un diffuseur officiel au Japon. Consultez son programme et ses vidéos. Ailleurs, vérifiez les droits locaux. Aucun direct gratuit mondial n’est confirmé.','La Formule 1 parcourt les remparts et longues lignes droites de Bakou. Essais le 24 septembre, qualifications le 25, course samedi 26.','F1 TV propose directs et rediffusions sur abonnement selon le pays. Consultez le guide officiel des diffuseurs. La chaîne officielle publie des résumés, sans promettre une course complète gratuite.','Le Mondial de League of Legends revient en Amérique du Nord, du 15 octobre au 14 novembre selon Riot, avec la finale à New York. Consultez le calendrier officiel.','LoL Esports propose les diffusions et horaires officiels. Sa chaîne publie des rediffusions sélectionnées et résumés après les matchs. Langue et disponibilité variables.'],
 de:['Athleten aus 45 Ländern und Regionen treffen sich in Japan. Eröffnung am 19. September, Abschluss am 4. Oktober; einige Wettbewerbe beginnen früher.','TBS überträgt offiziell in Japan. Prüfe Programm und offizielle Videos. In anderen Ländern gelten eigene Rechte. Kein weltweiter kostenloser Livestream bestätigt.','Die Formel 1 fährt durch Bakus Altstadt und Küstenstraßen. Training am 24. September, Qualifikation am 25., Rennen am Samstag, 26. September.','F1 TV bietet Liveübertragungen und Wiederholungen mit Abo in verfügbaren Ländern. Prüfe den offiziellen Senderführer. Der offizielle Kanal zeigt Höhepunkte; keine kostenlose vollständige Übertragung zugesagt.','Die League-of-Legends-WM kehrt nach Nordamerika zurück. Riot nennt den 15. Oktober bis 14. November, mit Finale in New York. Prüfe den offiziellen Spielplan.','LoL Esports bietet offizielle Übertragungen und regionale Zeiten. Der offizielle Kanal veröffentlicht ausgewählte Wiederholungen und Höhepunkte. Sprache und Verfügbarkeit können variieren.'],
 it:['Atleti di 45 paesi e regioni gareggiano in Giappone. Apertura il 19 settembre e chiusura il 4 ottobre; alcune gare iniziano prima.','TBS è un’emittente ufficiale in Giappone. Controlla palinsesto e video. Altrove verifica i diritti locali. Nessuna diretta mondiale gratuita confermata.','La Formula 1 attraversa le mura e i rettilinei sul mare di Baku. Prove il 24 settembre, qualifiche il 25 e gara sabato 26.','F1 TV offre dirette e repliche con abbonamento dove disponibile. Consulta la guida ufficiale delle emittenti. Il canale ufficiale pubblica sintesi, senza promettere gare complete gratuite.','Il Mondiale di League of Legends torna in Nord America, dal 15 ottobre al 14 novembre secondo Riot, con finale a New York. Consulta il calendario ufficiale.','LoL Esports offre trasmissioni ufficiali e orari regionali. Il canale ufficiale pubblica repliche selezionate e sintesi dopo le partite. Lingua e disponibilità variabili.'],
 tr:['45 ülke ve bölgeden sporcular Japonya’da buluşuyor. Açılış 19 Eylül, kapanış 4 Ekim; bazı yarışmalar daha önce başlar.','TBS Japonya’da resmî yayıncıdır. Programını ve resmî videolarını kontrol edin. Diğer ülkelerde yerel hakları kontrol edin. Dünya çapında ücretsiz canlı yayın doğrulanmadı.','Formula 1 Bakü’nün eski surları ve sahil düzlüklerinde yarışıyor. Antrenman 24 Eylül, sıralama 25 Eylül, yarış 26 Eylül Cumartesi.','F1 TV uygun ülkelerde abonelikle canlı yayın ve tekrar sunar. Resmî ülke yayıncı rehberine bakın. Resmî kanal özetler yayınlar; tam ücretsiz yarış sözü verilmez.','League of Legends Dünya Şampiyonası Kuzey Amerika’ya dönüyor. Riot takvimi 15 Ekim–14 Kasım ve New York finalini listeliyor. Resmî programı kontrol edin.','LoL Esports resmî yayın ve bölgesel program sunar. Resmî kanalda seçilmiş tekrarlar ve özetler maçlardan sonra yayınlanır. Dil ve erişim değişebilir.'],
 ru:['Спортсмены из 45 стран и регионов собираются в Японии. Открытие 19 сентября, закрытие 4 октября; некоторые соревнования начинаются раньше.','TBS — официальный вещатель в Японии. Проверьте программу и видео. В других странах действуют местные права. Бесплатная мировая трансляция не подтверждена.','Формула-1 проходит по улицам и приморским прямым Баку. Практика 24 сентября, квалификация 25-го, гонка в субботу 26-го.','F1 TV предлагает эфиры и повторы по подписке в доступных странах. Проверьте официальный список вещателей. Официальный канал публикует обзоры; полная бесплатная гонка не обещана.','Чемпионат мира League of Legends возвращается в Северную Америку. Календарь Riot: 15 октября–14 ноября, финал в Нью-Йорке. Проверьте официальный график.','LoL Esports предлагает официальные эфиры и региональное расписание. Канал публикует отдельные повторы и обзоры после матчей. Язык и доступность могут различаться.'],
 ar:['يجتمع رياضيون من 45 دولة ومنطقة في اليابان. الافتتاح 19 سبتمبر والختام 4 أكتوبر؛ بعض المنافسات تبدأ قبل ذلك.','TBS ناقل رسمي في اليابان. راجع جدوله وفيديوهاته. في الدول الأخرى تختلف الحقوق المحلية. لا يوجد بث مجاني عالمي مؤكد.','تتسابق فورمولا 1 بين أسوار باكو القديمة ومستقيماتها الساحلية. التجارب 24 سبتمبر والتأهيل 25 سبتمبر والسباق السبت 26 سبتمبر.','يوفر F1 TV بثًا وإعادات باشتراك حيث يتاح. راجع دليل الناقلين الرسمي حسب الدولة. تنشر القناة الرسمية ملخصات دون وعد بسباق كامل مجاني.','تعود بطولة العالم للعبة League of Legends إلى أمريكا الشمالية. تقويم Riot من 15 أكتوبر إلى 14 نوفمبر والنهائي في نيويورك. راجع الجدول الرسمي.','يوفر LoL Esports البث الرسمي والجداول الإقليمية. تنشر قناته إعادات مختارة وملخصات بعد المباريات. اللغة والتوافر قد يختلفان.'],
 hi:['45 देशों और क्षेत्रों के खिलाड़ी जापान में मिलते हैं। उद्घाटन 19 सितंबर और समापन 4 अक्टूबर है; कुछ प्रतियोगिताएँ पहले शुरू होती हैं।','TBS जापान का आधिकारिक प्रसारक है। कार्यक्रम और वीडियो देखें। दूसरे देशों में स्थानीय अधिकार जाँचें। विश्वव्यापी मुफ्त लाइव प्रसारण की पुष्टि नहीं है।','फॉर्मूला 1 बाकू की पुरानी दीवारों और तटीय सीधी सड़कों पर दौड़ती है। अभ्यास 24 सितंबर, क्वालीफाइंग 25 सितंबर और रेस शनिवार 26 सितंबर है।','F1 TV उपलब्ध देशों में सदस्यता पर लाइव और रीप्ले देता है। आधिकारिक देशवार प्रसारक गाइड देखें। आधिकारिक चैनल मुख्य अंश देता है; पूरी मुफ्त रेस का वादा नहीं है।','League of Legends विश्व चैम्पियनशिप उत्तरी अमेरिका लौटती है। Riot कैलेंडर में 15 अक्टूबर से 14 नवंबर और न्यूयॉर्क फाइनल है। आधिकारिक कार्यक्रम देखें।','LoL Esports आधिकारिक प्रसारण और क्षेत्रीय समय देता है। आधिकारिक चैनल मैचों के बाद चुनिंदा रीप्ले और मुख्य अंश देता है। भाषा और उपलब्धता बदल सकती हैं।'],
 id:['Atlet dari 45 negara dan wilayah berkumpul di Jepang. Pembukaan 19 September dan penutupan 4 Oktober; beberapa pertandingan dimulai lebih awal.','TBS adalah penyiar resmi di Jepang. Periksa jadwal dan videonya. Di negara lain, periksa hak siar lokal. Siaran langsung gratis global belum dikonfirmasi.','Formula 1 melintasi tembok tua dan jalan pesisir Baku. Latihan 24 September, kualifikasi 25 September, balapan Sabtu 26 September.','F1 TV menyediakan siaran dan tayangan ulang berlangganan di negara yang didukung. Periksa panduan penyiar resmi. Kanal resmi menyediakan sorotan; balapan penuh gratis tidak dijanjikan.','Kejuaraan Dunia League of Legends kembali ke Amerika Utara. Kalender Riot mencantumkan 15 Oktober–14 November, dengan final di New York. Periksa jadwal resmi.','LoL Esports menyediakan siaran resmi dan jadwal regional. Kanal resminya menayangkan rekaman pilihan dan sorotan setelah pertandingan. Bahasa dan ketersediaan bervariasi.'],
 ja:['45の国と地域の選手が日本に集まります。開会式は9月19日、閉会式は10月4日。一部競技は先に始まります。','TBSは日本の公式放送局です。放送予定と公式動画を確認してください。他国の放映権は別途確認が必要です。世界共通の無料ライブ配信は未確認です。','F1がバクーの旧市街と海沿いの直線を走ります。練習は9月24日、予選は25日、決勝は土曜26日です。','F1 TVは対象国で有料のライブとリプレイを提供します。公式の国別放送ガイドを確認してください。公式チャンネルはハイライトを掲載しますが、無料の全編中継は保証しません。','League of Legends世界選手権が北米に戻ります。Riotの予定は10月15日〜11月14日、決勝はニューヨーク。公式日程を確認してください。','LoL Esportsで公式配信と地域別日程を確認できます。公式チャンネルには試合後に一部リプレイとハイライトが掲載されます。言語と提供状況は異なります。'],
 ko:['45개 국가와 지역의 선수들이 일본에 모입니다. 개회식은 9월 19일, 폐회식은 10월 4일이며 일부 경기는 먼저 시작됩니다.','TBS는 일본의 공식 방송사입니다. 편성표와 공식 영상을 확인하세요. 다른 국가의 중계권은 별도입니다. 전 세계 무료 생중계는 확인되지 않았습니다.','F1이 바쿠의 옛 성벽과 해안 직선을 달립니다. 연습은 9월 24일, 예선은 25일, 결승은 토요일 26일입니다.','F1 TV는 지원 국가에서 구독으로 생중계와 다시 보기를 제공합니다. 공식 국가별 방송 안내를 확인하세요. 공식 채널은 하이라이트를 제공하며 전체 무료 중계를 약속하지 않습니다.','League of Legends 월드 챔피언십이 북미로 돌아옵니다. Riot 일정은 10월 15일~11월 14일, 결승은 뉴욕입니다. 공식 일정을 확인하세요.','LoL Esports는 공식 중계와 지역별 일정을 제공합니다. 공식 채널은 경기 후 일부 다시 보기와 하이라이트를 올립니다. 언어와 이용 가능 여부는 다를 수 있습니다.'],
 zh:['45个国家和地区的运动员齐聚日本。开幕式9月19日，闭幕式10月4日；部分比赛提前开始。','TBS是日本官方转播机构。请查看节目表和官方视频。其他国家的版权不同，请查询当地转播商。尚未确认全球免费直播。','F1穿越巴库古城墙与海滨直道。练习赛9月24日，排位赛25日，正赛周六26日。','F1 TV在支持地区提供订阅直播和回放。请查阅官方各国转播指南。官方频道提供精选集锦，不保证免费全程正赛。','League of Legends全球总决赛重返北美。Riot日历标注10月15日至11月14日，决赛在纽约。请查询官方赛程。','LoL Esports提供官方直播和地区赛程。官方频道在比赛后发布精选回放和集锦。语言与可用性可能不同。']
 };
 const slugs=['asian-games-2026','azerbaijan-gp-2026','worlds-2026'];
 for(const [lang,values] of Object.entries(descriptions))slugs.forEach((slug,i)=>{I18N[lang]['global.'+slug+'.synopsis']=values[i*2];I18N[lang]['global.'+slug+'.watchInfo']=values[i*2+1];});
 if(document.readyState!=='loading'&&typeof applyTranslations==='function')applyTranslations(window.MATCH_LANG||'en');
})();
