/* Homepage UX lock: compact check-in, fold controls, regional title details. */
(()=>{'use strict';
if(location.pathname!=='/'&&location.pathname!=='/index.html')return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const COMMON=['US','BR','GB','CA','MX','AR','CL','CO','PT','ES','FR','DE','IT','NL','BE','CH','AT','IE','AU','NZ','JP','KR','IN','ID','PH','TH','TW','HK','SG','ZA','TR','PL','SE','NO','DK','FI'];
let sheet,currentMeta,currentTitle;
function api(){return window.MatchAppCatalogMedia}
function region(){return api()?.regionCode?.()||'US'}
function name(code){return api()?.countryName?.(code)||code}
function setRegion(code){code=String(code||'').toUpperCase();if(!/^[A-Z]{2}$/.test(code))return;localStorage.setItem('match_user_region',code)}
function countries(meta){const keys=Object.keys(meta?.availability||{}).filter(k=>/^[A-Z]{2}$/.test(k));return [...new Set([...COMMON,...keys])].sort((a,b)=>name(a).localeCompare(name(b)))}
function ensureSheet(){if(sheet)return sheet;sheet=document.createElement('div');sheet.className='ma-title-sheet';sheet.hidden=true;sheet.innerHTML='<section class="ma-title-panel" role="dialog" aria-modal="true" aria-labelledby="ma-title-name"><button class="ma-title-close" type="button" aria-label="Close">×</button><div class="ma-title-body"></div></section>';document.body.appendChild(sheet);sheet.querySelector('.ma-title-close').onclick=close;sheet.addEventListener('click',e=>{if(e.target===sheet)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!sheet.hidden)close()});return sheet}
function close(){if(!sheet)return;sheet.hidden=true;document.documentElement.style.overflow='';document.body.style.overflow=''}
function metaLine(m){return [m.year,m.runtime_minutes?m.runtime_minutes+' min':'',m.content_rating||''].filter(Boolean).join(' · ')}
function providerActions(m,code){const A=api();const av=A?.availability?.(m,code)||{};const links=A?.providerLinks?.(m,currentTitle,code)||[];let html='';if(links.length){html+=links.slice(0,8).map((x,i)=>'<a '+(i===0?'class="primary" ':'')+'href="'+esc(x.href)+'" target="_blank" rel="noopener noreferrer">'+(x.mode==='stream'?'▶ Watch':'Open')+' on '+esc(x.provider)+'</a>').join('')}else html+='<p class="ma-location-note">No verified streaming provider is listed for '+esc(name(code))+' right now.</p>';
if(av.inCinemas)html+='<button class="ma-cinema-near primary" type="button">🎟 Cinemas near me showing '+esc(currentTitle)+'</button>';
if(av.guide)html+='<a href="'+esc(av.guide)+'" target="_blank" rel="noopener noreferrer">Verified regional watch guide ↗</a>';
return {html,av}}
function render(m){currentMeta=m;const s=ensureSheet(),code=region(),pa=providerActions(m,code),orig=(m.origin_countries||[]),cast=(m.cast||[]),genres=(m.genres||[]);const poster=api()?.safePoster?.(m)||m.poster_large_url||m.poster_url||'/assets/brand/matchapp-og.png';const options=countries(m).map(c=>'<option value="'+c+'" '+(c===code?'selected':'')+'>'+esc(name(c))+'</option>').join('');
s.querySelector('.ma-title-body').innerHTML='<div class="ma-title-hero"><img src="'+esc(poster)+'" alt="'+esc(currentTitle)+' poster"><div><h2 id="ma-title-name">'+esc(currentTitle)+'</h2><div class="ma-title-meta">'+esc(metaLine(m))+'</div>'+(orig.length?'<div class="ma-title-origin">Produced in '+esc(orig.map(name).join(', '))+'</div>':'')+(pa.av.inCinemas?'<span class="ma-title-cinema-ribbon">In cinemas</span>':'')+'</div></div>'+
'<div class="ma-title-card"><h3>Synopsis</h3><p>'+esc(m.overview||'Synopsis is not available from the verified title source yet.')+'</p></div>'+
'<div class="ma-title-card"><h3>Categories</h3><div class="ma-title-chips">'+(genres.length?genres.map(g=>'<span>'+esc(g)+'</span>').join(''):'<span>Not listed</span>')+'</div></div>'+
'<div class="ma-title-card"><h3>Cast</h3><p class="ma-title-cast">'+(cast.length?cast.slice(0,10).map(p=>esc(p.name)+(p.character?' as '+esc(p.character):'')).join(' · '):'Cast details are not available from the verified source yet.')+'</p></div>'+
'<div class="ma-title-card"><h3>Where to watch</h3><div class="ma-country-row"><label for="ma-watch-country">Country</label><select id="ma-watch-country">'+options+'</select></div><div class="ma-watch-actions">'+pa.html+'</div><p class="ma-location-note">Streaming availability is country-specific. Provider buttons use the provider’s supported title/search destination when an exact title deep-link is not supplied by the source.</p></div>';
const sel=s.querySelector('#ma-watch-country');sel.onchange=()=>{setRegion(sel.value);render(currentMeta)};
s.querySelector('.ma-cinema-near')?.addEventListener('click',cinemasNear);
}
async function cinemasNear(){const btn=sheet.querySelector('.ma-cinema-near');if(!navigator.geolocation){window.showToast?.('Location is not supported on this device.',true);return}if(btn){btn.disabled=true;btn.textContent='Finding nearby cinemas…'}navigator.geolocation.getCurrentPosition(pos=>{const q=currentTitle+' movie showtimes near '+pos.coords.latitude.toFixed(5)+','+pos.coords.longitude.toFixed(5);window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q),'_blank','noopener,noreferrer');if(btn){btn.disabled=false;btn.textContent='🎟 Cinemas near me showing '+currentTitle}},()=>{window.showToast?.('Location permission is needed to find nearby cinemas.');if(btn){btn.disabled=false;btn.textContent='🎟 Cinemas near me showing '+currentTitle}},{enableHighAccuracy:false,timeout:8000,maximumAge:300000})}
async function open(title){title=String(title||'').trim();if(!title)return false;currentTitle=title;const s=ensureSheet();s.hidden=false;document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';s.querySelector('.ma-title-body').innerHTML='<div class="ma-title-loading">Loading verified title details…</div>';try{let m=await api()?.lookup?.(title);if(m&&api()?.refreshExact)m=await api().refreshExact(m);if(!m)throw new Error('not found');render(m)}catch(_){s.querySelector('.ma-title-body').innerHTML='<div class="ma-title-loading">Verified details are unavailable right now.<br><br><a href="/discover.html?title='+encodeURIComponent(title)+'&focus=start" style="color:#ffe69a">Open title page</a></div>'}return true}
function folds(){const sels=['.daily-checkin','.marquee-wrapper','.tg-entry','main.page-wrapper .container > section','main.page-wrapper .container > .premium-card'];document.querySelectorAll(sels.join(',')).forEach(el=>{if(el.dataset.maFold==='1'||el.closest('.ma-title-sheet')||el.id==='result-box')return;el.dataset.maFold='1';el.classList.add('ma-foldable');const b=document.createElement('button');b.type='button';b.className='ma-fold-toggle';b.setAttribute('aria-label','Fold section');b.textContent='−';b.onclick=e=>{e.preventDefault();e.stopPropagation();const folded=el.classList.toggle('ma-folded');b.textContent=folded?'+':'−';b.setAttribute('aria-label',folded?'Expand section':'Fold section')};el.prepend(b)})}
function firstVisitNotice(){const k='match_daily_checkin_intro_v1';if(localStorage.getItem(k)==='1')return;localStorage.setItem(k,'1');setTimeout(()=>window.showToast?.('✨ New: check in once each day. Keep a 7-day streak to earn 5 Extra Matches — miss a day and the streak restarts.'),1800)}
window.MatchAppHomeTitleDetails={open,close};
function boot(){folds();firstVisitNotice();new MutationObserver(()=>folds()).observe(document.querySelector('main.page-wrapper')||document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();