/* Shared labels and catalog facts always follow the explicit language preference. */
(function(){'use strict';
 const keys=['polish.platforms','polish.titles','polish.languages','polish.privacy','polish.terms','polish.footerTitle','polish.guide','polish.about','polish.age','polish.release','polish.related','polish.providerNote','polish.kidsMatch','polish.classics','polish.kidsFaq','polish.kidsAnswer'];
 const copy={
 en:['streaming platforms searched','curated titles','languages','Privacy policy','Terms of service','Find where to watch, in seconds','Title guide','About','Suggested age bands','Original release','Discover titles from the same era','Providers set availability, prices, dubbing and episode ratings. Ask a grown-up before opening another site.','Kids matching','Classic cartoon guide','Can I match by age, mood and decade?','Yes. Kids Mode filters a reviewed allowlist by age, mood, format and decade. Unknown AI suggestions stay out.'],
 'pt-BR':['plataformas de streaming pesquisadas','títulos selecionados','idiomas','Política de privacidade','Termos de serviço','Encontre onde assistir em segundos','Guia do título','Sobre','Faixas etárias sugeridas','Lançamento original','Descubra títulos da mesma época','Os provedores definem disponibilidade, preços, dublagem e classificação de episódios. Peça ajuda a um adulto ao abrir outro site.','Match Kids','Guia de desenhos clássicos','Posso escolher por idade, clima e década?','Sim. O Modo Kids filtra uma lista revisada por idade, clima, formato e década. Sugestões desconhecidas da IA ficam de fora.'],
 es:['plataformas de streaming consultadas','títulos seleccionados','idiomas','Política de privacidad','Términos del servicio','Encuentra dónde verlo en segundos','Guía del título','Acerca de','Edades sugeridas','Estreno original','Descubre títulos de la misma época','Los proveedores fijan disponibilidad, precios, doblaje y clasificación. Pide ayuda a un adulto antes de abrir otro sitio.','Match Kids','Guía de dibujos clásicos','¿Puedo elegir por edad, ambiente y década?','Sí. Kids Mode filtra una lista revisada por edad, ambiente, formato y década. Excluye sugerencias desconocidas de IA.'],
 fr:['plateformes consultées','titres sélectionnés','langues','Politique de confidentialité','Conditions du service','Trouvez où regarder en quelques secondes','Guide du titre','À propos de','Âges conseillés','Sortie originale','Découvrez des titres de la même époque','Les services fixent disponibilité, prix, doublage et classification. Demandez à un adulte avant d’ouvrir un autre site.','Match Kids','Guide des dessins animés classiques','Puis-je choisir par âge, humeur et décennie ?','Oui. Kids Mode filtre une liste vérifiée par âge, humeur, format et décennie. Les suggestions IA inconnues sont exclues.'],
 de:['geprüfte Streamingdienste','kuratierte Titel','Sprachen','Datenschutz','Nutzungsbedingungen','Finde in Sekunden, wo du schauen kannst','Titelübersicht','Über','Empfohlene Altersgruppen','Erstveröffentlichung','Entdecke Titel aus derselben Zeit','Anbieter bestimmen Verfügbarkeit, Preise, Synchronisation und Altersfreigaben. Bitte vor dem Öffnen anderer Seiten einen Erwachsenen um Hilfe.','Kids-Auswahl','Klassische Zeichentrickserien','Kann ich nach Alter, Stimmung und Jahrzehnt wählen?','Ja. Kids Mode filtert eine geprüfte Liste nach Alter, Stimmung, Format und Jahrzehnt. Unbekannte KI-Vorschläge bleiben draußen.'],
 it:['piattaforme consultate','titoli selezionati','lingue','Informativa sulla privacy','Termini del servizio','Trova dove guardare in pochi secondi','Guida al titolo','Informazioni su','Età consigliate','Uscita originale','Scopri titoli della stessa epoca','I servizi stabiliscono disponibilità, prezzi, doppiaggio e classificazioni. Chiedi aiuto a un adulto prima di aprire altri siti.','Match Kids','Guida ai cartoni classici','Posso scegliere per età, umore e decennio?','Sì. Kids Mode filtra un elenco verificato per età, umore, formato e decennio. Esclude i suggerimenti IA sconosciuti.'],
 tr:['aranan yayın platformları','seçilmiş yapımlar','dil','Gizlilik politikası','Hizmet koşulları','Saniyeler içinde nereden izleyeceğini bul','Yapım rehberi','Hakkında','Önerilen yaş grupları','İlk yayın','Aynı dönemden yapımları keşfet','Hizmetler erişim, fiyat, dublaj ve yaş sınırlarını belirler. Başka siteyi açmadan önce bir yetişkinden yardım iste.','Çocuk eşleşmesi','Klasik çizgi film rehberi','Yaş, ruh hali ve on yıla göre seçebilir miyim?','Evet. Çocuk Modu incelenmiş listeyi yaş, ruh hali, tür ve on yıla göre süzer. Bilinmeyen yapay zekâ önerilerini dışarıda bırakır.'],
 ru:['проверенных платформ','отобранных произведений','языков','Конфиденциальность','Условия использования','Найдите, где смотреть, за секунды','Обзор произведения','О произведении','Рекомендуемый возраст','Первый выпуск','Произведения той же эпохи','Сервисы определяют доступность, цены, дубляж и возрастные ограничения. Попросите взрослого помочь открыть другой сайт.','Детский подбор','Классические мультфильмы','Можно выбрать по возрасту, настроению и десятилетию?','Да. Детский режим фильтрует проверенный список по возрасту, настроению, формату и десятилетию. Неизвестные предложения ИИ исключены.'],
 ar:['منصات بث تم البحث فيها','أعمال مختارة','لغات','سياسة الخصوصية','شروط الخدمة','اعثر على مكان المشاهدة في ثوانٍ','دليل العمل','عن العمل','الفئات العمرية المقترحة','الإصدار الأصلي','اكتشف أعمالًا من الحقبة نفسها','تحدد الخدمات التوفر والأسعار والدبلجة والتصنيف العمري. اطلب مساعدة شخص بالغ قبل فتح موقع آخر.','اختيار للأطفال','دليل الرسوم الكلاسيكية','هل أختار حسب العمر والمزاج والعقد؟','نعم. يرشح وضع الأطفال قائمة مراجعة حسب العمر والمزاج والنوع والعقد. تُستبعد اقتراحات الذكاء الاصطناعي غير المعروفة.'],
 hi:['खोजे गए स्ट्रीमिंग मंच','चुने हुए शीर्षक','भाषाएँ','गोपनीयता नीति','सेवा की शर्तें','कुछ सेकंड में जानें कहाँ देखें','शीर्षक की जानकारी','परिचय','सुझाए गए आयु समूह','पहली रिलीज़','उसी दौर के शीर्षक खोजें','सेवाएँ उपलब्धता, कीमत, डबिंग और आयु सीमा तय करती हैं। दूसरी साइट खोलने से पहले बड़े की मदद लें।','बच्चों का मैच','पुराने कार्टून की जानकारी','क्या उम्र, मूड और दशक से चुन सकते हैं?','हाँ। बच्चों का मोड समीक्षा की गई सूची को उम्र, मूड, प्रकार और दशक से छाँटता है। अज्ञात AI सुझाव बाहर रहते हैं।'],
 id:['platform streaming ditelusuri','judul pilihan','bahasa','Kebijakan privasi','Ketentuan layanan','Temukan tempat menonton dalam hitungan detik','Panduan judul','Tentang','Kelompok usia yang disarankan','Rilis pertama','Temukan judul dari era yang sama','Layanan menentukan ketersediaan, harga, sulih suara dan batas usia. Minta bantuan orang dewasa sebelum membuka situs lain.','Match anak','Panduan kartun klasik','Bisa memilih berdasarkan usia, suasana dan dekade?','Ya. Mode Anak menyaring daftar yang ditinjau berdasarkan usia, suasana, format dan dekade. Saran AI yang tidak dikenal dikecualikan.'],
 ja:['検索する配信サービス','厳選作品','言語','プライバシーポリシー','利用規約','数秒で視聴先を見つけよう','作品ガイド','作品について','おすすめ年齢','初公開','同じ時代の作品を発見','配信サービスが地域、料金、吹替、年齢制限を決めます。別のサイトを開くときは大人に手伝ってもらいましょう。','キッズマッチ','昔のアニメガイド','年齢、気分、年代で選べる？','はい。キッズモードは確認済み作品を年齢、気分、形式、年代で絞ります。未知のAI提案は表示しません。'],
 ko:['검색하는 스트리밍 서비스','엄선한 작품','언어','개인정보 정책','이용약관','몇 초 만에 시청할 곳을 찾으세요','작품 안내','작품 소개','권장 연령대','최초 공개','같은 시대의 작품 찾기','서비스마다 지역, 가격, 더빙, 연령 등급이 다릅니다. 다른 사이트를 열기 전에 어른에게 도움을 요청하세요.','키즈 매치','추억의 만화 안내','나이, 기분, 시대별로 고를 수 있나요?','네. 키즈 모드는 검토한 작품 목록을 나이, 기분, 형식, 시대별로 필터링합니다. 모르는 AI 추천은 제외합니다.'],
 zh:['已搜索的流媒体平台','精选作品','语言','隐私政策','服务条款','几秒内找到观看平台','作品指南','作品介绍','建议年龄段','首次发行','发现同一时代的作品','平台决定地区可用性、价格、配音和年龄评级。打开其他网站前，请向大人求助。','儿童匹配','经典动画指南','能按年龄、心情和年代选择吗？','可以。儿童模式按年龄、心情、类型和年代筛选经过审核的作品。未知的AI推荐不会显示。']
 };
 if(typeof I18N!=='undefined')for(const [lang,values] of Object.entries(copy))keys.forEach((k,i)=>I18N[lang][k]=values[i]);
 if(typeof I18N!=='undefined')for(const [l,value] of Object.entries({"en":"Friends","pt-BR":"Amigos","es":"Amigos","fr":"Amis","de":"Freunde","it":"Amici","tr":"Arkadaşlar","ru":"Друзья","ar":"الأصدقاء","hi":"दोस्त","id":"Teman","ja":"友だち","ko":"친구","zh":"好友"}))I18N[l]['polish.friends']=value;
 if(typeof I18N!=='undefined')for(const [l,value] of Object.entries({"en":"Sign in to host a match. Your guest can join with the invitation link.","pt-BR":"Entre para criar um match. Seu convidado pode participar pelo link.","es":"Inicia sesión para crear un match. Tu invitado puede unirse con el enlace.","fr":"Connectez-vous pour créer un match. Votre invité peut rejoindre par le lien.","de":"Melde dich an, um einen Match zu erstellen. Gäste können über den Link beitreten.","it":"Accedi per creare un match. L’ospite può unirsi tramite il link.","tr":"Eşleşme oluşturmak için giriş yapın. Konuk bağlantıyla katılabilir.","ru":"Войдите, чтобы создать подбор. Гость может присоединиться по ссылке.","ar":"سجل الدخول لإنشاء اختيار مشترك. يمكن لضيفك الانضمام بالرابط.","hi":"मैच बनाने के लिए साइन इन करें। मेहमान आमंत्रण लिंक से जुड़ सकते हैं।","id":"Masuk untuk membuat match. Tamu bisa bergabung lewat tautan.","ja":"マッチを作成するにはログインしてください。ゲストは招待リンクで参加できます。","ko":"매치를 만들려면 로그인하세요. 초대 링크로 손님이 참여할 수 있어요.","zh":"登录后即可创建匹配，访客可通过邀请链接加入。"}))I18N[l]['polish.hostSignIn']=value;
 function translateGuide(){
  const hero=document.querySelector('[data-kids-title]');if(!hero)return;
  const lang=window.MATCH_LANG||'en',c=copy[lang]||copy.en,title=hero.dataset.title,year=hero.dataset.year;
  const headings=hero.querySelectorAll('h2'),paragraphs=hero.querySelectorAll('p');
  document.querySelector('main h1').textContent=title+(year?' ('+year+')':'')+' · '+(window.t?window.t('res.findwhere'):c[6]);
  headings[0].textContent=c[7]+' · '+title;headings[1].textContent=(window.t?window.t('res.findwhere'):c[6])+' · '+title;
  if(lang!=='en')paragraphs[0].textContent=window.KidsDescriptions?.[lang]?.[title]||title+' · '+year+' · '+c[6];
  paragraphs[1].textContent=c[8]+': '+hero.dataset.ages.split(',').filter(x=>x!=='all').join(', ');
  paragraphs[2].textContent=c[9]+' '+year;paragraphs[3].textContent=c[11];
  hero.querySelectorAll('a.watch').forEach(a=>{const region=new URL(a.href).pathname.split('/')[1];a.textContent=new Intl.DisplayNames([lang],{type:'region'}).of(region==='br'?'BR':'US')+' · '+c[6];});
  const main=document.querySelector('main'),remaining=[...main.querySelectorAll('h2')].filter(h=>!hero.contains(h));
  if(remaining[0])remaining[0].textContent=c[10];if(remaining[1])remaining[1].textContent=c[14];
  if(remaining[1]?.nextElementSibling)remaining[1].nextElementSibling.textContent=c[15];
  const crumbs=main.querySelector(':scope > p');if(crumbs)crumbs.textContent='MatchApp Kids › '+c[6];
  document.querySelectorAll('header nav a').forEach((a,i)=>a.textContent=c[12+i]);
  document.querySelectorAll('footer > a').forEach((a,i)=>a.textContent=i===0?c[12]:c[2+i]);
  const note=document.querySelector('footer .note');if(note)note.textContent=c[11];
 }
 document.addEventListener('matchapp:langchange',translateGuide);
 function boot(){if(typeof applyTranslations==='function')applyTranslations(window.MATCH_LANG||'en');translateGuide();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
