/* MatchApp roadmap runtime: progressive enhancement only; explicit user choices remain authoritative. */
(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function emit(name,detail={}){try{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'matchapp_'+name,...detail});}catch(_){} }
function lazyArtwork(){ $$('img:not([loading])').forEach((img,i)=>{if(i>2)img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>emit('artwork_error',{src:String(img.currentSrc||img.src).slice(0,180)}),{once:true});}); }
function observeVitals(){if(!('PerformanceObserver'in window))return;try{new PerformanceObserver(list=>list.getEntries().forEach(e=>{if(e.entryType==='largest-contentful-paint')emit('web_vital',{metric:'LCP',value:Math.round(e.startTime)});if(e.entryType==='layout-shift'&&!e.hadRecentInput)emit('web_vital',{metric:'CLS',value:Number(e.value.toFixed(4))});})).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(list=>list.getEntries().forEach(e=>{if(e.duration>200)emit('web_vital',{metric:'INP_candidate',value:Math.round(e.duration)});})).observe({type:'event',durationThreshold:200,buffered:true});}catch(_){} }
function addTrust(){const result=$('#result')||$('.result-card')||$('.match-result');if(!result||result.querySelector('.match-trust-line'))return;const p=document.createElement('p');p.className='match-trust-line';p.setAttribute('role','note');p.textContent='MatchApp explains recommendations from your selected criteria and verified title metadata. Streaming availability can vary by region.';result.appendChild(p);}
function addRecovery(){const targets=$$('#result-message,.result-message,#match-status,[role="status"]');targets.forEach(el=>{const text=(el.textContent||'').toLowerCase();if(!/no (titles|matches|results)|nothing (matched|matches)|couldn.t find|could not find/.test(text))return;if(el.parentElement?.querySelector('.match-recovery'))return;const box=document.createElement('div');box.className='match-recovery';box.innerHTML='<strong>No silent compromises.</strong><span>Keep your choices, or deliberately broaden one filter and try again.</span><div><button type="button" data-relax="platform">Any platform</button><button type="button" data-relax="decade">Any decade</button><button type="button" data-relax="mood">Any mood</button></div>';box.addEventListener('click',e=>{const b=e.target.closest('[data-relax]');if(!b)return;const k=b.dataset.relax;const candidates={platform:['#platform','[name="platform"]'],decade:['#decade','[name="decade"]'],mood:['#mood','[name="mood"]']}[k]||[];const input=$(candidates.join(','));if(input){if(input.tagName==='SELECT'){const any=[...input.options].find(o=>/any|all/i.test(o.value+' '+o.textContent));input.value=any?any.value:'';}else input.value='any';input.dispatchEvent(new Event('change',{bubbles:true}));input.focus();}emit('zero_result_relax',{filter:k});});el.insertAdjacentElement('afterend',box);emit('zero_result');});}
function recent(){const result=$('#result')||$('.result-card')||$('.match-result');if(!result)return;const title=$('h2,h3,.result-title',result)?.textContent?.trim();if(!title)return;try{const old=JSON.parse(localStorage.getItem('match_recent_discovery')||'[]').filter(x=>x&&x.title!==title);old.unshift({title,at:Date.now()});localStorage.setItem('match_recent_discovery',JSON.stringify(old.slice(0,12)));}catch(_){} }
function shareEnhance(){if(!navigator.share)return;$$('[data-share-title],.share-btn').forEach(btn=>{if(btn.dataset.roadmapShare)return;btn.dataset.roadmapShare='1';btn.addEventListener('click',()=>emit('share_intent'));});}
function run(){lazyArtwork();addTrust();addRecovery();recent();shareEnhance();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();new MutationObserver(()=>requestAnimationFrame(run)).observe(document.documentElement,{childList:true,subtree:true});observeVitals();
})();
