/* ============================================================
   MatchApp — Settings
   ============================================================ */
(function () {
    'use strict';
    const KEY='match_settings',LEGACY_AUTOREAD_KEY='match_voice_autoread',KIDS_MODE_KEY='match_kids_mode';
    const DEFAULTS={fontScale:1,voiceURI:'',voiceRate:1,voicePitch:1,autoRead:true,reduceMotion:false,lazyDefault:false,compactCards:false,theme:'aurora'};
    let settings={...DEFAULTS};
    function syncLegacyAutoRead(){try{localStorage.setItem(LEGACY_AUTOREAD_KEY,settings.autoRead===false?'false':'true');}catch(e){}}
    function load(){try{const raw=localStorage.getItem(KEY);if(raw)settings={...DEFAULTS,...JSON.parse(raw)};if(!raw){const legacy=localStorage.getItem(LEGACY_AUTOREAD_KEY);if(legacy==='false')settings.autoRead=false;else if(legacy==='true')settings.autoRead=true;}syncLegacyAutoRead();}catch(e){settings={...DEFAULTS};syncLegacyAutoRead();}return settings;}
    function persistLocal(){try{localStorage.setItem(KEY,JSON.stringify(settings));}catch(e){}syncLegacyAutoRead();}
    let syncTimer=null;function persistRemote(){clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{const sb=window.supabaseClient;if(!sb)return;try{const {data:{user}}=await sb.auth.getUser();if(!user)return;await sb.auth.updateUser({data:{match_settings:settings}});}catch(e){}},900);}
    function applyFontScale(){document.documentElement.style.setProperty('--font-scale',settings.fontScale);}function applyMotion(){document.documentElement.classList.toggle('reduce-motion',!!settings.reduceMotion);}function applyCompact(){document.documentElement.classList.toggle('compact-cards',!!settings.compactCards);}function applyAll(){applyFontScale();applyMotion();applyCompact();}
    function loadRedesign(){if(location.pathname.startsWith('/kids/')||document.querySelector('link[data-matchapp-redesign]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='/redesign.css?v=192';link.dataset.matchappRedesign='true';document.head.appendChild(link);}
    function kidsLabel(){const code=String(window.MATCH_LANG||localStorage.getItem('match_lang')||document.documentElement.lang||'en').toLowerCase();if(code.startsWith('pt'))return'Modo Kids';if(code.startsWith('es'))return'Modo Niños';if(code.startsWith('fr'))return'Mode Kids';if(code.startsWith('de'))return'Kids-Modus';if(code.startsWith('it'))return'Modalità Kids';if(code.startsWith('tr'))return'Çocuk Modu';if(code.startsWith('ru'))return'Детский режим';if(code.startsWith('ar'))return'وضع الأطفال';if(code.startsWith('hi'))return'Kids Mode';if(code.startsWith('id'))return'Mode Anak';if(code.startsWith('ja'))return'キッズモード';if(code.startsWith('ko'))return'키즈 모드';if(code.startsWith('zh'))return'儿童模式';return'Kids Mode';}
    function installKidsModeToggle(){if(location.pathname.startsWith('/kids/')||document.querySelector('.matchapp-kids-toggle'))return;const btn=document.createElement('button');btn.type='button';btn.className='matchapp-kids-toggle';btn.setAttribute('aria-label',kidsLabel());btn.innerHTML='<i class="kids-toggle-emblem" aria-hidden="true"><img src="/kids/kids-logo.jpeg" alt=""></i><span></span><b class="kids-toggle-star" aria-hidden="true">✦</b>';btn.querySelector('span').textContent=kidsLabel();btn.addEventListener('click',()=>{try{localStorage.setItem(KIDS_MODE_KEY,'true');}catch(e){}location.href='/kids/';});document.body.appendChild(btn);}
    function maybeRedirectKidsMode(){return false;}
    window.MatchSettings={get(k){return k?settings[k]:{...settings};},set(k,v,opts){if(!(k in DEFAULTS))return;if(k==='theme'&&!['aurora','cinema','ocean','sunrise','arcade'].includes(v))return;settings[k]=v;persistLocal();applyAll();if(!opts||opts.sync!==false)persistRemote();document.dispatchEvent(new CustomEvent('matchapp:settingschanged',{detail:{key:k,value:v}}));},reset(){settings={...DEFAULTS};persistLocal();applyAll();persistRemote();document.dispatchEvent(new CustomEvent('matchapp:settingschanged',{detail:{key:'*',value:null}}));},async hydrateFromAccount(){const sb=window.supabaseClient;if(!sb)return;try{const {data:{user}}=await sb.auth.getUser();const remote=user&&user.user_metadata&&user.user_metadata.match_settings;if(!remote)return;let local={};try{local=JSON.parse(localStorage.getItem(KEY)||'{}');}catch(e){}settings={...DEFAULTS,...remote,...local};persistLocal();applyAll();document.dispatchEvent(new CustomEvent('matchapp:settingschanged',{detail:{key:'*',value:null}}));}catch(e){}},listVoices(){return new Promise(resolve=>{if(!('speechSynthesis'in window))return resolve([]);const got=speechSynthesis.getVoices();if(got.length)return resolve(got);let done=false;const finish=()=>{if(done)return;done=true;resolve(speechSynthesis.getVoices());};speechSynthesis.addEventListener('voiceschanged',finish,{once:true});setTimeout(finish,1200);});},resolveVoice(voices,lang){if(!voices||!voices.length)return null;if(settings.voiceURI){const chosen=voices.find(v=>v.voiceURI===settings.voiceURI);if(chosen)return chosen;}const base=String(lang||'en').toLowerCase().split('-')[0];return voices.find(v=>v.lang.toLowerCase().startsWith(base))||voices.find(v=>v.lang.toLowerCase().startsWith('en'))||voices[0];},DEFAULTS};
    load();if(maybeRedirectKidsMode())return;loadRedesign();applyFontScale();const ready=()=>{applyAll();installKidsModeToggle();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();document.addEventListener('matchapp:langchange',()=>{const btn=document.querySelector('.matchapp-kids-toggle'),span=btn&&btn.querySelector('span'),label=kidsLabel();if(span)span.textContent=label;if(btn)btn.setAttribute('aria-label',label);});
})();

/* Main-screen In-App Purchases shortcut. Native SVG/CSS stays sharp from phones to 8K TVs. */
(function(){'use strict';function install(){if(location.pathname!=='/'&&location.pathname!=='/index.html')return;if(document.querySelector('.matchapp-purchase-shortcut'))return;const style=document.createElement('style');style.textContent=`.matchapp-purchase-shortcut{position:fixed;right:1rem;bottom:5.7rem;z-index:1150;display:flex;align-items:center;gap:.65rem;padding:.62rem .85rem .62rem .62rem;border:1px solid #f2c94c77;border-radius:999px;background:linear-gradient(135deg,#171126ee,#241044ee);color:#fff;text-decoration:none;font-weight:900;font-size:.78rem;box-shadow:0 10px 32px #0008,0 0 22px #8b5cf633;backdrop-filter:blur(14px);transition:transform .2s,box-shadow .2s}.matchapp-purchase-shortcut:hover,.matchapp-purchase-shortcut:focus-visible{transform:translateY(-3px) scale(1.03);box-shadow:0 14px 36px #0009,0 0 28px #f2c94c55;outline:2px solid #f2c94c}.purchase-orb{width:2.2rem;height:2.2rem;display:grid;place-items:center;border-radius:50%;background:radial-gradient(circle at 35% 30%,#f2c94c,#8b5cf6 52%,#241044);box-shadow:0 0 18px #8b5cf688;animation:purchaseOrb 2.6s ease-in-out infinite}.purchase-orb svg{width:1.42rem;height:1.42rem;overflow:visible}.purchase-spark{transform-origin:18px 5px;animation:purchaseSpark 1.7s ease-in-out infinite}@keyframes purchaseOrb{50%{transform:translateY(-2px);box-shadow:0 0 28px #f2c94c88}}@keyframes purchaseSpark{50%{transform:scale(1.35) rotate(18deg);opacity:.65}}@media(max-width:520px){.matchapp-purchase-shortcut{right:.65rem;bottom:5.2rem;padding:.55rem}.matchapp-purchase-shortcut span{display:none}}@media(min-width:1920px){.matchapp-purchase-shortcut{font-size:1rem;padding:.8rem 1.05rem}.purchase-orb{width:2.7rem;height:2.7rem}}@media(prefers-reduced-motion:reduce){.purchase-orb,.purchase-spark{animation:none}}`;document.head.appendChild(style);const a=document.createElement('a');a.className='matchapp-purchase-shortcut';a.href='/pricing/pricing.html?focus=matches#matches';a.setAttribute('aria-label','In-App Purchases');a.innerHTML=`<i class="purchase-orb" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><path d="M6.5 9h11l-1 10h-9l-1-10Z" stroke="white" stroke-width="1.8" stroke-linejoin="round"/><path d="M9 9V7a3 3 0 0 1 6 0v2" stroke="white" stroke-width="1.8" stroke-linecap="round"/><path class="purchase-spark" d="m18 2 .7 1.5L20 4l-1.3.6L18 6l-.6-1.4L16 4l1.4-.5L18 2Z" fill="#fff3a6"/></svg></i><span>In-App Purchases</span>`;document.body.appendChild(a);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();})();
