/* MatchApp settings — stable production loader */
(function(){'use strict';
const KEY='match_settings',LEGACY_AUTOREAD_KEY='match_voice_autoread',KIDS_MODE_KEY='match_kids_mode';
const DEFAULTS={fontScale:1,voiceURI:'',voiceRate:1,voicePitch:1,autoRead:true,reduceMotion:false,lazyDefault:false,compactCards:false,theme:'aurora'};let settings={...DEFAULTS},syncTimer=null;
function syncLegacyAutoRead(){try{localStorage.setItem(LEGACY_AUTOREAD_KEY,settings.autoRead===false?'false':'true')}catch(_){}}
function load(){try{const raw=localStorage.getItem(KEY);if(raw)settings={...DEFAULTS,...JSON.parse(raw)};if(!raw){const legacy=localStorage.getItem(LEGACY_AUTOREAD_KEY);if(legacy==='false')settings.autoRead=false;else if(legacy==='true')settings.autoRead=true}}catch(_){settings={...DEFAULTS}}syncLegacyAutoRead()}
function persistLocal(){try{localStorage.setItem(KEY,JSON.stringify(settings))}catch(_){}syncLegacyAutoRead()}
function persistRemote(){clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{const sb=window.supabaseClient;if(!sb)return;try{const {data:{user}}=await sb.auth.getUser();if(user)await sb.auth.updateUser({data:{match_settings:settings}})}catch(_){ }},900)}
function applyAll(){document.documentElement.style.setProperty('--font-scale',settings.fontScale);document.documentElement.classList.toggle('reduce-motion',!!settings.reduceMotion);document.documentElement.classList.toggle('compact-cards',!!settings.compactCards)}
function loadRedesign(){if(location.pathname.startsWith('/kids/')||document.querySelector('link[data-matchapp-redesign]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/redesign.css?v=193';l.dataset.matchappRedesign='true';document.head.appendChild(l)}
function kidsLabel(){const c=String(window.MATCH_LANG||localStorage.getItem('match_lang')||document.documentElement.lang||'en').toLowerCase();if(c.startsWith('pt'))return'Modo Kids';if(c.startsWith('es'))return'Modo Niños';if(c.startsWith('fr'))return'Mode Kids';if(c.startsWith('de'))return'Kids-Modus';if(c.startsWith('it'))return'Modalità Kids';if(c.startsWith('tr'))return'Çocuk Modu';if(c.startsWith('ru'))return'Детский режим';if(c.startsWith('ar'))return'وضع الأطفال';if(c.startsWith('ja'))return'キッズモード';if(c.startsWith('ko'))return'키즈 모드';if(c.startsWith('zh'))return'儿童模式';return'Kids Mode'}
function installKidsModeToggle(){if(location.pathname.startsWith('/kids/')||document.querySelector('.matchapp-kids-toggle'))return;const b=document.createElement('button');b.type='button';b.className='matchapp-kids-toggle';b.setAttribute('aria-label',kidsLabel());b.innerHTML='<i class="kids-toggle-emblem" aria-hidden="true"><img src="/kids/kids-logo.jpeg" alt=""></i><span></span><b class="kids-toggle-star" aria-hidden="true">✦</b>';b.querySelector('span').textContent=kidsLabel();b.addEventListener('click',()=>{try{localStorage.setItem(KIDS_MODE_KEY,'true')}catch(_){}location.href='/kids/'});document.body.appendChild(b)}
window.MatchSettings={get:k=>k?settings[k]:{...settings},set(k,v,opts){if(!(k in DEFAULTS))return;if(k==='theme'&&!['aurora','cinema','ocean','sunrise','arcade'].includes(v))return;settings[k]=v;persistLocal();applyAll();if(!opts||opts.sync!==false)persistRemote();document.dispatchEvent(new CustomEvent('matchapp:settingschanged',{detail:{key:k,value:v}}))},reset(){settings={...DEFAULTS};persistLocal();applyAll();persistRemote();document.dispatchEvent(new CustomEvent('matchapp:settingschanged',{detail:{key:'*',value:null}}))},async hydrateFromAccount(){const sb=window.supabaseClient;if(!sb)return;try{const {data:{user}}=await sb.auth.getUser();const remote=user?.user_metadata?.match_settings;if(!remote)return;let local={};try{local=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){}settings={...DEFAULTS,...remote,...local};persistLocal();applyAll();document.dispatchEvent(new CustomEvent('matchapp:settingschanged',{detail:{key:'*',value:null}}))}catch(_){}},listVoices(){return new Promise(resolve=>{if(!('speechSynthesis'in window))return resolve([]);const got=speechSynthesis.getVoices();if(got.length)return resolve(got);let done=false;const finish=()=>{if(done)return;done=true;resolve(speechSynthesis.getVoices())};speechSynthesis.addEventListener('voiceschanged',finish,{once:true});setTimeout(finish,1200)})},resolveVoice(voices,lang){if(!voices?.length)return null;if(settings.voiceURI){const v=voices.find(x=>x.voiceURI===settings.voiceURI);if(v)return v}const base=String(lang||'en').toLowerCase().split('-')[0];return voices.find(v=>v.lang.toLowerCase().startsWith(base))||voices.find(v=>v.lang.toLowerCase().startsWith('en'))||voices[0]},DEFAULTS};
load();loadRedesign();applyAll();const ready=()=>{applyAll();installKidsModeToggle()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();document.addEventListener('matchapp:langchange',()=>{const b=document.querySelector('.matchapp-kids-toggle'),s=b?.querySelector('span'),l=kidsLabel();if(s)s.textContent=l;if(b)b.setAttribute('aria-label',l)});
})();
(function(){'use strict';const V='20260915-recovery1';function js(src){if(document.querySelector(`script[src^="${src}"]`))return;const s=document.createElement('script');s.src=src+'?v='+V;s.defer=true;document.head.appendChild(s)}function css(src){if(document.querySelector(`link[href^="${src}"]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=src+'?v='+V;document.head.appendChild(l)}css('/emergency-layout.css');js('/activity-cloud-bridge.js');if(location.pathname==='/profile/profile.html'){css('/profile-history.css');js('/profile-history.js');js('/registration-upgrade.js')}if(location.pathname==='/'||location.pathname==='/index.html'||location.pathname==='/discover.html')js('/roadmap-runtime.js');if(location.pathname==='/pricing/pricing.html'||location.pathname==='/pricing/')js('/brl-pricing.js');})();
