/* Reviewed offline Portuguese descriptions. Other locales use localized catalog facts. */
window.KidsDescriptions={
  "pt-BR": {
    "Bluey": "Brincadeiras em família, humor gentil e aventuras do dia a dia.",
    "Peppa Pig": "Histórias curtas sobre família, amigos e rotinas divertidas.",
    "Daniel Tiger's Neighborhood": "Lições acolhedoras sobre sentimentos, rotinas e amizade.",
    "Sesame Street": "Canções, letras, números, gentileza e humor com personagens clássicos.",
    "Numberblocks": "Personagens numéricos coloridos transformam a matemática em pequenas aventuras.",
    "Ask the StoryBots": "Perguntas das crianças respondidas com humor, canções e ciência.",
    "Puffin Rock": "Aventuras tranquilas numa ilha, com papagaios-do-mar, natureza e família.",
    "Pocoyo": "Humor visual simples e curiosidade para os pequenos.",
    "Gabby's Dollhouse": "Artesanato, canções, gatos e aventuras em pequenos mundos imaginários.",
    "Octonauts": "Resgates submarinos inspirados em animais reais do oceano.",
    "Wild Kratts": "Ciência dos animais, exploração e poderes das criaturas.",
    "Shaun the Sheep": "Humor sem palavras na fazenda, com piadas visuais e confusões leves.",
    "My Neighbor Totoro": "Uma história mágica sobre duas irmãs, a natureza e um amigo da floresta.",
    "Kiki's Delivery Service": "Uma jovem bruxa ganha confiança e faz amigos numa cidade à beira-mar.",
    "Paddington": "Um urso muito educado encontra uma família e um lar em Londres.",
    "Paddington 2": "Gentileza, humor e um mistério colorido com Paddington.",
    "Winnie the Pooh": "Uma aventura tranquila no Bosque dos Cem Acres, com Pooh e seus amigos.",
    "The Peanuts Movie": "Charlie Brown tenta ser corajoso enquanto Snoopy vive sua própria aventura.",
    "Luca": "Amizade, curiosidade e um verão ensolarado no litoral italiano.",
    "Ratatouille": "Um rato apaixonado por comida segue seu sonho numa cozinha de Paris.",
    "Super Simple Songs": "Canções simples para rotinas, vocabulário e aprendizado inicial.",
    "The Wiggles": "Canções animadas, movimento e aprendizado para a pré-escola.",
    "Cosmic Kids Yoga": "Histórias com ioga, relaxamento e movimento para crianças.",
    "SciShow Kids": "Explicações de ciência a partir das perguntas do dia a dia das crianças.",
    "The Jetsons": "Uma família do futuro, carros voadores e confusões da era espacial.",
    "The Yogi Bear Show": "Cestas de piquenique, aventuras no parque e humor com ursos.",
    "The Flintstones": "Humor familiar da Idade da Pedra para crianças maiores assistirem com um adulto.",
    "Scooby-Doo, Where Are You!": "Um cachorro simpático e jovens detetives resolvem mistérios assustadores.",
    "Schoolhouse Rock!": "Canções animadas apresentam números, gramática, ciência e história.",
    "The Many Adventures of Winnie the Pooh": "Mel, amizade e pequenas aventuras no Bosque dos Cem Acres.",
    "The Rescuers": "Dois ratinhos corajosos se unem para resgatar uma criança neste clássico de aventura.",
    "The Smurfs": "Pequenos amigos azuis aprendem a trabalhar juntos numa aldeia mágica da floresta.",
    "Inspector Gadget": "Um detetive atrapalhado, sua sobrinha esperta e um cachorro prestativo resolvem casos.",
    "DuckTales": "Uma família de patos explora histórias de tesouros e aventuras distantes.",
    "Chip 'n Dale Rescue Rangers": "Pequenos detetives enfrentam grandes mistérios com cooperação e invenções.",
    "Disney's Adventures of the Gummi Bears": "Ursos mágicos saltam por aventuras medievais e trabalham juntos.",
    "The Care Bears": "Ursos coloridos compartilham lições de carinho e aventuras imaginativas.",
    "Arthur": "Escola, amizade e lições do cotidiano com Arthur e seus amigos.",
    "Rugrats": "A imaginação dos bebês transforma lugares comuns em grandes descobertas.",
    "The Magic School Bus": "Uma turma curiosa faz passeios extraordinários pelo mundo da ciência.",
    "Franklin": "Uma jovem tartaruga aprende sobre gentileza, amizade e rotinas.",
    "Little Bear": "Histórias tranquilas na floresta sobre amizade, família e imaginação.",
    "Dora the Explorer": "Dora e Botas exploram mapas, canções e aventuras de aprendizado.",
    "Clifford the Big Red Dog": "Um cachorro enorme e seus amigos praticam gentileza e convivência.",
    "Kim Possible": "Uma adolescente criativa e seus amigos enfrentam missões cheias de ação.",
    "Phineas and Ferb": "Dois irmãos inventivos enchem os dias de verão com ideias espetaculares.",
    "The Backyardigans": "Amigos do quintal dançam e cantam em mundos de faz de conta.",
    "Doc McStuffins": "Uma médica de brinquedos ensina saúde e empatia aos amigos.",
    "Sofia the First": "Uma jovem princesa descobre gentileza, coragem e amizades mágicas.",
    "Sarah & Duck": "Pequenas aventuras tranquilas e curiosas de Sarah e seu amigo pato.",
    "Hilda": "Uma exploradora corajosa descobre o folclore, a amizade e criaturas mágicas.",
    "Stillwater": "Um panda sábio ajuda as crianças a encontrar calma, perspectiva e gentileza.",
    "Ada Twist, Scientist": "Amigos curiosos fazem perguntas, experimentos e exploram a ciência cotidiana.",
    "Spidey and His Amazing Friends": "Jovens heróis trabalham juntos para resolver problemas e ajudar a comunidade.",
    "Molly of Denali": "Uma menina indígena do Alasca explora sua comunidade com perguntas e descobertas.",
    "The New Adventures of Winnie the Pooh": "Pooh e seus amigos vivem juntos aventuras acolhedoras e imaginativas.",
    "The Woody Woodpecker Show": "O humor físico do Pica-Pau na coleção original da televisão. Crianças maiores devem assistir aos curtas selecionados com um adulto.",
    "The New Woody Woodpecker Show": "Pica-Pau, Chilly Willy e amigos fazem confusões divertidas. Escolha os links em português, espanhol ou inglês.",
    "Garfield and Friends": "Garfield, Odie e os amigos da fazenda transformam dias comuns em histórias engraçadas.",
    "Doug": "Um menino imaginativo aprende sobre amizade, confiança e desafios da escola.",
    "Recess": "Amigos da escola exploram cooperação, justiça e aventuras no recreio.",
    "Hey Arnold!": "Um menino da cidade aprende sobre amizade, empatia e crescimento em seu bairro.",
    "Ben 10": "Um relógio que transforma seu usuário em alienígenas muda uma viagem de verão para resgates de super-herói. Contém lutas animadas.",
    "Lilo & Stitch: The Series": "Lilo e Stitch encontram um lar para experiências alienígenas com cooperação e família."
  }
};
