/* MatchApp Kids immersive play layer. Original UI/mascot; no third-party character/audio assets. */
(function(){'use strict';if(window.__matchappKidsImmersive)return;window.__matchappKidsImmersive=true;
const FX_KEY='match_kids_fx_enabled',VOICE_KEY='match_kids_lumi_voice';
const COPY={en:{wallet:'Kids power',daily:'Daily adventures',matches:'Match tokens',ai:'AI stars',buy:'Grown-ups: add credits',quest:'Build your adventure',questSub:'Choose three things, then Lumi reveals an age-approved match.',mood:'1 · Pick a vibe',format:'2 · Pick a format',era:'3 · Pick a time',reveal:'Reveal my adventure',fine:'Fine-tune the quest',hello:"Hi! I’m Lumi. Ready to build an adventure?",found:'Ta-da! I found a safe adventure for you!',asked:'Sparkle found! Here’s a safe idea.',empty:'Adventure power is empty. A grown-up can add more.'},'pt-BR':{wallet:'Energia Kids',daily:'Aventuras de hoje',matches:'Fichas de Match',ai:'Estrelas da IA',buy:'Adultos: adicionar créditos',quest:'Monte sua aventura',questSub:'Escolha três coisas e a Lumi revela um match aprovado para a idade.',mood:'1 · Escolha o clima',format:'2 · Escolha o formato',era:'3 · Escolha a época',reveal:'Revelar minha aventura',fine:'Ajustar a aventura',hello:'Oi! Eu sou a Lumi. Vamos montar uma aventura?',found:'Tcharam! Achei uma aventura segura para você!',asked:'Brilho encontrado! Aqui vai uma ideia segura.',empty:'A energia de aventura acabou. Um adulto pode adicionar mais.'},es:{wallet:'Energía Kids',daily:'Aventuras de hoy',matches:'Fichas Match',ai:'Estrellas IA',buy:'Adultos: añadir créditos',quest:'Crea tu aventura',questSub:'Elige tres cosas y Lumi revela una opción aprobada para tu edad.',mood:'1 · Elige el ambiente',format:'2 · Elige el formato',era:'3 · Elige la época',reveal:'Revelar mi aventura',fine:'Afinar la aventura',hello:'¡Hola! Soy Lumi. ¿Creamos una aventura?',found:'¡Ta-da! Encontré una aventura segura para ti.',asked:'¡Brillo encontrado! Aquí tienes una idea segura.',empty:'Se acabó la energía de aventura. Un adulto puede añadir más.'}};
Object.assign(COPY,{
fr:{wallet:'Énergie Kids',daily:'Aventures du jour',matches:'Jetons Match',ai:'Étoiles IA',buy:'Adultes : ajouter des crédits',quest:'Crée ton aventure',questSub:'Choisis trois éléments et Lumi révèle un match adapté à ton âge.',mood:'1 · Choisis une ambiance',format:'2 · Choisis un format',era:'3 · Choisis une époque',reveal:'Révéler mon aventure',fine:'Affiner la quête',hello:'Salut ! Je suis Lumi. On crée une aventure ?',found:'Tadaa ! J’ai trouvé une aventure sûre pour toi !',asked:'Étincelle trouvée ! Voici une idée sûre.',empty:'Plus d’énergie aventure. Un adulte peut en ajouter.'},
de:{wallet:'Kids-Energie',daily:'Heutige Abenteuer',matches:'Match-Tokens',ai:'KI-Sterne',buy:'Erwachsene: Credits hinzufügen',quest:'Baue dein Abenteuer',questSub:'Wähle drei Dinge, dann zeigt Lumi einen altersgerechten Match.',mood:'1 · Stimmung wählen',format:'2 · Format wählen',era:'3 · Zeit wählen',reveal:'Abenteuer enthüllen',fine:'Quest fein einstellen',hello:'Hi! Ich bin Lumi. Bereit für ein Abenteuer?',found:'Tadaa! Ich habe ein sicheres Abenteuer gefunden!',asked:'Funke gefunden! Hier ist eine sichere Idee.',empty:'Die Abenteuer-Energie ist leer. Ein Erwachsener kann mehr hinzufügen.'},
it:{wallet:'Energia Kids',daily:'Avventure di oggi',matches:'Gettoni Match',ai:'Stelle IA',buy:'Adulti: aggiungi crediti',quest:'Crea la tua avventura',questSub:'Scegli tre cose e Lumi rivela un match adatto alla tua età.',mood:'1 · Scegli il mood',format:'2 · Scegli il formato',era:'3 · Scegli il periodo',reveal:'Rivela la mia avventura',fine:'Regola la missione',hello:'Ciao! Sono Lumi. Creiamo un’avventura?',found:'Ta-da! Ho trovato un’avventura sicura per te!',asked:'Scintilla trovata! Ecco un’idea sicura.',empty:'Energia avventura finita. Un adulto può aggiungerne.'},
tr:{wallet:'Kids enerjisi',daily:'Bugünkü maceralar',matches:'Match jetonları',ai:'AI yıldızları',buy:'Yetişkinler: kredi ekle',quest:'Maceranı kur',questSub:'Üç seçim yap; Lumi yaşına uygun bir eşleşme göstersin.',mood:'1 · Hava seç',format:'2 · Format seç',era:'3 · Dönem seç',reveal:'Maceramı göster',fine:'Macera ayarları',hello:'Merhaba! Ben Lumi. Bir macera kuralım mı?',found:'Ta-da! Sana güvenli bir macera buldum!',asked:'Işıltı bulundu! İşte güvenli bir fikir.',empty:'Macera enerjisi bitti. Bir yetişkin daha ekleyebilir.'},
ru:{wallet:'Энергия Kids',daily:'Приключения сегодня',matches:'Жетоны Match',ai:'Звёзды ИИ',buy:'Взрослым: добавить кредиты',quest:'Собери приключение',questSub:'Выбери три вещи, и Lumi покажет вариант по возрасту.',mood:'1 · Выбери настроение',format:'2 · Выбери формат',era:'3 · Выбери время',reveal:'Открыть приключение',fine:'Настроить квест',hello:'Привет! Я Lumi. Соберём приключение?',found:'Та-да! Я нашла безопасное приключение!',asked:'Искорка найдена! Вот безопасная идея.',empty:'Энергия приключений закончилась. Взрослый может добавить.'},
ar:{wallet:'طاقة الأطفال',daily:'مغامرات اليوم',matches:'رموز المطابقة',ai:'نجوم الذكاء',buy:'للكبار: إضافة رصيد',quest:'اصنع مغامرتك',questSub:'اختر ثلاثة أشياء ثم تكشف Lumi اقتراحاً مناسباً للعمر.',mood:'1 · اختر المزاج',format:'2 · اختر النوع',era:'3 · اختر الفترة',reveal:'اكشف مغامرتي',fine:'ضبط المغامرة',hello:'مرحباً! أنا Lumi. هل نبني مغامرة؟',found:'ها هي! وجدت مغامرة آمنة لك!',asked:'وجدنا اللمعة! إليك فكرة آمنة.',empty:'انتهت طاقة المغامرة. يمكن لشخص بالغ إضافة المزيد.'},
hi:{wallet:'Kids पावर',daily:'आज के रोमांच',matches:'Match टोकन',ai:'AI सितारे',buy:'बड़ों के लिए: क्रेडिट जोड़ें',quest:'अपना रोमांच बनाओ',questSub:'तीन चीज़ें चुनो और Lumi उम्र के अनुसार सुरक्षित मैच दिखाएगी।',mood:'1 · मूड चुनो',format:'2 · फॉर्मेट चुनो',era:'3 · समय चुनो',reveal:'मेरा रोमांच दिखाओ',fine:'क्वेस्ट को ठीक करें',hello:'हाय! मैं Lumi हूँ। रोमांच बनाएँ?',found:'टा-डा! मुझे तुम्हारे लिए सुरक्षित रोमांच मिला!',asked:'चमक मिल गई! यह सुरक्षित आइडिया है।',empty:'रोमांच पावर खत्म है। कोई बड़ा और जोड़ सकता है।'},
id:{wallet:'Energi Kids',daily:'Petualangan hari ini',matches:'Token Match',ai:'Bintang AI',buy:'Orang dewasa: tambah kredit',quest:'Buat petualanganmu',questSub:'Pilih tiga hal lalu Lumi menampilkan match sesuai usia.',mood:'1 · Pilih suasana',format:'2 · Pilih format',era:'3 · Pilih masa',reveal:'Buka petualanganku',fine:'Atur petualangan',hello:'Hai! Aku Lumi. Siap membuat petualangan?',found:'Ta-da! Aku menemukan petualangan aman untukmu!',asked:'Kilau ditemukan! Ini ide yang aman.',empty:'Energi petualangan habis. Orang dewasa bisa menambah.'},
ja:{wallet:'Kids パワー',daily:'今日の冒険',matches:'Match トークン',ai:'AI スター',buy:'保護者：クレジット追加',quest:'冒険をつくろう',questSub:'3つ選ぶと、Lumiが年齢に合った安全なMatchを見つけます。',mood:'1 · 気分を選ぶ',format:'2 · 形式を選ぶ',era:'3 · 時代を選ぶ',reveal:'冒険を発見',fine:'もっと細かく選ぶ',hello:'こんにちは！Lumiだよ。冒険をつくる？',found:'じゃーん！安全な冒険を見つけたよ！',asked:'キラキラ発見！安全なアイデアだよ。',empty:'冒険パワーがなくなりました。保護者が追加できます。'},
ko:{wallet:'Kids 파워',daily:'오늘의 모험',matches:'Match 토큰',ai:'AI 별',buy:'보호자: 크레딧 추가',quest:'모험 만들기',questSub:'세 가지를 고르면 Lumi가 나이에 맞는 안전한 Match를 찾아요.',mood:'1 · 기분 고르기',format:'2 · 형식 고르기',era:'3 · 시대 고르기',reveal:'내 모험 공개',fine:'더 자세히 고르기',hello:'안녕! 나는 Lumi야. 모험을 만들어 볼까?',found:'짜잔! 안전한 모험을 찾았어!',asked:'반짝임 발견! 안전한 아이디어야.',empty:'모험 파워가 다 됐어요. 보호자가 더 추가할 수 있어요.'},
zh:{wallet:'Kids 能量',daily:'今日冒险',matches:'Match 代币',ai:'AI 星星',buy:'家长：添加额度',quest:'打造你的冒险',questSub:'选择三项，Lumi 会揭晓适龄的安全 Match。',mood:'1 · 选择心情',format:'2 · 选择形式',era:'3 · 选择年代',reveal:'揭晓我的冒险',fine:'微调冒险',hello:'嗨！我是 Lumi。一起打造冒险吗？',found:'当当！我找到一个安全的冒险！',asked:'找到闪光啦！这是一个安全的点子。',empty:'冒险能量用完了。家长可以添加更多。'}
});
const VOICE_ASSIST_COPY={
 en:{askQuestion:'Ask your question!',assistantLabel:'Ask Lumi a question by voice',noSpeech:"I didn't catch that. Tap me and try again!",micDenied:'I need microphone permission to hear you.',voiceUnavailable:'Voice listening is not available on this device.'},
 'pt-BR':{askQuestion:'Faça sua pergunta!',assistantLabel:'Pergunte à Lumi por voz',noSpeech:'Não consegui ouvir. Toque em mim e tente de novo!',micDenied:'Preciso da permissão do microfone para ouvir você.',voiceUnavailable:'A escuta por voz não está disponível neste aparelho.'},
 es:{askQuestion:'¡Haz tu pregunta!',assistantLabel:'Pregúntale a Lumi por voz',noSpeech:'No te escuché. ¡Tócame e inténtalo otra vez!',micDenied:'Necesito permiso para usar el micrófono y escucharte.',voiceUnavailable:'La escucha por voz no está disponible en este dispositivo.'},
 fr:{askQuestion:'Pose ta question !',assistantLabel:'Pose une question à Lumi à la voix',noSpeech:'Je ne t’ai pas entendu. Touche-moi et réessaie !',micDenied:'J’ai besoin de l’autorisation du micro pour t’entendre.',voiceUnavailable:'L’écoute vocale n’est pas disponible sur cet appareil.'},
 de:{askQuestion:'Stell deine Frage!',assistantLabel:'Frag Lumi per Stimme',noSpeech:'Ich habe dich nicht gehört. Tipp mich an und versuch es noch einmal!',micDenied:'Ich brauche Mikrofonzugriff, um dich zu hören.',voiceUnavailable:'Spracheingabe ist auf diesem Gerät nicht verfügbar.'},
 it:{askQuestion:'Fai la tua domanda!',assistantLabel:'Fai una domanda a Lumi con la voce',noSpeech:'Non ti ho sentito. Toccami e riprova!',micDenied:'Mi serve il permesso del microfono per sentirti.',voiceUnavailable:'L’ascolto vocale non è disponibile su questo dispositivo.'},
 tr:{askQuestion:'Sorunu sor!',assistantLabel:"Lumi'ye sesli soru sor",noSpeech:'Seni duyamadım. Bana dokunup tekrar dene!',micDenied:'Seni duyabilmem için mikrofon izni gerekiyor.',voiceUnavailable:'Bu cihazda sesli dinleme kullanılamıyor.'},
 ru:{askQuestion:'Задай свой вопрос!',assistantLabel:'Спроси Lumi голосом',noSpeech:'Я не расслышала. Нажми на меня и попробуй ещё раз!',micDenied:'Мне нужен доступ к микрофону, чтобы тебя слышать.',voiceUnavailable:'Голосовой ввод недоступен на этом устройстве.'},
 ar:{askQuestion:'اسأل سؤالك!',assistantLabel:'اسأل Lumi بصوتك',noSpeech:'لم أسمعك. اضغط عليّ وحاول مرة أخرى!',micDenied:'أحتاج إلى إذن الميكروفون حتى أسمعك.',voiceUnavailable:'الاستماع الصوتي غير متاح على هذا الجهاز.'},
 hi:{askQuestion:'अपना सवाल पूछो!',assistantLabel:'Lumi से आवाज़ में सवाल पूछें',noSpeech:'मैं सुन नहीं पाई। मुझे टैप करके फिर कोशिश करो!',micDenied:'तुम्हें सुनने के लिए मुझे माइक्रोफ़ोन की अनुमति चाहिए।',voiceUnavailable:'इस डिवाइस पर वॉइस सुनना उपलब्ध नहीं है।'},
 id:{askQuestion:'Tanyakan pertanyaanmu!',assistantLabel:'Tanya Lumi dengan suara',noSpeech:'Aku belum dengar. Ketuk aku lalu coba lagi!',micDenied:'Aku perlu izin mikrofon untuk mendengarmu.',voiceUnavailable:'Pendengaran suara tidak tersedia di perangkat ini.'},
 ja:{askQuestion:'質問してね！',assistantLabel:'Lumiに声で質問する',noSpeech:'聞き取れなかったよ。もう一度タップして話してね！',micDenied:'声を聞くためにマイクの許可が必要だよ。',voiceUnavailable:'この端末では音声入力を利用できません。'},
 ko:{askQuestion:'질문해 줘!',assistantLabel:'Lumi에게 음성으로 질문하기',noSpeech:'잘 못 들었어. 나를 탭하고 다시 말해 줘!',micDenied:'네 목소리를 들으려면 마이크 권한이 필요해.',voiceUnavailable:'이 기기에서는 음성 듣기를 사용할 수 없어.'},
 zh:{askQuestion:'问你的问题吧！',assistantLabel:'用语音向 Lumi 提问',noSpeech:'我没听清。点一下我再试一次吧！',micDenied:'我需要麦克风权限才能听见你。',voiceUnavailable:'此设备不支持语音聆听。'}
};
Object.entries(VOICE_ASSIST_COPY).forEach(([code,extra])=>Object.assign(COPY[code]||(COPY[code]={}),extra));

function lang(){const raw=String(document.documentElement.lang||localStorage.getItem('match_lang')||'en');if(/^pt/i.test(raw))return'pt-BR';return COPY[raw]?raw:(COPY[raw.split('-')[0]]?raw.split('-')[0]:'en')}function t(k){return COPY[lang()]?.[k]||COPY.en[k]||k}
function fxOn(){try{return localStorage.getItem(FX_KEY)!=='false'}catch(_){return true}}let ctx=null;function tone(freq,duration=.08,gain=.007,delay=0,type='sine'){if(!fxOn())return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;ctx=ctx||new AC();if(ctx.state==='suspended')ctx.resume?.().catch?.(()=>{});const o=ctx.createOscillator(),g=ctx.createGain(),s=ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,s);g.gain.setValueAtTime(.0001,s);g.gain.exponentialRampToValueAtTime(Math.min(.018,gain),s+.01);g.gain.exponentialRampToValueAtTime(.0001,s+duration);o.connect(g);g.connect(ctx.destination);o.start(s);o.stop(s+duration+.02)}
function sound(kind){if(kind==='choice'){tone(520,.055,.006);tone(690,.065,.004,.035,'triangle');return}if(kind==='quest'){tone(392,.07,.006);tone(523.25,.09,.005,.04);tone(783.99,.12,.0035,.085);return}if(kind==='reveal'){tone(392,.1,.007);tone(587.33,.13,.005,.055);tone(783.99,.16,.0035,.12);return}if(kind==='ai'){tone(659.25,.075,.005);tone(880,.11,.0035,.05);return}if(kind==='save'){tone(523.25,.07,.005);tone(659.25,.09,.0035,.04);return}if(kind==='hello'){tone(440,.06,.005);tone(659.25,.08,.004,.045);return}tone(410,.045,.0045)}
const VOICE_LABELS={en:['Hear Lumi','Lumi quiet'],'pt-BR':['Ouvir Lumi','Lumi em silêncio'],es:['Escuchar a Lumi','Lumi en silencio'],fr:['Écouter Lumi','Lumi silencieuse'],de:['Lumi hören','Lumi leise'],it:['Ascolta Lumi','Lumi silenziosa'],tr:["Lumi'yi dinle",'Lumi sessiz'],ru:['Слушать Lumi','Lumi молчит'],ar:['استمع إلى Lumi','Lumi صامتة'],hi:['Lumi को सुनें','Lumi शांत'],id:['Dengar Lumi','Lumi diam'],ja:['Lumiを聞く','Lumiは静か'],ko:['Lumi 듣기','Lumi 조용히'],zh:['听 Lumi','Lumi 安静']};
function lumiVoiceOn(){try{return localStorage.getItem(VOICE_KEY)!=='false'}catch(_){return true}}
function setTalking(on){const box=document.getElementById('kids-talking');if(box)box.hidden=!on}
let lumiAfterSpeech=null,nativeLumiSpeaking=false,lumiSpeechToken=0;
function finishLumiSpeech(token){if(token!==lumiSpeechToken)return;const done=lumiAfterSpeech;lumiAfterSpeech=null;setTalking(false);if(typeof done==='function')setTimeout(done,0)}
function stopLumiVoice(){lumiSpeechToken++;lumiAfterSpeech=null;nativeLumiSpeaking=false;try{window.MatchAppNativeVoice?.stopSpeaking?.()}catch(_){}try{speechSynthesis?.cancel?.()}catch(_){}setTalking(false)}
function paintLumiVoice(){const b=document.getElementById('kids-voice-toggle');if(!b)return;const on=lumiVoiceOn(),labels=VOICE_LABELS[lang()]||VOICE_LABELS.en;b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',labels[on?0:1]);const label=b.querySelector('[data-voice-label]');if(label)label.textContent=labels[on?0:1]}
let lumiVoices=[];function cacheLumiVoices(){try{lumiVoices=speechSynthesis?.getVoices?.()||[]}catch(_){lumiVoices=[]}return lumiVoices}function pickLumiVoice(language){const tag=String(language||'en').toLowerCase(),base=tag.split('-')[0],voices=lumiVoices.length?lumiVoices:cacheLumiVoices();let best=null,bestScore=-1e9;for(const voice of voices){const vtag=String(voice.lang||'').toLowerCase(),name=String(voice.name||'').toLowerCase();if(vtag.split('-')[0]!==base)continue;let score=vtag===tag?80:48;if(voice.localService)score+=18;if(voice.default)score+=4;if(/child|kid|young|junior/.test(name))score+=48;if(/neural|natural|enhanced|premium|wavenet|studio/.test(name))score+=24;if(/aria|jenny|ava|samantha|zira|luciana|francisca|helena|paulina|joana/.test(name))score+=10;if(/male|david|mark|daniel|george|guy|jorge|ricardo|carlos|felipe|paulo/.test(name))score-=12;if(score>bestScore){bestScore=score;best=voice}}return best}
window.matchAppNativeLumiState=active=>{setTalking(!!active);if(active){nativeLumiSpeaking=true;return}if(nativeLumiSpeaking){nativeLumiSpeaking=false;finishLumiSpeech(lumiSpeechToken)}};function speakLumi(text,onDone){const value=String(text||'').replace(/\s+/g,' ').trim().slice(0,520);if(!value||!lumiVoiceOn()||document.hidden)return false;stopLumiVoice();const token=++lumiSpeechToken;lumiAfterSpeech=typeof onDone==='function'?onDone:null;try{if(typeof window.MatchAppNativeVoice?.speak==='function'){nativeLumiSpeaking=false;setTalking(true);window.MatchAppNativeVoice.speak(value,lang());return true}if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){lumiAfterSpeech=null;return false}const utter=new SpeechSynthesisUtterance(value);utter.lang=lang();const voice=pickLumiVoice(utter.lang);if(voice)utter.voice=voice;utter.rate=1.12;utter.pitch=1.24;utter.volume=.94;utter.onstart=()=>setTalking(true);utter.onend=()=>finishLumiSpeech(token);utter.onerror=()=>{if(token===lumiSpeechToken){lumiAfterSpeech=null;setTalking(false)}};speechSynthesis.speak(utter);return true}catch(_){if(token===lumiSpeechToken)lumiAfterSpeech=null;setTalking(false);return false}}
function enableLumiVoice(){try{localStorage.setItem(VOICE_KEY,'true')}catch(_){}paintLumiVoice()}
window.MatchAppLumi={speak:speakLumi,stop:stopLumiVoice,t,lang,enable:enableLumiVoice,voiceOn:lumiVoiceOn};
function installLumiVoice(){cacheLumiVoices();try{speechSynthesis?.addEventListener?.('voiceschanged',cacheLumiVoices)}catch(_){}const toggle=document.getElementById('kids-voice-toggle');if(toggle&&!toggle.dataset.lumiVoice){toggle.dataset.lumiVoice='1';toggle.addEventListener('click',()=>{const next=!lumiVoiceOn();try{localStorage.setItem(VOICE_KEY,String(next))}catch(_){}if(!next)stopLumiVoice();paintLumiVoice();if(next)speakLumi(t('hello'))})}const answer=document.getElementById('kids-answer-speak');if(answer&&!answer.dataset.lumiVoice){answer.dataset.lumiVoice='1';answer.hidden=false;answer.addEventListener('click',()=>speakLumi(document.getElementById('kids-answer')?.textContent||''))}const title=document.getElementById('kids-title-speak');if(title&&!title.dataset.lumiVoice){title.dataset.lumiVoice='1';title.addEventListener('click',()=>speakLumi(document.getElementById('kids-watch-name')?.textContent||''))}const stop=document.getElementById('kids-talking-stop');if(stop&&!stop.dataset.lumiVoice){stop.dataset.lumiVoice='1';stop.addEventListener('click',stopLumiVoice)}addEventListener('pagehide',stopLumiVoice,{once:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopLumiVoice()});paintLumiVoice()}
function installFxToggle(){const tools=document.querySelector('.kids-tools');if(!tools||document.getElementById('kids-fx-toggle'))return;const b=document.createElement('button');b.id='kids-fx-toggle';b.className='kids-pill kids-tool kids-fx-toggle';b.type='button';const paint=()=>{const on=fxOn();b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',on?'Sound effects on':'Sound effects off');b.innerHTML='<span class="kids-pill-ico" aria-hidden="true">'+(on?'🔊':'🔇')+'</span><span>'+(on?'FX':'Muted')+'</span>'};b.addEventListener('click',()=>{try{localStorage.setItem(FX_KEY,String(!fxOn()))}catch(_){}paint();if(fxOn())sound('hello')});paint();const motion=document.getElementById('kids-motion');motion?.insertAdjacentElement('afterend',b)||tools.prepend(b)}
function bubble(text){const el=document.getElementById('kids-lumi-bubble');if(el)el.textContent=text}
function installLumi(){const art=document.querySelector('.kids-hero-art'),img=art?.querySelector('.kids-mascot');if(!art||!img)return;img.src='/kids/lumi.svg?v=20261001-immersive1';if(!document.getElementById('kids-lumi-bubble')){const b=document.createElement('div');b.id='kids-lumi-bubble';b.className='kids-lumi-bubble';b.textContent=t('hello');art.appendChild(b);['s1','s2','s3'].forEach((c,i)=>{const s=document.createElement('span');s.className='kids-lumi-spark '+c;s.textContent=i===1?'✧':'✦';s.setAttribute('aria-hidden','true');art.appendChild(s)})}const activate=()=>{bubble(t('hello'));sound('hello');speakLumi(t('hello'))};img.style.cursor='pointer';img.setAttribute('role','button');img.tabIndex=0;img.setAttribute('aria-label',t('hello'));img.addEventListener('click',activate);img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})}
let wallet=null;async function refreshWallet(detail){if(!wallet)return;let s=detail;try{if(!s||typeof s.remaining!=='number')s=await window.KidsAccount?.status?.()}catch(_){}if(!s)return;wallet.querySelector('[data-kids-daily]').textContent=String(Math.max(0,Number(s.remaining)||0))+'/'+String(Math.max(0,Number(s.limit)||3));wallet.querySelector('[data-kids-matches]').textContent=String(Math.max(0,Number(s.kids_purchased_matches)||0));wallet.querySelector('[data-kids-ai]').textContent=String(Math.max(0,Number(s.kids_credits)||0))}
function parentPacks(e){e?.preventDefault?.();const go=()=>{try{localStorage.setItem('match_kids_mode','true')}catch(_){}location.href='/pricing/pricing.html?focus=kids#kids-packs-section'};if(typeof window.KidsGrownUpCheck==='function')window.KidsGrownUpCheck().then(ok=>{if(ok)go()}).catch(()=>{})}
function installWallet(){const host=document.querySelector('.kids-hero-copy');if(!host||document.getElementById('kids-wallet'))return;wallet=document.createElement('div');wallet.id='kids-wallet';wallet.className='kids-wallet';wallet.innerHTML='<span class="kids-wallet-title">'+t('wallet')+'</span><span class="kids-wallet-stat">'+t('daily')+': <strong data-kids-daily>…</strong></span><span class="kids-wallet-stat">'+t('matches')+': <strong data-kids-matches>…</strong></span><span class="kids-wallet-stat">'+t('ai')+': <strong data-kids-ai>…</strong></span><button id="kids-buy-credits" class="kids-wallet-buy" type="button">'+t('buy')+'</button>';host.insertBefore(wallet,host.querySelector('.kids-hero-actions'));wallet.querySelector('#kids-buy-credits').addEventListener('click',parentPacks);refreshWallet()}
function choicesFor(select,preferred){const opts=[...select.options].filter(o=>preferred.includes(o.value));return opts.length?opts:[...select.options].slice(0,6)}function choiceRow(label,select,preferred){const box=document.createElement('div');box.className='kids-quest-step';box.innerHTML='<strong>'+label+'</strong><div class="kids-quest-options"></div>';const row=box.lastElementChild,opts=choicesFor(select,preferred);const paint=()=>row.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===select.value)));opts.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='kids-quest-choice';b.dataset.value=o.value;b.textContent=o.textContent.trim();b.addEventListener('click',()=>{select.value=o.value;select.dispatchEvent(new Event('change',{bubbles:true}));paint();sound('choice')});row.appendChild(b)});paint();select.addEventListener('change',paint);return box}
function installQuest(){const form=document.getElementById('kids-match-form'),match=form?.closest('.kids-match');if(!form||!match||document.getElementById('kids-quest'))return;const mood=document.getElementById('kids-match-mood'),format=document.getElementById('kids-match-format'),era=document.getElementById('kids-match-era');const quest=document.createElement('section');quest.id='kids-quest';quest.className='kids-quest';quest.innerHTML='<div class="kids-quest-head"><div><h3 id="kids-quest-title">'+t('quest')+'</h3><p>'+t('questSub')+'</p></div></div>';quest.append(choiceRow(t('mood'),mood,['funny','adventure','animals','learning','bedtime','music','all']),choiceRow(t('format'),format,['all','series','movie','music']),choiceRow(t('era'),era,['all','1990','2000','2010','2020']));const reveal=document.createElement('button');reveal.type='button';reveal.className='kids-primary kids-quest-reveal';reveal.textContent='✦ '+t('reveal');reveal.addEventListener('click',()=>{sound('quest');form.requestSubmit()});quest.appendChild(reveal);form.insertAdjacentElement('beforebegin',quest);const fine=document.createElement('details');fine.className='kids-finetune';const sum=document.createElement('summary');sum.textContent=t('fine');fine.appendChild(sum);form.insertAdjacentElement('beforebegin',fine);fine.appendChild(form)}
function reveal(event){const stage=document.getElementById('kids-match-stage'),dialog=document.getElementById('kids-watch-dialog'),title=String(event?.detail?.title||'').trim();stage?.classList.add('is-kids-revealing');dialog?.classList.add('is-kids-revealing');bubble(t('found'));sound('reveal');speakLumi(t('found')+(title?' '+title:''));setTimeout(()=>{stage?.classList.remove('is-kids-revealing');dialog?.classList.remove('is-kids-revealing')},900)}
function paintCopy(){if(document.getElementById('kids-lumi-bubble'))bubble(t('hello'));document.querySelector('.kids-mascot')?.setAttribute('aria-label',t('hello'));if(wallet){wallet.querySelector('.kids-wallet-title').textContent=t('wallet');wallet.querySelector('#kids-buy-credits').textContent=t('buy');const stats=wallet.querySelectorAll('.kids-wallet-stat');if(stats[0])stats[0].childNodes[0].nodeValue=t('daily')+': ';if(stats[1])stats[1].childNodes[0].nodeValue=t('matches')+': ';if(stats[2])stats[2].childNodes[0].nodeValue=t('ai')+': '}const q=document.getElementById('kids-quest');if(q){q.querySelector('h3').textContent=t('quest');q.querySelector('p').textContent=t('questSub');const labels=[t('mood'),t('format'),t('era')];q.querySelectorAll('.kids-quest-step>strong').forEach((el,i)=>el.textContent=labels[i]||el.textContent);q.querySelector('.kids-quest-reveal').textContent='✦ '+t('reveal');const selects=['kids-match-mood','kids-match-format','kids-match-era'];q.querySelectorAll('.kids-quest-step').forEach((step,i)=>{const s=document.getElementById(selects[i]);step.querySelectorAll('.kids-quest-choice').forEach(b=>{const o=[...s.options].find(x=>x.value===b.dataset.value);if(o)b.textContent=o.textContent.trim()})})}const fine=document.querySelector('.kids-finetune>summary');if(fine)fine.textContent=t('fine');refreshWallet()}
function boot(){installFxToggle();installLumi();installLumiVoice();installWallet();installQuest();document.getElementById('kids-lang')?.addEventListener('change',()=>setTimeout(()=>{paintCopy();paintLumiVoice();stopLumiVoice()},0));document.addEventListener('matchapp:kids-result',reveal);document.addEventListener('matchapp:kids-ai-result',event=>{bubble(t('asked'));sound('ai');const title=String(event?.detail?.title||'').trim();if(!document.getElementById('kids-lumi-assistant'))speakLumi(t('asked')+(title?' '+title:''))});document.addEventListener('matchapp:kids-quota',e=>refreshWallet(e.detail));document.addEventListener('matchapp:kids-quota-empty',()=>{bubble(t('empty'));if(!document.getElementById('kids-lumi-assistant'))speakLumi(t('empty'))});document.addEventListener('matchapp:kids-favorites',()=>sound('save'));document.addEventListener('matchapp:authchange',()=>refreshWallet())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()})();