/* Match-specific copy supplements the existing fourteen-language Kids interface. */
window.KidsMatchCopy={};
(function(){
 const keys=['resultTitle','matchFree','opening','quotaEmpty','quotaError','quotaUsed','synopsis','share','copy','copied','saveLater','seenIt','lovedIt','notForMe','historySaved','historyError','sameCriteria','newCriteria','account'];
 const rows={
 fr:['Ta prochaine aventure','Ouvrir un titre utilise un match du compte ou du quota invité. Regarder, partager et enregistrer ce résultat ne coûte pas de match supplémentaire.','Ton aventure se prépare…','Tu as utilisé tes matchs du jour. Demande de l’aide à un adulte ou reviens demain.','Impossible de vérifier tes matchs. Réessaie.','1 match utilisé','L’histoire','Partager cette aventure','Copier le lien','Lien copié !','À regarder plus tard','Déjà vu','J’ai adoré','Pas pour moi','Enregistré dans ton historique.','Enregistrement impossible. Réessaie.','Un autre avec ces choix','Choisir une nouvelle aventure','Adultes : compte et matchs'],
 de:['Dein nächstes Abenteuer','Einen Titel zu öffnen nutzt ein Match vom Konto oder Gastkontingent. Anschauen, Teilen und Speichern dieses Ergebnisses nutzt kein weiteres Match.','Dein Abenteuer wird vorbereitet…','Deine heutigen Matches sind aufgebraucht. Bitte einen Erwachsenen um Hilfe oder komm morgen wieder.','Matches konnten nicht geprüft werden. Versuch es erneut.','1 Match genutzt','Die Geschichte','Abenteuer teilen','Link kopieren','Link kopiert!','Später ansehen','Schon gesehen','Hat mir gefallen','Nichts für mich','Im Verlauf gespeichert.','Speichern fehlgeschlagen. Versuch es erneut.','Noch eins mit diesen Wünschen','Neues Abenteuer wählen','Erwachsene: Konto und Matches'],
 it:['La tua prossima avventura','Aprire un titolo usa un match del conto o del limite ospiti. Guardare, condividere e salvare questo risultato non usa un altro match.','Prepariamo la tua avventura…','Hai usato i match di oggi. Chiedi aiuto a un adulto o torna domani.','Impossibile verificare i match. Riprova.','1 match usato','La storia','Condividi questa avventura','Copia link','Link copiato!','Guarda più tardi','Già visto','Adorato','Non fa per me','Salvato nella cronologia.','Impossibile salvare. Riprova.','Un altro con queste scelte','Scegli una nuova avventura','Adulti: conto e match'],
 tr:['Sıradaki maceran','Bir yapımı açmak hesap veya misafir kotasından bir eşleşme kullanır. Bu sonucu izlemek, paylaşmak ve kaydetmek ek hak kullanmaz.','Maceran hazırlanıyor…','Bugünkü hakların bitti. Bir yetişkinden yardım iste veya yarın gel.','Hakların kontrol edilemedi. Yeniden dene.','1 eşleşme kullanıldı','Hikâye','Macerayı paylaş','Bağlantıyı kopyala','Bağlantı kopyalandı!','Sonra izle','İzledim','Bayıldım','Bana göre değil','Geçmişine kaydedildi.','Kaydedilemedi. Yeniden dene.','Bu seçimlerle bir tane daha','Yeni macera seç','Yetişkinler: hesap ve haklar'],
 ru:['Твоё следующее приключение','Открытие произведения использует один подбор из квоты аккаунта или гостя. Просмотр, сохранение и отправка этого результата не тратят дополнительный подбор.','Готовим приключение…','Сегодняшние подборы закончились. Попроси взрослого помочь или возвращайся завтра.','Не удалось проверить подборы. Попробуй снова.','Использован 1 подбор','История','Поделиться приключением','Копировать ссылку','Ссылка скопирована!','Посмотреть позже','Уже смотрел','Очень понравилось','Не для меня','Сохранено в истории.','Не удалось сохранить. Попробуй снова.','Ещё с такими пожеланиями','Выбрать новое приключение','Взрослым: аккаунт и подборы'],
 ar:['مغامرتك القادمة','فتح عنوان يستخدم مطابقة واحدة من الحساب أو حصة الزائر. المشاهدة والمشاركة والحفظ لهذا الاختيار لا تستخدم مطابقة إضافية.','نجهز مغامرتك…','انتهت مطابقات اليوم. اطلب مساعدة شخص بالغ أو عد غدًا.','تعذر التحقق من المطابقات. حاول مجددًا.','تم استخدام مطابقة واحدة','القصة','شارك المغامرة','نسخ الرابط','تم نسخ الرابط!','المشاهدة لاحقًا','شاهدته','أحببته','لا يناسبني','تم الحفظ في سجلك.','تعذر الحفظ. حاول مجددًا.','اختيار آخر بنفس التفضيلات','اختر مغامرة جديدة','للبالغين: الحساب والمطابقات'],
 hi:['तुम्हारा अगला रोमांच','शीर्षक खोलने पर खाते या अतिथि सीमा से एक मैच लगता है। इस परिणाम को देखने, साझा करने और सहेजने पर अतिरिक्त मैच नहीं लगता।','रोमांच तैयार हो रहा है…','आज के मैच पूरे हो गए। किसी बड़े से मदद माँगो या कल आओ।','मैच जाँच नहीं सके। दोबारा कोशिश करो।','1 मैच इस्तेमाल हुआ','कहानी','यह रोमांच साझा करो','लिंक कॉपी करो','लिंक कॉपी हो गया!','बाद में देखूँगा','देख लिया','बहुत पसंद आया','मेरे लिए नहीं','इतिहास में सहेजा गया।','सहेज नहीं सके। दोबारा कोशिश करो।','इन्हीं पसंदों से एक और','नया रोमांच चुनो','बड़ों के लिए: खाता और मैच'],
 id:['Petualangan berikutnya','Membuka judul memakai satu match dari akun atau kuota tamu. Menonton, berbagi dan menyimpan hasil ini tidak memakai match tambahan.','Menyiapkan petualanganmu…','Match hari ini sudah habis. Minta bantuan orang dewasa atau kembali besok.','Tidak bisa memeriksa match. Coba lagi.','1 match terpakai','Ceritanya','Bagikan petualangan ini','Salin tautan','Tautan disalin!','Tonton nanti','Sudah ditonton','Suka sekali','Bukan untukku','Disimpan ke riwayatmu.','Gagal menyimpan. Coba lagi.','Lagi dengan pilihan ini','Pilih petualangan baru','Dewasa: akun dan match'],
 ja:['次の冒険を見つけよう','作品を開くとアカウントまたはゲスト枠から1マッチ使います。この結果の視聴・共有・保存では追加使用しません。','冒険を準備中…','今日のマッチは使い切りました。大人に相談するか、明日また来てね。','マッチを確認できませんでした。もう一度試してね。','1マッチ使用','どんなお話？','冒険を共有','リンクをコピー','コピーしました！','あとで見る','見たことがある','大好き','好みではない','履歴に保存しました。','保存できませんでした。もう一度試してね。','同じ条件でもうひとつ','新しい冒険を選ぶ','大人向け：アカウントとマッチ'],
 ko:['다음 모험을 찾아요','작품을 열면 계정 또는 방문자 한도에서 매치 1회를 사용해요. 이 결과의 시청, 공유와 저장에는 추가 차감이 없어요.','모험을 준비하고 있어요…','오늘 매치를 모두 사용했어요. 어른에게 도움을 요청하거나 내일 다시 와요.','매치를 확인할 수 없어요. 다시 시도해요.','매치 1회 사용','어떤 이야기일까요?','모험 공유하기','링크 복사','링크를 복사했어요!','나중에 보기','이미 봤어요','정말 좋아요','취향이 아니에요','기록에 저장했어요.','저장할 수 없어요. 다시 시도해요.','같은 조건으로 하나 더','새 모험 고르기','어른용: 계정과 매치'],
 zh:['你的下一场冒险','打开作品使用账户或访客额度中的一次匹配。观看、分享和保存本次结果不额外消耗匹配。','正在准备冒险…','今天的匹配用完啦。请向大人求助，或明天再来。','无法检查匹配额度，请重试。','已使用1次匹配','故事简介','分享这场冒险','复制链接','链接已复制！','稍后观看','看过了','很喜欢','不适合我','已保存到历史记录。','无法保存，请重试。','用相同条件再找一个','选择新的冒险','大人专区：账户和匹配']
 };
 for(const [lang,values] of Object.entries(rows))window.KidsMatchCopy[lang]=Object.fromEntries(keys.map((key,i)=>[key,values[i]]));
})();
