const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const script=fs.readFileSync('ai-composer.js','utf8');
function setup(){const dom=new JSDOM('<html lang="en"><body class="ai-chat-page"><aside id="matchapp-growth-disclosure"><span class="matchapp-growth-copy"><strong>Always growing.</strong> MatchApp is constantly expanding with new titles, features and experiences. <span>Stay tuned for what’s next.</span></span></aside><h2 id="search-box"></h2><textarea id="specific-search-input"></textarea><div class="composer-input-label"></div><div class="chat-user">New chat</div><div class="chat-answer-text">Original answer</div><div class="ai-sidebar-section-title"></div><button id="match-cta">Find my match</button><a id="ai-link" aria-label="Find my match"><span>Talk to our Ai</span></a><section class="discover-card"><h3>Original title identity</h3></section><div class="ma-cookie"><p>We use essential cookies to run MatchApp. Analytics and Google AdSense may use cookies to measure visits and fund the free service. <a href="/cookies.html">Details</a>.</p><button>Accept</button><button>Essential only</button></div></body></html>',{url:'https://matchapp.tv/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.I18N={en:{'q.submit':'Find my match'},'pt-BR':{'q.submit':'Encontrar minha combinação'},es:{'q.submit':'Encontrar mi opción'},fr:{'q.submit':'Trouver mon choix'},de:{'q.submit':'Meine Auswahl finden'},it:{'q.submit':'Trova la mia scelta'},tr:{'q.submit':'Eşleşmemi bul'},ru:{'q.submit':'Найти вариант'},ar:{'q.submit':'اعثر على اختياري'},hi:{'q.submit':'मेरी पसंद खोजें'},id:{'q.submit':'Temukan pilihanku'},ja:{'q.submit':'おすすめを探す'},ko:{'q.submit':'추천 찾기'},zh:{'q.submit':'查找推荐'}};w.t=key=>w.I18N[w.MATCH_LANG||'en']?.[key]||key;w.eval(script);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));return dom;}
test('AI composer validates emptiness and forwards the exact user request once without matching',()=>{const dom=setup(),w=dom.window;let asks=[],matches=0;w.askAI=q=>asks.push(q);w.triggerMatch=()=>matches++;assert.equal(w.submitHomeAI(),false);w.document.querySelector('textarea').value='Dune';assert.equal(w.submitHomeAI(),true);assert.deepEqual(asks,['Dune']);assert.equal(matches,0);assert.equal(w.document.activeElement,w.document.body);w.close();});
test('all supported languages localize composer, growth notice and consent labels while preserving user text',()=>{const dom=setup(),w=dom.window;for(const lang of ['en','pt-BR','es','fr','de','it','tr','ru','ar','hi','id','ja','ko','zh']){w.MATCH_LANG=lang;w.document.dispatchEvent(new w.Event('matchapp:langchange'));const label=w.document.querySelector('.composer-input-label').textContent;assert.ok(label);if(lang!=='en')assert.notEqual(label,'Type your question here');assert.equal(w.document.querySelector('.chat-user').textContent,'New chat');if(lang==='pt-BR'){assert.equal(w.document.querySelector('.matchapp-growth-copy strong').textContent,'Sempre crescendo.');assert.match(w.document.querySelector('.matchapp-growth-copy').textContent,/A MatchApp está sempre se expandindo/);assert.equal(w.document.querySelector('#matchapp-growth-disclosure').getAttribute('aria-label'),'A MatchApp está sempre se expandindo');assert.match(w.document.querySelector('.ma-cookie p').firstChild.nodeValue,/Usamos cookies essenciais/);assert.equal(w.document.querySelector('.ma-cookie button').textContent,'Aceitar');}}w.close();});
test('unannotated adult actions follow the selected language without rewriting title identity',()=>{const dom=setup(),w=dom.window;for(const lang of ['en','pt-BR','es','fr','de','it','tr','ru','ar','hi','id','ja','ko','zh']){w.MATCH_LANG=lang;w.document.dispatchEvent(new w.Event('matchapp:langchange'));assert.equal(w.document.querySelector('#match-cta').textContent,w.t('q.submit'));assert.equal(w.document.querySelector('#ai-link').getAttribute('aria-label'),w.t('q.submit'));}assert.equal(w.document.querySelector('.discover-card h3').textContent,'Original title identity');w.close();});
test('late response translations cannot overwrite a newer language selection',async()=>{const dom=setup(),w=dom.window;let resolve;w.localizeMatchSynopsis=()=>new Promise(r=>resolve=r);w.MATCH_LANG='pt-BR';w.document.dispatchEvent(new w.Event('matchapp:langchange'));w.MATCH_LANG='en';w.document.dispatchEvent(new w.Event('matchapp:langchange'));resolve('Resposta antiga');await new Promise(r=>setTimeout(r,10));assert.equal(w.document.querySelector('.chat-answer-text').textContent,'Original answer');w.close();});
test('dictation waits for Send on both adult surfaces',()=>{for(const file of ['index.html','discover.html']){const html=fs.readFileSync(file,'utf8');assert.doesNotMatch(html,/initVoiceInput\([^;]+=>/);assert.match(html,/ai-composer.css\?v=/);}assert.match(fs.readFileSync('voice-input.js','utf8'),/interimResults=true/);});
test('header labels switch languages reversibly while preserving guide, menu and Kids actions',()=>{
 const dom=setup(),w=dom.window;w.document.body.className='page-home';
 const h=w.document.createElement('header');h.id='mh-topbox';h.className='ma-home-header';
 h.innerHTML='<button class="ma-how-button">How it works</button><a class="ma-kids-mode-entry" href="/kids/"><img src="/kids/logo.png"><span>Kids Mode</span></a><button class="ma-menu-button"><svg></svg><span>Settings</span></button><div class="ma-menu"><a role="menuitem" href="/profile/profile.html#country">🌍 Country</a></div>';
 w.document.body.append(h);let clicks=0;const guide=h.querySelector('button');guide.addEventListener('click',()=>clicks++);
 for(const lang of ['en','pt-BR','es','fr','de','it','tr','ru','ar','hi','id','ja','ko','zh','en']){
  w.MATCH_LANG=lang;w.document.dispatchEvent(new w.Event('matchapp:langchange'));
  assert.ok(guide.textContent);if(lang!=='en')assert.notEqual(guide.textContent,'How it works');
  assert.equal(h.querySelector('a').getAttribute('href'),'/kids/');assert.ok(h.querySelector('img'));assert.ok(h.querySelector('svg'));guide.click();
 }
 assert.equal(clicks,15);assert.equal(guide.textContent,'How it works');assert.equal(h.querySelector('.ma-menu a').textContent,'🌍 Country');w.close();
});
