const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {JSDOM}=require('jsdom');const root=path.join(__dirname,'..');const tick=()=>new Promise(r=>setTimeout(r,10));
async function authDom(auth,signed=true){const dom=new JSDOM('<button data-passkey-action="signin" data-passkey-text="signIn"></button><button data-passkey-action="add" data-passkey-text="add"></button><p data-passkey-status></p><div id="passkey-list"></div>',{url:'https://matchapp.tv',runScripts:'outside-only'}),w=dom.window;Object.defineProperty(w,'isSecureContext',{value:true});w.PublicKeyCredential=class{};w.navigator.credentials={};w.closeAuthModal=()=>{w.closedAuth=true;};w.supabaseClient={auth:{getSession:async()=>({data:{session:signed?{user:{id:'u'}}:null}}),onAuthStateChange:()=>{},passkey:{list:async()=>({data:[]})},...auth}};w.eval(fs.readFileSync(path.join(root,'passkeys.js'),'utf8'));await tick();return dom;}

test('all auth pages load the verified passkey-capable SDK and the client opts in',()=>{
 const pages=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.git'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(p.endsWith('.html')){const s=fs.readFileSync(p,'utf8');for(const m of s.matchAll(/supabase-js@([^/]+)\/dist\/umd\/supabase\.js/g)){assert.equal(m[1],'2.105.0',path.relative(root,p)+' uses an incompatible SDK');pages.push(p);}}}}walk(root);
 assert(pages.includes(path.join(root,'index.html')));assert(pages.includes(path.join(root,'profile','profile.html')));assert(pages.includes(path.join(root,'friends.html')));
 assert.match(fs.readFileSync(path.join(root,'app.js'),'utf8'),/experimental:\s*\{\s*passkey:\s*true/);
});
test('passkey sign-in succeeds only after Supabase returns a verified session',async()=>{const dom=await authDom({signInWithPasskey:async()=>({data:{user:{id:'u'},session:{access_token:'server-verified'}}})});dom.window.document.querySelector('[data-passkey-action=signin]').click();await tick();assert.equal(dom.window.closedAuth,true);assert.equal(dom.window.document.querySelector('[data-passkey-status]').textContent,'Signed in securely.');dom.window.close();});
test('failed or cancelled passkey authentication never promotes a user to signed in',async()=>{for(const response of [{error:{name:'NotAllowedError'}},{data:{user:{id:'u'},session:null}}]){const dom=await authDom({signInWithPasskey:async()=>response},false);dom.window.document.querySelector('[data-passkey-action=signin]').click();await tick();assert.notEqual(dom.window.closedAuth,true);assert(dom.window.document.querySelector('[data-passkey-status]').textContent.includes('Google or email'));dom.window.close();}});
test('passkey enrollment requires a signed-in confirmed account',async()=>{let enroll=0;const dom=await authDom({signInWithPasskey:async()=>({}),getUser:async()=>({data:{user:{id:'u'}}}),registerPasskey:async()=>{enroll++;return {data:{id:'credential'}};}});dom.window.document.querySelector('[data-passkey-action=add]').click();await tick();assert.equal(enroll,0);assert.match(dom.window.document.querySelector('[data-passkey-status]').textContent,/confirm your email/);dom.window.close();});
test('a verified account can enroll through native Supabase WebAuthn',async()=>{let enroll=0;const dom=await authDom({signInWithPasskey:async()=>({}),getUser:async()=>({data:{user:{id:'u',email_confirmed_at:'2026-01-01'}}}),registerPasskey:async()=>{enroll++;return {data:{id:'credential'}};}});dom.window.document.querySelector('[data-passkey-action=add]').click();await tick();assert.equal(enroll,1);assert.match(dom.window.document.querySelector('[data-passkey-status]').textContent,/Passkey added/);assert.equal(dom.window.localStorage.length,0);dom.window.close();});
test('unsupported devices preserve fallback guidance and cannot attempt fake authentication',async()=>{const dom=await authDom({});assert.equal(dom.window.document.querySelector('[data-passkey-action=signin]').disabled,true);assert.match(dom.window.document.querySelector('[data-passkey-status]').textContent,/not supported/);dom.window.close();});
async function updatesDom(version,remote,installed=true){const dom=new JSDOM('<button class="install-btn" onclick=""></button>',{url:'https://matchapp.tv',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.MATCHAPP_BUILD=version;w.matchMedia=()=>({matches:installed});w.fetch=async()=>({ok:true,json:async()=>remote});w.eval(fs.readFileSync(path.join(root,'app-updates.js'),'utf8'));await tick();return dom;}
const release={version:'2026.09.13.1',functional:true,notes:{en:'New functionality'}};
test('a newer release turns install into update and Later retains the update shortcut',async()=>{const d=await updatesDom('2026.09.12.1',release);const doc=d.window.document;assert.equal(doc.querySelector('.install-btn').textContent,'Update app');assert.equal(d.window.matchAppUpdatePending.version,release.version);doc.querySelector('.app-release-dismiss').click();assert.equal(doc.querySelector('.app-release-notice').hidden,true);assert.equal(doc.querySelector('.install-btn').textContent,'Update app');d.window.close();});
test('installed app gets functional release notes once after applying the update',async()=>{const d=await updatesDom(release.version,release);const doc=d.window.document;assert.match(doc.querySelector('h2').textContent,/What’s new/);doc.querySelector('.app-release-dismiss').click();assert.equal(d.window.localStorage.getItem('match_release_seen'),release.version);await d.window.checkMatchAppRelease();assert.equal(doc.querySelector('.app-release-notice').hidden,true);d.window.close();});
test('stale metadata cannot downgrade the app and offline checks preserve usability',async()=>{const d=await updatesDom('2026.09.14.1',release);assert.equal(d.window.matchAppUpdatePending,undefined);d.window.fetch=async()=>{throw new Error('offline');};await d.window.checkMatchAppRelease();assert.equal(d.window.document.querySelector('.install-btn').disabled,false);d.window.close();});
test('stale deployment metadata cannot remove a previously discovered update',async()=>{const d=await updatesDom('2026.09.12.1',release);d.window.fetch=async()=>({ok:true,json:async()=>({...release,version:'2026.09.12.1'})});await d.window.checkMatchAppRelease();assert.equal(d.window.matchAppUpdatePending.version,release.version);assert.equal(d.window.document.querySelector('.install-btn').textContent,'Update app');d.window.close();});
