const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('shown titles remain permanent and merge into signed-in history',()=>{const s=read('matching-policy.js');assert.match(s,/match_recentTitles/);assert.match(s,/stageRestored\(i,'shown'\)/);});
test('visual title identity wins over incidental music tags',()=>{const s=read('production-hardening.js');assert.match(s,/if\(!audioIntent&&isAudioType\(rawType\)\)return null/);});
test('install progress reports browser install phases and only confirms on appinstalled',()=>{const s=read('install-progress.js');assert.match(s,/real install phases, not fake bytes/i);assert.match(s,/window\.addEventListener\('appinstalled'/);assert.match(s,/was successfully installed on your device/);assert.doesNotMatch(s,/downloaded\s+\d+\s+bytes|Math\.random\(\)/i);});
test('crawlability and AdSense publisher declaration remain correct',()=>{assert.equal(read('ads.txt').trim(),'google.com, pub-9541435081010948, DIRECT, f08c47fec0942fa0');const robots=read('robots.txt');assert.match(robots,/Sitemap: https:\/\/matchapp\.tv\/sitemaps\.xml/);assert.doesNotMatch(robots,/Disallow: \/register\.html|Disallow: \/profile\//);});
test('release and build metadata are required to match in CI',()=>{const w=read('.github/workflows/site-validation.yml');assert.match(w,/Verify release\/build metadata match/);assert.match(w,/MATCHAPP_BUILD/);});
