const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM}=require('jsdom');const root=path.join(__dirname,'..');const js=fs.readFileSync(path.join(root,'kids/kids.js'),'utf8');const library=vm.runInNewContext(js.match(/const LIBRARY = (\[[\s\S]*?\n  \]);/)[1]);
const tick=()=>new Promise(r=>setTimeout(r,10));
function revealAllReviewed(w){const grid=w.document.getElementById('kids-grid');let more,clicks=0;while((more=grid.querySelector('.kids-grid-more button'))){assert(clicks++<20,'reviewed shelf must finish loading in bounded batches');more.click();}return grid;}
async function boot(overrides={}){const html=fs.readFileSync(path.join(root,'kids/index.html'),'utf8').replace(/<script\b[\s\S]*?<\/script>/g,'');const dom=new JSDOM(html,{url:'https://matchapp.tv/kids/',runScripts:'outside-only'}),w=dom.window;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.tmdbLookup=async()=>null;w.KidsAccount={consume:async()=>({allowed:true,userId:null}),consumeAI:async()=>({allowed:true,userId:null}),prepare:async()=>{},remember:async()=>{},claimShareReward:async()=>({granted:true,kids_purchased_matches:1}),known:()=>new Set(),key:t=>String(t).toLowerCase()};Object.assign(w,overrides);w.eval(js);await tick();return dom;}
test('every approved title has a complete deterministic local cover and unique DOM IDs',async()=>{const d=await boot();const doc=d.window.document;assert.equal(doc.querySelectorAll('#kids-grid .kids-card').length,Math.min(24,library.length),'initial mobile-safe batch');revealAllReviewed(d.window);assert.equal(doc.querySelectorAll('#kids-grid .kids-card').length,library.length,'all reviewed titles remain reachable');const ids=[...doc.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length);for(const img of doc.querySelectorAll('#kids-grid img')){const p=path.join(root,img.getAttribute('src'));assert(fs.existsSync(p));const svg=new JSDOM(fs.readFileSync(p,'utf8'),{contentType:'image/svg+xml'}).window.document;assert(svg.querySelector('title').textContent.includes(img.alt));assert.equal(svg.querySelectorAll('text').length>=3,true);}d.window.close();});
test('each age band filters grid and featured picks before rendering',async()=>{const d=await boot(),w=d.window,age=w.document.getElementById('kids-age');for(const band of ['3-5','6-8','9-12']){age.value=band;age.dispatchEvent(new w.Event('change'));for(const el of w.document.querySelectorAll('#kids-grid [data-title]'))assert(library.find(x=>x.title===el.dataset.title).ages.includes(band));const count=library.filter(x=>x.ages.includes(band)).length;assert.equal(w.document.querySelectorAll('#kids-grid .kids-card').length,Math.min(24,count));revealAllReviewed(w);assert.equal(w.document.querySelectorAll('#kids-grid .kids-card').length,count);}d.window.close();});
test('AI cannot introduce unknown titles, and age changes invalidate in-flight results',async()=>{let resolve;const d=await boot({supabaseClient:{functions:{invoke:()=>new Promise(r=>{resolve=r;})}}}),w=d.window,doc=w.document;doc.getElementById('kids-question').value='adventure';doc.getElementById('kids-ask-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();doc.getElementById('kids-age').value='3-5';doc.getElementById('kids-age').dispatchEvent(new w.Event('change'));resolve({data:{candidates:[{content:{parts:[{text:JSON.stringify({results:[{title:'Ratatouille'},{title:'Unknown adult film'}]})}]}}]}});await tick();assert.equal(doc.querySelectorAll('#kids-chat-results .kids-card').length,0);assert.equal(doc.getElementById('kids-send').disabled,false);d.window.close();});
test('AI ranking admits only the local title object and escapes query content',async()=>{const response={data:{candidates:[{content:{parts:[{text:JSON.stringify({results:[{title:'Bluey',desc:'<script>bad</script>'},{title:'Unknown adult film'}]})}]}}]}};const d=await boot({supabaseClient:{functions:{invoke:async()=>response}}}),w=d.window,doc=w.document;doc.getElementById('kids-question').value='<script>unsafe</script>';doc.getElementById('kids-ask-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(doc.querySelectorAll('#kids-chat-results .kids-card').length,1);assert.equal(doc.querySelector('#kids-chat-results h3').textContent,'Bluey');assert.equal(doc.querySelectorAll('#kids-chat-results script').length,0);d.window.close();});
test('poster hydration rejects mismatched identity, adult content and untrusted hosts',async()=>{for(const result of [{title:'Unrelated',kind:'tv',year:'2018',poster:'https://image.tmdb.org/t/p/w500/a.jpg'},{title:'Bluey',kind:'tv',year:'2018',adult:true,poster:'https://image.tmdb.org/t/p/w500/a.jpg'},{title:'Bluey',kind:'tv',year:'2000',poster:'https://image.tmdb.org/t/p/w500/a.jpg'},{title:'Bluey',kind:'tv',year:'2018',poster:'https://evil.example/a.jpg'}]){const d=await boot({tmdbLookup:async()=>result});assert.match(d.window.document.querySelector('#kids-grid img').getAttribute('src'),/^\/kids\/covers\//);d.window.close();}});
test('cover requests are deduplicated and bounded; valid artwork replaces the fallback',async()=>{let active=0,max=0,calls=0;const d=await boot({Image:class {set src(value){setTimeout(()=>this.onload?.(),0);}},tmdbLookup:async(title)=>{calls++;active++;max=Math.max(max,active);await tick();active--;return {title,kind:'tv',year:'2018',poster:'https://image.tmdb.org/t/p/w500/bluey.jpg'};}});const expected=library.filter(x=>x.tmdb!==false).length;for(let i=0;i<80&&calls<expected;i++)await tick();assert(calls < expected);assert(calls <= 50, 'the first minute stays below the proxy limit');assert(max<=4);assert.match(d.window.document.querySelector('#kids-grid img').src,/image.tmdb.org/);d.window.close();});
test('children can pause motion and category buttons retain keyboard focus',async()=>{const d=await boot(),w=d.window,doc=w.document;doc.getElementById('kids-motion').click();assert(doc.body.classList.contains('kids-paused'));assert.equal(doc.getElementById('kids-motion').getAttribute('aria-pressed'),'true');const funny=doc.querySelector('[data-cat=funny]');funny.focus();funny.click();assert.equal(doc.activeElement.dataset.cat,'funny');assert.equal(doc.activeElement.getAttribute('aria-pressed'),'true');d.window.close();});

function ask(w,question='funny animals'){w.document.getElementById('kids-question').value=question;w.document.getElementById('kids-ask-form').dispatchEvent(new w.Event('submit',{cancelable:true}));}
function throttle(seconds,body=true){return {error:{context:new Response(JSON.stringify(body?{retryAfter:seconds}:{error:'Provider quota'}),{status:429,headers:{'Retry-After':String(seconds)}})}};}
const blueyAI={data:{candidates:[{content:{parts:[{text:JSON.stringify({results:[{title:'Bluey'},{title:'Unknown adult film'}]})}]}}]}};
test('Kids Ask AI spends only after a usable reviewed result and never on an empty approved pool',async()=>{
 const order=[];const account={consume:async()=>({allowed:true,userId:null}),consumeAI:async()=>{order.push('consume');return {allowed:true,userId:null}},status:async()=>({remaining:1,kids_credits:0}),prepare:async()=>{},remember:async()=>{},claimShareReward:async()=>({granted:true,kids_purchased_matches:1}),known:()=>new Set(),key:t=>String(t).toLowerCase()};
 const d=await boot({KidsAccount:account,supabaseClient:{functions:{invoke:async()=>{order.push('recognise');return blueyAI}}}}),w=d.window;ask(w,'bluey');await new Promise(r=>setTimeout(r,30));assert.deepEqual(order,['recognise','consume']);assert.equal(w.document.querySelectorAll('#kids-chat-results .kids-card').length,1);d.window.close();
 let spends=0;const knownAll=new Set(library.map(x=>String(x.title).toLowerCase()));const emptyAccount={...account,consumeAI:async()=>{spends++;return {allowed:true,userId:null}},known:()=>knownAll};
 const d2=await boot({KidsAccount:emptyAccount,supabaseClient:{functions:{invoke:async()=>blueyAI}}}),w2=d2.window;ask(w2,'bluey');await new Promise(r=>setTimeout(r,30));assert.equal(spends,0);assert.equal(w2.document.querySelectorAll('#kids-chat-results .kids-card').length,0);d2.window.close();
});
test('Kids short app throttle retries once after Retry-After and retains the reviewed allowlist',async()=>{
 let calls=0;const d=await boot({supabaseClient:{functions:{invoke:async()=>++calls===1?throttle(0):blueyAI}}}),w=d.window;
 ask(w);ask(w);await tick();assert.equal(calls,1,'duplicate submission and immediate retry are blocked');
 await new Promise(r=>setTimeout(r,300));assert.equal(calls,2);assert.equal(w.document.querySelectorAll('#kids-chat-results .kids-card').length,1);assert.equal(w.document.querySelector('#kids-chat-results h3').textContent,'Bluey');assert.equal(w.document.getElementById('kids-send').disabled,false);assert(!w.document.querySelector('#kids-answer strong'));d.window.close();
});
test('Kids long throttles use honest age-safe local picks and suppress calls during cooldown',async()=>{
 let calls=0;const d=await boot({supabaseClient:{functions:{invoke:async()=>{calls++;return throttle(60);}}}}),w=d.window;
 ask(w);await tick();assert.equal(calls,1);assert(w.document.querySelector('#kids-answer strong').textContent.includes('approved Kids library'));assert.equal(w.document.getElementById('kids-send').disabled,false);assert.equal(w.document.getElementById('kids-question').value,'funny animals');
 const age=w.document.getElementById('kids-age');age.value='3-5';age.dispatchEvent(new w.Event('change'));ask(w);await tick();assert.equal(calls,1,'cooldown applies across questions and ages');for(const card of w.document.querySelectorAll('#kids-chat-results .kids-card'))assert(library.find(x=>x.title===card.dataset.title).ages.includes('3-5'));d.window.close();
});
test('Kids retry is bounded and provider throttles never trigger an automatic retry',async()=>{
 for(const appThrottle of [true,false]){let calls=0;const d=await boot({supabaseClient:{functions:{invoke:async()=>{calls++;return throttle(0,appThrottle);}}}}),w=d.window;ask(w);await new Promise(r=>setTimeout(r,600));assert.equal(calls,appThrottle?2:1);assert.equal(w.document.getElementById('kids-send').disabled,false);assert(w.document.querySelector('#kids-answer strong'));d.window.close();}
});
test('Kids age changes cancel a delayed retry before another AI call',async()=>{
 let calls=0;const d=await boot({supabaseClient:{functions:{invoke:async()=>{calls++;return throttle(0);}}}}),w=d.window;ask(w);await tick();const age=w.document.getElementById('kids-age');age.value='3-5';age.dispatchEvent(new w.Event('change'));await new Promise(r=>setTimeout(r,300));assert.equal(calls,1);assert.equal(w.document.querySelectorAll('#kids-chat-results .kids-card').length,0);assert.equal(w.document.getElementById('kids-send').disabled,false);d.window.close();
});
