const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM}=require('jsdom'),root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'kids/kids.js'),'utf8');
const library=vm.runInNewContext(source.match(/const LIBRARY = (\[[\s\S]*?\n  \]);/)[1]);
const links=JSON.parse(fs.readFileSync(path.join(root,'kids/watch-links.json'),'utf8'));
const tick=()=>new Promise(r=>setTimeout(r,10));
async function boot(data=links,saved=[]){const html=fs.readFileSync(path.join(root,'kids/index.html'),'utf8').replace(/<script\b[\s\S]*?<\/script>/g,'');const d=new JSDOM(html,{url:'https://matchapp.tv/kids/',runScripts:'outside-only'}),w=d.window;w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.tmdbLookup=async()=>null;w.fetch=async()=>({ok:true,json:async()=>data});w.localStorage.setItem('match_kids_saved_titles',JSON.stringify(saved));w.KidsAccount={prepare:async()=>{},consume:async()=>({allowed:true,userId:null}),remember:async()=>{}};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.eval(source);await tick();return d;}
function change(w,id,value){const el=w.document.getElementById(id);el.value=value;el.dispatchEvent(new w.Event('change'));}
test('Kids matching intersects the curated age, mood, format and decade filters',async()=>{const d=await boot(),w=d.window;change(w,'kids-age','6-8');change(w,'kids-match-mood','adventure');change(w,'kids-match-format','series');change(w,'kids-match-era','1980');w.document.getElementById('kids-match-submit').click();await tick();const cards=[...w.document.querySelectorAll('#kids-match-results .kids-card')];assert.equal(cards.length,3);for(const card of cards){const item=library.find(x=>x.title===card.dataset.title);assert(item.ages.includes('6-8'));assert(item.cats.includes('adventure'));assert.equal(item.type,'series');assert.equal(Math.floor(Number(item.year)/10),198);}const ids=[...w.document.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length);change(w,'kids-age','3-5');assert.equal(w.document.querySelectorAll('#kids-match-results .kids-card').length,0);d.window.close();});
test('Kids matching never dead-ends for Funny + Show + 2020s',async()=>{const d=await boot(),w=d.window;change(w,'kids-match-mood','funny');change(w,'kids-match-format','series');change(w,'kids-match-era','2020');w.document.getElementById('kids-match-submit').click();await tick();const cards=[...w.document.querySelectorAll('#kids-match-results .kids-card')];assert(cards.length>0);assert.doesNotMatch(w.document.getElementById('kids-match-status').textContent,/No approved titles|Nenhum título aprovado|No hay títulos aprobados/i);for(const card of cards){const item=library.find(x=>x.title===card.dataset.title);assert(item&&item.ages.includes('all'));}d.window.close();});
test('favorites accept only approved titles and older favorites disappear from younger age bands',async()=>{const d=await boot(links,['unknown-adult-film','the-flintstones']),w=d.window;assert.equal(w.document.querySelectorAll('#kids-saved-results .kids-card').length,1);change(w,'kids-age','3-5');assert.equal(w.document.querySelectorAll('#kids-saved-results .kids-card').length,0);w.document.querySelector('#kids-grid [data-save=bluey]').click();assert.equal(w.document.querySelector('#kids-saved-results h3').textContent,'Bluey');const saved=JSON.parse(w.localStorage.getItem('match_kids_saved_titles'));assert(!saved.includes('unknown-adult-film'));assert(saved.includes('bluey'));w.document.querySelector('#kids-grid [data-save=bluey]').click();assert.equal(w.document.querySelectorAll('#kids-saved-results .kids-card').length,0);d.window.close();});
test('viewing links resolve exact regional title pages in the same tab and stay active until navigation',async()=>{const d=await boot(),w=d.window;w.document.querySelector('#kids-grid [data-watch=bluey]').click();await tick();change(w,'kids-watch-region','BR');const link=w.document.getElementById('kids-watch-continue'),dialog=w.document.getElementById('kids-watch-dialog');assert.equal(link.href,links.titles.bluey.regions.BR);assert.equal(link.target,'_self');assert.match(link.href,/\/br\/serie\/bluey$/);link.addEventListener('click',e=>e.preventDefault());link.click();assert.equal(dialog.open,true);change(w,'kids-watch-region','US');assert.equal(link.href,links.titles.bluey.regions.US);assert.match(w.document.getElementById('kids-watch-fallback').href,/google\.com\/search/);d.window.close();});
test('missing, mismatched and untrusted watch data always gets a usable title-specific fallback',async()=>{for(const entry of [undefined,{title:'Bluey',year:'2018',type:'series',regions:{BR:'https://evil.example/bluey',US:'https://evil.example/bluey'}},{title:'Unknown',year:'2018',type:'series',regions:{US:'https://www.justwatch.com/us/tv-show/unknown'}}]){const d=await boot({titles:{bluey:entry}}),w=d.window;w.document.querySelector('#kids-grid [data-watch=bluey]').click();await tick();const link=w.document.getElementById('kids-watch-continue');assert.match(link.href,/^https:\/\/www\.google\.com\/search\?q=/);assert(decodeURIComponent(link.href).includes('Bluey'));d.window.close();}});
test('the expanded collection spans eight decades and local watch metadata matches its identities',()=>{assert.equal(library.length,64);assert.equal(new Set(library.map(x=>x.title)).size,64);for(const decade of [1950,1960,1970,1980,1990,2000,2010,2020])assert(library.some(x=>Math.floor(Number(x.year)/10)*10===decade));for(const entry of Object.values(links.titles)){const item=library.find(x=>x.title===entry.title);assert(item);assert.equal(entry.year,item.year);assert.equal(entry.type,item.type);for(const [region,url] of Object.entries(entry.regions))assert(new RegExp('^https://www\\.justwatch\\.com/'+region.toLowerCase()+'/').test(url));}});
