const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM}=require('jsdom');const root=path.join(__dirname,'..');const js=fs.readFileSync(path.join(root,'kids/kids.js'),'utf8');const library=vm.runInNewContext(js.match(/const LIBRARY = (\[[\s\S]*?\n  \]);/)[1]);
const tick=()=>new Promise(r=>setTimeout(r,10));
async function boot(overrides={}){const html=fs.readFileSync(path.join(root,'kids/index.html'),'utf8').replace(/<script\b[\s\S]*?<\/script>/g,'');const dom=new JSDOM(html,{url:'https://matchapp.tv/kids/',runScripts:'outside-only'}),w=dom.window;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.tmdbLookup=async()=>null;Object.assign(w,overrides);w.eval(js);await tick();return dom;}
test('every approved title has a complete deterministic local cover and unique DOM IDs',async()=>{const d=await boot();const doc=d.window.document;assert.equal(doc.querySelectorAll('#kids-grid .kids-card').length,library.length);const ids=[...doc.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length);for(const img of doc.querySelectorAll('#kids-grid img')){const p=path.join(root,img.getAttribute('src'));assert(fs.existsSync(p));const svg=new JSDOM(fs.readFileSync(p,'utf8'),{contentType:'image/svg+xml'}).window.document;assert(svg.querySelector('title').textContent.includes(img.alt));assert.equal(svg.querySelectorAll('text').length>=3,true);}d.window.close();});
test('each age band filters grid and featured picks before rendering',async()=>{const d=await boot(),w=d.window,age=w.document.getElementById('kids-age');for(const band of ['3-5','6-8','9-12']){age.value=band;age.dispatchEvent(new w.Event('change'));for(const el of w.document.querySelectorAll('#kids-grid [data-title]'))assert(library.find(x=>x.title===el.dataset.title).ages.includes(band));const count=library.filter(x=>x.ages.includes(band)).length;assert.equal(w.document.querySelectorAll('#kids-grid .kids-card').length,count);}d.window.close();});
test('AI cannot introduce unknown titles, and age changes invalidate in-flight results',async()=>{let resolve;const d=await boot({supabaseClient:{functions:{invoke:()=>new Promise(r=>{resolve=r;})}}}),w=d.window,doc=w.document;doc.getElementById('kids-question').value='adventure';doc.getElementById('kids-ask-form').dispatchEvent(new w.Event('submit',{cancelable:true}));doc.getElementById('kids-age').value='3-5';doc.getElementById('kids-age').dispatchEvent(new w.Event('change'));resolve({data:{candidates:[{content:{parts:[{text:JSON.stringify({results:[{title:'Ratatouille'},{title:'Unknown adult film'}]})}]}}]}});await tick();assert.equal(doc.querySelectorAll('#kids-chat-results .kids-card').length,0);assert.equal(doc.getElementById('kids-send').disabled,false);d.window.close();});
test('AI ranking admits only the local title object and escapes query content',async()=>{const response={data:{candidates:[{content:{parts:[{text:JSON.stringify({results:[{title:'Bluey',desc:'<script>bad</script>'},{title:'Unknown adult film'}]})}]}}]}};const d=await boot({supabaseClient:{functions:{invoke:async()=>response}}}),w=d.window,doc=w.document;doc.getElementById('kids-question').value='<script>unsafe</script>';doc.getElementById('kids-ask-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(doc.querySelectorAll('#kids-chat-results .kids-card').length,1);assert.equal(doc.querySelector('#kids-chat-results h3').textContent,'Bluey');assert.equal(doc.querySelectorAll('#kids-chat-results script').length,0);d.window.close();});
test('poster hydration rejects mismatched identity, adult content and untrusted hosts',async()=>{for(const result of [{title:'Unrelated',kind:'tv',year:'2018',poster:'https://image.tmdb.org/t/p/w500/a.jpg'},{title:'Bluey',kind:'tv',year:'2018',adult:true,poster:'https://image.tmdb.org/t/p/w500/a.jpg'},{title:'Bluey',kind:'tv',year:'2000',poster:'https://image.tmdb.org/t/p/w500/a.jpg'},{title:'Bluey',kind:'tv',year:'2018',poster:'https://evil.example/a.jpg'}]){const d=await boot({tmdbLookup:async()=>result});assert.match(d.window.document.querySelector('#kids-grid img').getAttribute('src'),/^\/kids\/covers\//);d.window.close();}});
test('cover requests are deduplicated and bounded; valid artwork replaces the fallback',async()=>{let active=0,max=0,calls=0;const d=await boot({Image:class {set src(value){setTimeout(()=>this.onload?.(),0);}},tmdbLookup:async(title)=>{calls++;active++;max=Math.max(max,active);await tick();active--;return {title,kind:'tv',year:'2018',poster:'https://image.tmdb.org/t/p/w500/bluey.jpg'};}});await new Promise(r=>setTimeout(r,150));assert.equal(calls,library.length);assert(max<=4);assert.match(d.window.document.querySelector('#kids-grid img').src,/image.tmdb.org/);d.window.close();});
test('children can pause motion and category buttons retain keyboard focus',async()=>{const d=await boot(),w=d.window,doc=w.document;doc.getElementById('kids-motion').click();assert(doc.body.classList.contains('kids-paused'));assert.equal(doc.getElementById('kids-motion').getAttribute('aria-pressed'),'true');const funny=doc.querySelector('[data-cat=funny]');funny.focus();funny.click();assert.equal(doc.activeElement.dataset.cat,'funny');assert.equal(doc.activeElement.getAttribute('aria-pressed'),'true');d.window.close();});
