const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),app=fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/\r\n/g,'\n'),policy=fs.readFileSync(path.join(root,'matching-policy.js'),'utf8');
const catalog=vm.runInNewContext(app.match(/const CONTENT_CATALOG = (\[[\s\S]*?\n\]);/)[1]);
function boot(rpc){const d=new JSDOM('<body></body>',{url:'https://matchapp.tv/',runScripts:'outside-only'});d.window.supabaseClient={rpc:rpc|| (async()=>({data:{keys:[],history:[]}}))};d.window.eval(policy);return d;}
test('saved, seen, loved and declined titles remain excluded after list removal and reload',async()=>{const d=boot(),w=d.window;await w.matchPolicy.attach({id:'alice'});for(const action of ['save','seen','like','dislike'])w.matchPolicy.remember({title:'Some Title '+action},action);await w.matchPolicy.flush();assert(w.matchPolicy.known().has('sometitlesave'));w.localStorage.removeItem('match_savedList');w.eval(policy);await w.matchPolicy.attach({id:'alice'});assert(w.matchPolicy.known().has('sometitlesave'));assert.equal(w.matchPolicy.history().length,4);assert(w.matchPolicy.known().has(w.matchPolicy.key('SOME — TITLE save')));d.window.close();});
test('cloud restoration and account switching cannot mix permanent histories',async()=>{let alice=true;const d=boot(async(name,p)=>({data:p.p_action==='list'?{keys:alice?['aliceonly']:[],history:[]}: {}})),w=d.window;await w.matchPolicy.attach({id:'alice'});assert(w.matchPolicy.known().has('aliceonly'));alice=false;await w.matchPolicy.attach({id:'bob'});assert(!w.matchPolicy.known().has('aliceonly'));await w.matchPolicy.attach(null);assert(!w.matchPolicy.known().has('aliceonly'));d.window.close();});
test('strict catalog selection intersects all fields and returns null after exhaustion',async()=>{const d=boot(),w=d.window;const c=vm.createContext({window:w,CONTENT_CATALOG:catalog,SESSION_SHOWN:new Set(),normCriteria:w.matchPolicy.values,isBlockedEntry:()=>false,isSurpriseEligible:e=>!e.cats.includes('Gospel & Faith'),Math});vm.runInContext(app.match(/function pickFromCatalog\([\s\S]*?\n}\n\nwindow.triggerMatch/)[0].replace(/\nwindow.triggerMatch$/,''),c);for(let n=0;n<60;n++){const pick=c.pickFromCatalog('movie','any','funny','any','any',['2020s']);if(!pick)break;const entry=catalog.find(e=>e.title===pick.title);assert(entry.cats.includes('movie'));assert(entry.moods.includes('funny'));assert(entry.year>=2020&&entry.year<2030);c.SESSION_SHOWN.add(pick.title);}assert.equal(c.pickFromCatalog('movie','Impossible service','funny','any','any'),null);catalog.forEach(e=>w.matchPolicy.remember({title:e.title},'seen',false));assert.equal(c.pickFromCatalog('any','any','any','any','any'),null);d.window.close();});
test('incompatible mood chips are disabled and programmatic choices cannot relax matching',()=>{const d=boot(),w=d.window;w.document.body.innerHTML='<div>'+new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8')).window.document.querySelector('#q-mood').outerHTML+'</div>';w.eval(fs.readFileSync(path.join(root,'criteria.js'),'utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));w.document.querySelector('[data-value="funny"]').click();const intense=w.document.querySelector('[data-value="intense and thrilling"]');assert(intense.disabled);assert(w.document.querySelector('[data-value="scary"]').disabled);intense.click();assert.deepEqual(Array.from(w.getMatchCriteria().mood),['funny']);w.document.querySelector('[data-value="funny"]').click();assert(!w.document.querySelector('[data-value="intense and thrilling"]').disabled);w.setMatchCriteria({mood:['funny','scary']});assert.deepEqual(Array.from(w.getMatchCriteria().mood),['funny']);d.window.close();});
test('empty strict searches are checked before a credit is consumed and rejection opens history',()=>{const trigger=app.slice(app.indexOf('window.triggerMatch ='),app.indexOf('// THE RENDER ENGINE'));assert(trigger.indexOf('!preflight')<trigger.indexOf('await checkDailyLimit()'));assert.match(app,/profile\/profile\.html\?tab=history&rematch=1/);assert(!app.includes('${deadTitle}</strong>'));});

test('owner Auth preferences restore permanent exclusions when the private RPC is not activated',async()=>{const d=boot(async()=>({error:{code:'PGRST202'}})),w=d.window;await w.matchPolicy.attach({id:'alice',user_metadata:{match_exclusion_keys:['removedclassic'],match_history:[{title:'Removed Classic',action:'removed',addedAt:10}]}});assert(w.matchPolicy.known().has('removedclassic'));assert.equal(w.matchPolicy.history()[0].title,'Removed Classic');await w.matchPolicy.attach({id:'bob',user_metadata:{}});assert(!w.matchPolicy.known().has('removedclassic'));d.window.close();});
test('logout clears active account and entitlement data while keeping installation and lifetime exclusions',async()=>{const storage=new Map([['match_savedList','private'],['match_app_installed','true'],['match_app_installed_build','2026.09.13.3'],['match_exclusions_alice','["classic"]'],['match_history_alice','private'],['match_kids_age_band','3-5'],['match_ad_free','true']]);const local={getItem:k=>storage.get(k),removeItem:k=>storage.delete(k)};for(const k of storage.keys())Object.defineProperty(local,k,{enumerable:true});let signedOut=0,synced=0;const w={location:{}};const context=vm.createContext({window:w,localStorage:local,isUserLoggedIn:true,profileHydrationEpoch:0,syncListsToDatabase:async()=>{synced++;},supabaseClient:{auth:{signOut:async()=>{signedOut++;}}},setTimeout:()=>{}});vm.runInContext(app.match(/window.doLogout = async function\(\) \{[\s\S]*?\n\};/)[0],context);await w.doLogout();assert.equal(signedOut,1);assert.equal(synced,1);assert(!storage.has('match_savedList'));assert(!storage.has('match_ad_free'));assert.equal(storage.get('match_app_installed'),'true');assert(storage.has('match_exclusions_alice'));assert.equal(storage.get('match_kids_age_band'),'3-5');assert.equal(w.location.href,'/');});
