const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'kids/kids.js'),'utf8'),library=vm.runInNewContext(source.match(/const LIBRARY = (\[[\s\S]*?\n  \]);/)[1]),art=JSON.parse(fs.readFileSync(path.join(root,'kids/artwork.json'),'utf8'));
const tick=()=>new Promise(r=>setTimeout(r,10));
async function boot(country,options={}){const html=fs.readFileSync(path.join(root,'kids/index.html'),'utf8').replace(/<script\b[\s\S]*?<\/script>/g,'');const d=new JSDOM(html,{url:'https://matchapp.tv/kids/',runScripts:'outside-only'}),w=d.window;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.localStorage.setItem('match_user_country',country);w.fetch=async u=>({ok:true,json:async()=>u.includes('artwork')?art:JSON.parse(fs.readFileSync(path.join(root,'kids/watch-links.json'),'utf8'))});w.tmdbLookup=options.tmdbLookup||(async()=>null);w.KidsAccount={prepare:async()=>{},consume:async()=>({allowed:true,userId:null}),remember:async()=>{}};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.eval(source);await tick();return d;}
test('all reviewed film/TV entries have a respective provider cover, with original local art always present',()=>{for(const i of library){const id=i.title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,'-');assert(fs.existsSync(path.join(root,'kids/covers',id+'.svg')));if(i.tmdb!==false){assert(art.titles[id],i.title+' provider art');assert.equal(art.titles[id].title,i.title);assert.equal(String(art.titles[id].year),i.year);assert.equal(art.titles[id].type,i.type);assert.match(art.titles[id].poster,/^https:\/\/(image\.tmdb\.org|static\.tvmaze\.com|is[1-5]-ssl\.mzstatic\.com)\//);}}});
test('reviewed Kids first paint uses exact cached artwork without a live TMDB burst',async()=>{let calls=0;const d=await boot('Brazil',{tmdbLookup:async()=>{calls++;return null;}});await tick();assert.equal(calls,0,'exact cached Kids covers must not spend live TMDB quota on first paint');const visible=[...d.window.document.querySelectorAll('#kids-grid img')];assert(visible.length>0);for(const img of visible)assert.match(img.src,/image\.tmdb\.org|static\.tvmaze\.com|is[1-5]-ssl\.mzstatic\.com|kids\/covers\//);d.window.close();});
test('Kids category controls and paginated more control remain pill shaped',()=>{const css=fs.readFileSync(path.join(root,'kids/kids.css'),'utf8');assert.match(css,/\.kids-chip\{[^}]*border-radius:999px/);assert.match(css,/\.kids-grid-more>\.kids-chip\{[^}]*border-radius:999px/);});
test('residence chooses an official Woody dub and the title match retains the official viewing channel',async()=>{for(const [country,dub]of [['Brazil','pt'],['Mexico','es'],['United States','en']]){const d=await boot(country),w=d.window;assert.equal(w.document.getElementById('kids-watch-dub').value,dub);const card=[...w.document.querySelectorAll('#kids-nostalgia .kids-card')].find(c=>c.dataset.title==='The Woody Woodpecker Show');const link=card.querySelector('h3 a');assert.equal(link.hash,'#kids-watch-dialog');link.click();await tick();assert.match(w.document.getElementById('kids-watch-continue').href,/^https:\/\/www.youtube.com\/channel\//);assert(!link.hasAttribute('data-watch'));w.document.getElementById('kids-age').value='3-5';w.document.getElementById('kids-age').dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('#kids-nostalgia .kids-card').length,0);d.window.close();}});
test('public title guides protect younger age bands and hydrate official covers with a failure fallback',async()=>{const html=fs.readFileSync(path.join(root,'kids/titles/the-woody-woodpecker-show/index.html'),'utf8');const d=new JSDOM(html,{url:'https://matchapp.tv/kids/titles/the-woody-woodpecker-show/',runScripts:'outside-only'}),w=d.window;w.localStorage.setItem('match_kids_age_band','3-5');w.fetch=async()=>({ok:true,json:async()=>art});w.eval(fs.readFileSync(path.join(root,'kids/title-artwork.js'),'utf8'));assert(w.document.querySelector('[data-kids-title]').hidden);await tick();const img=w.document.querySelector('[data-kids-title] img');assert.match(img.src,/image.tmdb.org|static.tvmaze.com/);img.dispatchEvent(new w.Event('error'));assert.match(img.src,/kids\/covers\//);d.window.close();});
