const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
test('profile always receives current canonical avatar and compact Taste DNA styles and script',()=>{
 const profile=fs.readFileSync('profile/profile.html','utf8');
 const shell=fs.readFileSync('title-captions.js','utf8');
 const settings=fs.readFileSync('settings.js','utf8');
 assert(profile.includes('/settings.js?v=20261006-installbell1'));
 assert(profile.includes('/title-captions.js?v=20260929-avatar1'));
 assert(shell.includes('/final-audit.js?v=20260929-avatar1'));
 assert(shell.includes('/final-audit.css?v=20260929-avatar1'));
 assert(settings.includes("src==='/taste-profile.js'?'20260929-taste1'"));
 assert(settings.includes("src==='/taste-profile.css'?'20260929-taste1'"));
 const hero=fs.readFileSync('final-audit.js','utf8');
 assert(hero.includes('avatar=window.resolveUserAvatar?.()'));
 assert(fs.readFileSync('taste-profile.js','utf8').includes("toast.id='taste-saved-toast'"));
 const release=JSON.parse(fs.readFileSync('release.json','utf8'));
 assert.match(release.version,/^\d{4}\.\d{2}\.\d{2}\.\d+$/);
 assert.equal(release.date,release.version.split('.').slice(0,3).join('-'));
 assert.equal(Object.keys(release.notes).length,14);
 assert(fs.readFileSync('build-meta.js','utf8').includes("window.MATCHAPP_BUILD = '"+release.version+"'"));
});