const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const {JSDOM}=require('jsdom'),root=path.join(__dirname,'..'),tick=()=>new Promise(r=>setTimeout(r,15));
const source=f=>fs.readFileSync(path.join(root,f),'utf8'),run=(w,f)=>w.eval(source(f));
test('Roku titles participate in the actual match catalog while Gospel identifiers remain strings',()=>{const s=source('app.js'),start=s.indexOf('const CONTENT_CATALOG = '),end=s.indexOf('\n];',start)+3,catalog=vm.runInNewContext(s.slice(start,end)+';CONTENT_CATALOG');assert.equal(catalog.filter(e=>e.platform==='Roku Channel').length,8);const a=s.indexOf('const GOSPEL_TITLES = '),b=s.indexOf('];',a)+2;assert(vm.runInNewContext(s.slice(a,b)+';GOSPEL_TITLES').every(e=>typeof e==='string'));});
const locales=w=>w.eval(['i18n.js','polish-i18n.js','event-i18n.js','page-locale.js'].map(source).join('\n'));
function page(url='https://matchapp.tv/'){return new JSDOM('<html><body><button data-theme-choice="cinema"><strong></strong><small></small></button><p id="theme-preview-status"></p></body></html>',{url,runScripts:'outside-only',pretendToBeVisual:true});}
test('theme preview leaves stored preferences unchanged, cancellation restores them, and saving commits only a valid theme',async()=>{const d=page(),w=d.window;w.localStorage.setItem('match_settings',JSON.stringify({theme:'ocean'}));w.MatchSettings={get:()=>JSON.parse(w.localStorage.getItem('match_settings')).theme,set:(k,v)=>{w.localStorage.setItem('match_settings',JSON.stringify({theme:v}));w.document.dispatchEvent(new w.Event('matchapp:settingschanged'));}};run(w,'themes.js');await tick();assert.equal(w.document.documentElement.dataset.theme,'ocean');w.document.querySelector('button').click();assert.equal(w.document.documentElement.dataset.theme,'cinema');assert.equal(w.MatchSettings.get(),'ocean');w.MatchThemes.cancel();assert.equal(w.document.documentElement.dataset.theme,'ocean');w.MatchThemes.preview('arcade');w.MatchThemes.save();assert.equal(w.MatchSettings.get(),'arcade');w.MatchThemes.preview('unknown');assert.equal(w.document.documentElement.dataset.theme,'arcade');w.close();});
test('saved language beats a link language, persists through a page boot, and explicitly changing it updates storage and page direction',async()=>{const d=page('https://matchapp.tv/?lang=en'),w=d.window;w.localStorage.setItem('match_lang','pt-BR');locales(w);await tick();assert.equal(w.MATCH_LANG,'pt-BR');assert.equal(w.document.documentElement.lang,'pt-BR');assert.match(w.t('polish.platforms'),/plataformas/);w.setLanguage('ar');assert.equal(w.localStorage.getItem('match_lang'),'ar');assert.equal(w.document.documentElement.dir,'rtl');w.close();});
test('a failed synopsis translation retains the selected language rather than returning an English description',async()=>{const d=page(),w=d.window;w.localStorage.setItem('match_lang','pt-BR');run(w,'i18n.js');run(w,'polish-i18n.js');w.supabaseClient={functions:{invoke:async()=>({error:{message:'offline'}})}};run(w,'match-localization.js');await tick();const text=await w.localizeMatchSynopsis('An English-only synopsis.');assert.notEqual(text,'An English-only synopsis.');assert.match(text,/assistir|Guia/);assert.equal(w.MATCH_LANG,'pt-BR');w.close();});
test('all replacement events have ordered future dates, local original artwork, official sources and live/recorded viewing routes',()=>{const events=JSON.parse(source('tools/global-events.json'));assert.equal(events.length,3);for(const e of events){assert(Date.parse(e.start)>Date.parse('2026-09-14T00:00:00Z'));assert(Date.parse(e.end)>Date.parse(e.start));assert(fs.existsSync(path.join(root,e.slug+'.jpg')));assert.match(e.watch,/^https:\/\//);assert.match(e.recorded,/^https:\/\//);assert.match(e.source,/^https:\/\//);}assert(!/rock.in.rio|oktoberfest/i.test(source('index.html')+source('events-archive.html')));});
test('the premiere starts open and native folding preserves the poster and countdown',()=>{const d=new JSDOM(source('index.html')),details=d.window.document.getElementById('premiere-disclosure');assert(details.open);assert(details.querySelector('#spotlight-ahs13'));assert.equal(details.querySelectorAll('details').length,0);details.open=true;assert(details.open);assert(details.querySelector('.spotlight-countdown'));d.window.close();});
test('Roku is backed by reviewed titles and actual typed poster identities; no adult title enters the independent Kids allowlist',()=>{const entries=JSON.parse(source('tools/roku-titles.json')),identities=JSON.parse(source('data/poster-identities.json'));assert.equal(entries.length,8);const n=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');for(const e of entries){assert.equal(e.platform,'Roku Channel');assert.match(e.source,/^https:\/\//);assert(identities.find(r=>n(r.title)===n(e.title)&&String(r.year)===String(e.year)));}const kids=source('kids/kids.js').match(/const LIBRARY = (\[[\s\S]*?\n  \]);/)[1];assert(!kids.includes('Die Hart'));assert(!kids.includes('Honest Renovations'));});
