const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),{stripTypeScriptTypes}=require('node:module');
const root=path.join(__dirname,'..'),user='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
function billing(){const ctx={Date,console};vm.createContext(ctx);vm.runInContext(stripTypeScriptTypes(fs.readFileSync(path.join(root,'supabase/functions/_shared/billing.ts'),'utf8')).replace(/\bexport /g,'')+'\nthis.exports={PRODUCTS,catalog,verifiedCheckout,deliver};',ctx);return ctx.exports;}
function stripe(b){const products=Object.entries(b.PRODUCTS);return {paymentLinks:{list:async()=>({data:products.map(([key,p])=>({id:'plink_'+key,url:p.url})),has_more:false}),listLineItems:async id=>{const key=id.slice(6),p=b.PRODUCTS[key];return {data:[{quantity:1,price:{id:'price_'+key,active:true,unit_amount:p.amount,currency:'usd',recurring:p.mode==='subscription'?{}:null}}]};}},checkout:{sessions:{listLineItems:async()=>({data:[{quantity:1,price:{id:'price_credits_25',currency:'usd'}}]})}}};}
const paid=()=>({id:'cs_live_example',status:'complete',payment_status:'paid',client_reference_id:user,mode:'payment',currency:'usd',payment_link:'plink_credits_25'});
test('verified merchant Price and paid status determine fulfillment, including local presentation currency',async()=>{const b=billing(),s=stripe(b);assert.equal((await b.verifiedCheckout(s,paid())).product.key,'credits_25');const localized={...paid(),currency:'brl',amount_total:1600};assert.equal((await b.verifiedCheckout(s,localized)).product.key,'credits_25');});
test('unpaid, incomplete, wrong product, forged identity and unrelated same-amount purchases never deliver',async()=>{const b=billing(),s=stripe(b);for(const patch of [{payment_status:'unpaid'},{payment_status:'no_payment_required'},{status:'open'},{client_reference_id:'bad-id'},{mode:'subscription'},{payment_link:'plink_other'},{payment_link:null,metadata:{matchapp_product:'credits_500',matchapp_user:user}}])assert.equal(await b.verifiedCheckout(s,{...paid(),...patch}),null);s.checkout.sessions.listLineItems=async()=>({data:[{quantity:1,price:{id:'price_unrelated',currency:'usd'}}]});assert.equal(await b.verifiedCheckout(s,{...paid(),amount_total:299}),null);});
test('authenticated checkout metadata must bind the product to the same verified account',async()=>{const b=billing(),s=stripe(b);assert(await b.verifiedCheckout(s,{...paid(),payment_link:null,metadata:{matchapp_product:'credits_25',matchapp_user:user}}));assert.equal(await b.verifiedCheckout(s,{...paid(),payment_link:null,metadata:{matchapp_product:'credits_25',matchapp_user:other}}),null);});
test('Postgres delivers each session once, isolates receipts, and preserves a lifetime ad-free purchase',async()=>{
 const {PGlite}=await import('@electric-sql/pglite'),db=await PGlite.create();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema match_private;grant usage on schema match_private to authenticated;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table public.profiles(id uuid primary key references auth.users,credits integer default 0,is_vip boolean default false,is_business boolean default false,is_ad_free boolean default false,subscription_updated_at timestamptz,stripe_customer_id text,stripe_subscription_id text,subscription_status text,subscription_plan text);
 create table public.stripe_events(id text primary key,user_id uuid,plan text);create table public.credit_ledger(user_id uuid,delta integer,balance integer,reason text,pack text,stripe_event_id text unique);insert into auth.users values('${user}'),('${other}');`);
 await db.exec(fs.readFileSync(path.join(root,'supabase/security/verified-billing.sql'),'utf8'));
 const call=(id,uid,plan,sub='sub_example')=>db.query(`select public.fulfill_stripe_checkout($1,$2,$3,'cus_example',$4) as result`,[id,uid,plan,sub]);
 await call('cs_live_credits',user,'credits_25');const again=await call('cs_live_credits',user,'credits_25');assert.equal(again.rows[0].result.duplicate,true);assert.equal((await db.query('select credits from public.profiles where id=$1',[user])).rows[0].credits,25);assert.equal((await db.query('select count(*)::int n from public.credit_ledger')).rows[0].n,1);
 await assert.rejects(call('cs_live_credits',other,'credits_25'),/owner mismatch/);
 await call('cs_live_vip',user,'vip_monthly');await call('cs_live_adfree',user,'ad_free',null);let p=(await db.query('select * from public.profiles where id=$1',[user])).rows[0];assert.equal(p.is_vip,true);assert.equal(p.subscription_plan,'vip_monthly');assert.equal(p.ad_free_purchased,true);
 await db.exec(`set role authenticated;set request.jwt.claim.sub='${other}';`);assert.equal((await db.query("select public.purchase_status('cs_live_credits') r")).rows[0].r.delivered,false);await assert.rejects(db.query("select * from match_private.billing_receipts"),/permission denied/);await assert.rejects(call('cs_live_forged',other,'credits_500'),/permission denied/);
 await db.exec(`set request.jwt.claim.sub='${user}';`);assert.equal((await db.query("select public.purchase_status('cs_live_credits') r")).rows[0].r.delivered,true);
 }finally{await db.close();}
});
