#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),CAL=path.join(ROOT,'awareness/calendar.json'),CUR=path.join(ROOT,'awareness/current.json'),URLS=path.join(ROOT,'tools/awareness-urls.json'),HOME=path.join(ROOT,'index.html');
const HOSTS=new Set(['www.un.org','un.org','www.who.int','who.int','www.alzint.org','alzint.org','www.worldcancerday.org','worldcancerday.org']);
const read=(p,f)=>{try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch{return f;}},stable=(p,v)=>{const n=JSON.stringify(v,null,2)+'\n',o=fs.existsSync(p)?fs.readFileSync(p,'utf8'):'';if(o!==n){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,n);return true;}return false;};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),add=(iso,n)=>{const d=new Date(iso+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);},days=(a,b)=>Math.floor((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const expand=(e,y)=>{const s=y+'-'+String(e.month).padStart(2,'0')+'-'+String(e.day).padStart(2,'0');return{...e,id:e.key+'-'+y,year:y,startDate:s,endExclusive:add(s,e.durationDays||1),pageUrl:'/awareness/'+e.key+'-'+y+'/',theme:e.themeByYear?.[String(y)]||''};},active=(c,t)=>t>=c.startDate&&t<c.endExclusive;
async function verify(e){const u=new URL(e.sourceUrl);if(!HOSTS.has(u.hostname))throw new Error('Unapproved awareness source: '+u.hostname);try{const r=await fetch(e.sourceUrl,{redirect:'follow',headers:{'user-agent':'MatchApp-AwarenessBot/1.0'},signal:AbortSignal.timeout(15000)});if(!r.ok)return false;return (await r.text()).toLowerCase().includes(String(e.verifyTerm||e.name).toLowerCase());}catch(x){console.warn('Source verification deferred:',e.name,x.message);return false;}}
function json(c){const o={id:c.id,key:c.key,year:c.year,name:c.name,startDate:c.startDate,endExclusive:c.endExclusive,sourceName:c.sourceName,sourceUrl:c.sourceUrl,pageUrl:c.pageUrl,ribbonColor:c.ribbonColor||'#7b4db3',theme:c.theme||'',supportLine:c.supportLine||''};if(c.id==='world-alzheimers-month-2026')o.copy={en:{eyebrow:'SEPTEMBER 2026 · AWARENESS SPOTLIGHT',title:'MatchApp supports World Alzheimer’s Month',body:'Raising awareness. Challenging stigma. Supporting earlier dementia diagnosis.',cta:'Learn about the 2026 campaign'},'pt-BR':{eyebrow:'SETEMBRO DE 2026 · DESTAQUE DE CONSCIENTIZAÇÃO',title:'MatchApp apoia o Mês Mundial do Alzheimer',body:'Conscientizar. Combater o estigma. Apoiar o diagnóstico mais precoce da demência.',cta:'Conheça a campanha de 2026'}};return o;}
function block(c){if(!c)return'<!-- AWARENESS-SPOTLIGHT:START -->\n<!-- AWARENESS-SPOTLIGHT:END -->';const title=c.id==='world-alzheimers-month-2026'?'MatchApp supports World Alzheimer’s Month':'MatchApp supports '+c.name,eye=c.id==='world-alzheimers-month-2026'?'September 2026 · Awareness Spotlight':'Awareness Spotlight';return `<!-- AWARENESS-SPOTLIGHT:START -->
<aside id="awareness-spotlight" role="note" aria-label="${esc(title)}" data-awareness-start="${c.startDate}" data-awareness-end="${c.endExclusive}" style="--awareness:${esc(c.ribbonColor||'#7b4db3')}"><div class="awareness-card"><span class="awareness-ribbon" aria-hidden="true"><svg viewBox="0 0 48 64"><path d="M18 4c9 0 16 6 16 15 0 8-6 15-13 22l6 17-9-8-8 8 7-21C12 30 8 24 8 18 8 10 12 4 18 4Z" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" style="color:var(--awareness)"/></svg></span><span class="awareness-copy"><span class="awareness-eyebrow">${esc(eye)}</span><strong class="awareness-title">${esc(title)}</strong><span class="awareness-body">${esc(c.supportLine||'Awareness, respect and reliable information matter.')}</span></span><a class="awareness-cta" href="${esc(c.pageUrl)}">Learn more</a></div></aside>
<!-- AWARENESS-SPOTLIGHT:END -->`;}
function syncHome(c){let s=fs.readFileSync(HOME,'utf8'),r=/<!-- AWARENESS-SPOTLIGHT:START -->[\s\S]*?<!-- AWARENESS-SPOTLIGHT:END -->/;if(r.test(s))s=s.replace(r,block(c));else{s=s.replace(/(<header id="mh-topbox"[\s\S]*?<\/header>)/i,m=>m+'\n'+block(c));}fs.writeFileSync(HOME,s);}
function generic(c){const d=c.durationDays>1?c.startDate+' through '+add(c.endExclusive,-1):c.startDate;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(c.name)} ${c.year}: Date & Official Resources | MatchApp</title><meta name="description" content="${esc(c.name)} ${c.year}: date, awareness context and official resources from ${esc(c.sourceName)}."><meta name="robots" content="index,follow,max-snippet:-1"><link rel="canonical" href="https://matchapp.tv${c.pageUrl}"></head><body style="background:#120d1b;color:#fff;font:16px/1.6 system-ui"><main style="max-width:820px;margin:40px auto;padding:20px"><p><a href="/" style="color:#e5c158">← MatchApp</a></p><h1>${esc(c.name)} ${c.year}</h1><p><strong>Date:</strong> ${esc(d)}</p><p>${esc(c.supportLine||'MatchApp is highlighting this awareness event and directing visitors to authoritative information.')}</p><h2>Official resources</h2><p>Visit <a href="${esc(c.sourceUrl)}" style="color:#e5c158">${esc(c.sourceName)}</a> for current official information.</p><p>MatchApp is an independent supporter of awareness and does not claim endorsement, sponsorship or affiliation. Health-related information is not medical advice.</p></main></body></html>`;}
function robots(file,on){if(!fs.existsSync(file))return;let s=fs.readFileSync(file,'utf8'),w=on?'index,follow,max-image-preview:large,max-snippet:-1':'noindex,follow';s=/<meta name="robots" content="[^"]*">/i.test(s)?s.replace(/<meta name="robots" content="[^"]*">/i,'<meta name="robots" content="'+w+'">'):s.replace('</head>','<meta name="robots" content="'+w+'">\n</head>');fs.writeFileSync(file,s);}
const cal=read(CAL,{events:[],leadDays:45}),t=today(),y=Number(t.slice(0,4)),all=cal.events.flatMap(e=>[expand(e,y-1),expand(e,y),expand(e,y+1)]).sort((a,b)=>a.startDate.localeCompare(b.startDate)),old=read(CUR,{campaign:null});
let selected=all.find(c=>active(c,t))||null;if(selected&&!await verify(selected)){selected=old.campaign&&old.campaign.id===selected.id&&active(old.campaign,t)?{...selected,...old.campaign}:null;}const sj=selected?json(selected):null;stable(CUR,{schemaVersion:1,campaign:sj});syncHome(sj);
const urls=[];for(const c of all){const lead=days(t,c.startDate),on=active(c,t)||(lead>=0&&lead<=Number(cal.leadDays||45)),file=path.join(ROOT,'awareness',c.id,'index.html');if(on){const ok=await verify(c);if(!ok&&!fs.existsSync(file))continue;fs.mkdirSync(path.dirname(file),{recursive:true});if(!fs.existsSync(file))fs.writeFileSync(file,generic(c));robots(file,true);urls.push('https://matchapp.tv'+c.pageUrl);}else if(c.endExclusive<=t&&fs.existsSync(file))robots(file,false);}stable(URLS,[...new Set(urls)].sort());console.log('Awareness bot',t,selected?selected.id:'none',urls.length);
