#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),CAL=path.join(ROOT,'awareness/calendar.json'),CUR=path.join(ROOT,'awareness/current.json'),URLS=path.join(ROOT,'tools/awareness-urls.json'),HOME=path.join(ROOT,'index.html');
const HOSTS=new Set(['www.un.org','un.org','www.who.int','who.int','www.alzint.org','alzint.org','www.worldcancerday.org','worldcancerday.org','www.nationalbreastcancer.org','nationalbreastcancer.org']);
const read=(p,f)=>{try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch{return f;}},stable=(p,v)=>{const n=JSON.stringify(v,null,2)+'\n',o=fs.existsSync(p)?fs.readFileSync(p,'utf8'):'';if(o!==n){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,n);return true;}return false;};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),add=(iso,n)=>{const d=new Date(iso+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);},days=(a,b)=>Math.floor((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000),human=iso=>new Intl.DateTimeFormat('en-US',{timeZone:'UTC',year:'numeric',month:'long',day:'numeric'}).format(new Date(iso+'T12:00:00Z')),cap=s=>String(s||'').replace(/^./,m=>m.toUpperCase()),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const expand=(e,y)=>{const s=y+'-'+String(e.month).padStart(2,'0')+'-'+String(e.day).padStart(2,'0');return{...e,id:e.key+'-'+y,year:y,startDate:s,endExclusive:add(s,e.durationDays||1),pageUrl:'/awareness/'+e.key+'-'+y+'/',theme:e.themeByYear?.[String(y)]||''};},active=(c,t)=>t>=c.startDate&&t<c.endExclusive;
async function verifyUrl(url,term,label){const u=new URL(url);if(!HOSTS.has(u.hostname))throw new Error('Unapproved '+label+': '+u.hostname);try{const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'MatchApp-AwarenessBot/1.0'},signal:AbortSignal.timeout(15000)});if(!r.ok)return false;return (await r.text()).toLowerCase().includes(String(term).toLowerCase());}catch(x){console.warn('Source verification deferred:',label,x.message);return false;}}
async function verify(e){return verifyUrl(e.sourceUrl,e.verifyTerm||e.name,'awareness source');}
async function verifyRibbon(e){if(!e.ribbonSourceUrl)return true;return verifyUrl(e.ribbonSourceUrl,e.ribbonVerifyTerm||e.ribbonColorName||'ribbon','ribbon source');}
function json(c){const o={id:c.id,key:c.key,year:c.year,name:c.name,startDate:c.startDate,endExclusive:c.endExclusive,sourceName:c.sourceName,sourceUrl:c.sourceUrl,pageUrl:c.pageUrl,ribbonColor:c.ribbonColor||'#d9bf79',ribbonColorName:c.ribbonColorName||'',ribbonSourceName:c.ribbonSourceName||'',ribbonSourceUrl:c.ribbonSourceUrl||'',ribbonVerifyTerm:c.ribbonVerifyTerm||'',theme:c.theme||'',supportLine:c.supportLine||''};if(c.id==='world-alzheimers-month-2026')o.copy={en:{eyebrow:'SEPTEMBER 2026 · AWARENESS SPOTLIGHT',title:'MatchApp supports World Alzheimer’s Month',body:'Raising awareness. Challenging stigma. Supporting earlier dementia diagnosis.',cta:'Learn about the 2026 campaign'},'pt-BR':{eyebrow:'SETEMBRO DE 2026 · DESTAQUE DE CONSCIENTIZAÇÃO',title:'MatchApp apoia o Mês Mundial do Alzheimer',body:'Conscientizar. Combater o estigma. Apoiar o diagnóstico mais precoce da demência.',cta:'Conheça a campanha de 2026'}};return o;}
function block(c){if(!c)return'<!-- AWARENESS-SPOTLIGHT:START -->\n<!-- AWARENESS-SPOTLIGHT:END -->';const title=c.id==='world-alzheimers-month-2026'?'MatchApp supports World Alzheimer’s Month':'MatchApp supports '+c.name,eye=c.id==='world-alzheimers-month-2026'?'September 2026 · Awareness Spotlight':'Awareness Spotlight';return `<!-- AWARENESS-SPOTLIGHT:START -->
<aside id="awareness-spotlight" role="note" aria-label="${esc(title)}" data-awareness-start="${c.startDate}" data-awareness-end="${c.endExclusive}" style="--awareness:${esc(c.ribbonColor||'#d9bf79')}"><div class="awareness-card"><span class="awareness-ribbon" aria-hidden="true"><svg viewBox="0 0 48 64"><path d="M18 4c9 0 16 6 16 15 0 8-6 15-13 22l6 17-9-8-8 8 7-21C12 30 8 24 8 18 8 10 12 4 18 4Z" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" style="color:var(--awareness)"/><path class="awareness-ribbon-highlight" d="M18 7c7 0 13 5 13 12 0 6-5 12-12 19" fill="none" stroke="rgba(255,255,255,.58)" stroke-width="2.4" stroke-linecap="round"/></svg></span><span class="awareness-copy"><span class="awareness-eyebrow">${esc(eye)}</span><strong class="awareness-title">${esc(title)}</strong><span class="awareness-body">${esc(c.supportLine||'Awareness, respect and reliable information matter.')}</span></span><a class="awareness-cta" href="${esc(c.pageUrl)}">Learn more</a></div></aside>
<!-- AWARENESS-SPOTLIGHT:END -->`;}
function syncHome(c){let s=fs.readFileSync(HOME,'utf8'),r=/<!-- AWARENESS-SPOTLIGHT:START -->[\s\S]*?<!-- AWARENESS-SPOTLIGHT:END -->/g;s=s.replace(r,'');const footer='    <footer class="seo-footer">';if(!s.includes(footer))throw new Error('Cannot place awareness spotlight: Home footer missing');s=s.replace(footer,block(c)+'\n\n'+footer);fs.writeFileSync(HOME,s);}
function seoSchema(c,title,description){const url='https://matchapp.tv'+c.pageUrl,citations=[c.sourceUrl,...(c.ribbonSourceUrl?[c.ribbonSourceUrl]:[])];return JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebPage','@id':url+'#webpage',url,name:title,description,inLanguage:'en',datePublished:c.startDate,isPartOf:{'@type':'WebSite','@id':'https://matchapp.tv/#website',url:'https://matchapp.tv/',name:'MatchApp Ai'},about:{'@type':'Thing',name:c.name+' '+c.year},citation:citations},{'@type':'BreadcrumbList','@id':url+'#breadcrumb',itemListElement:[{'@type':'ListItem',position:1,name:'MatchApp Ai',item:'https://matchapp.tv/'},{'@type':'ListItem',position:2,name:c.name+' '+c.year,item:url}]}]}).replace(/</g,'\\u003c');}
function generic(c){const end=add(c.endExclusive,-1),d=c.durationDays>1?human(c.startDate)+' – '+human(end):human(c.startDate),ribbon=c.ribbonColorName&&c.ribbonSourceUrl,desc=c.name+' '+c.year+' runs '+d+'. '+(ribbon?cap(c.ribbonColorName)+' ribbon information and ':'')+'official resources from '+c.sourceName+'.',title=c.name+' '+c.year+': '+(ribbon?cap(c.ribbonColorName)+' Ribbon, ':'')+'Dates & Official Resources | MatchApp Ai',url='https://matchapp.tv'+c.pageUrl,theme=c.theme?`<section><h2>${esc(c.year)} campaign theme</h2><p>${esc(c.theme)}</p></section>`:'',ribbonSection=ribbon?`<section><h2>Awareness ribbon</h2><p>The ribbon color highlighted for this campaign is <strong>${esc(c.ribbonColorName)}</strong>. Ribbon reference: <a href="${esc(c.ribbonSourceUrl)}" rel="noopener">${esc(c.ribbonSourceName||'official ribbon resource')}</a>.</p></section>`:'';return `<!doctype html><html lang="en"><head><!-- MATCHAPP-AWARENESS-GENERATED --><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="${esc(url)}"><meta property="og:type" content="website"><meta property="og:site_name" content="MatchApp Ai"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${esc(url)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(desc)}"><meta name="theme-color" content="${esc(c.ribbonColor||'#d9bf79')}"><link rel="stylesheet" href="/brand.css?v=192"><script type="application/ld+json">${seoSchema(c,title,desc)}</script><!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-M7J3NNBN');</script>
<!-- End Google Tag Manager --></head><body style="background:#120d1b;color:#fff;font:16px/1.6 system-ui"><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M7J3NNBN" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><div class="matchapp-brand-bar"><a class="matchapp-brand-link" href="/" aria-label="MatchApp Ai"><img class="matchapp-wordmark" src="/assets/brand/matchapp-tv-ai-v2.svg" alt="MatchApp Ai" width="368" height="66" decoding="async"></a></div><main style="max-width:820px;margin:40px auto;padding:20px"><nav aria-label="Breadcrumb"><a href="/" style="color:#e5c158">MatchApp Ai</a> › Awareness</nav><article><header><p>Awareness Spotlight</p><h1>${esc(c.name)} ${c.year}</h1><p>${esc(c.supportLine||'MatchApp Ai highlights reliable awareness information and official resources.')}</p></header><section><h2>When is ${esc(c.name)} ${c.year}?</h2><p><strong>Date:</strong> <time datetime="${esc(c.startDate)}">${esc(human(c.startDate))}</time>${c.durationDays>1?` through <time datetime="${esc(end)}">${esc(human(end))}</time>`:''}.</p></section>${ribbonSection}${theme}<section><h2>Official information and resources</h2><p>For current campaign information, visit <a href="${esc(c.sourceUrl)}" rel="noopener">${esc(c.sourceName)}</a>.</p>${ribbon&&c.ribbonSourceUrl!==c.sourceUrl?`<p>Ribbon reference: <a href="${esc(c.ribbonSourceUrl)}" rel="noopener">${esc(c.ribbonSourceName||c.ribbonSourceUrl)}</a>.</p>`:''}</section><section><h2>About this MatchApp Ai awareness page</h2><p>MatchApp Ai publishes this page to make verified awareness dates and authoritative resources easier to find. It does not claim endorsement, sponsorship or affiliation with the organizations linked above.</p><p>Health-related information on this page is general awareness information and is not medical advice.</p></section></article></main></body></html>`;}
function botOwned(file,c){if(!fs.existsSync(file))return true;const s=fs.readFileSync(file,'utf8');return s.includes('MATCHAPP-AWARENESS-GENERATED')||s.includes(c.name+' '+c.year+': date, awareness context and official resources');}
function robots(file,on){if(!fs.existsSync(file))return;let s=fs.readFileSync(file,'utf8'),w=on?'index,follow,max-image-preview:large,max-snippet:-1':'noindex,follow';s=/<meta name="robots" content="[^"]*">/i.test(s)?s.replace(/<meta name="robots" content="[^"]*">/i,'<meta name="robots" content="'+w+'">'):s.replace('</head>','<meta name="robots" content="'+w+'">\n</head>');fs.writeFileSync(file,s);}
const cal=read(CAL,{events:[],leadDays:45}),t=today(),y=Number(t.slice(0,4)),all=cal.events.flatMap(e=>[expand(e,y-1),expand(e,y),expand(e,y+1)]).sort((a,b)=>a.startDate.localeCompare(b.startDate)),old=read(CUR,{campaign:null});
let selected=all.find(c=>active(c,t))||null;if(selected&&!await verify(selected)){selected=old.campaign&&old.campaign.id===selected.id&&active(old.campaign,t)?{...selected,...old.campaign}:null;}if(selected&&selected.ribbonSourceUrl&&!await verifyRibbon(selected)){console.warn('Ribbon source verification deferred:',selected.name);if(old.campaign&&old.campaign.id===selected.id&&old.campaign.ribbonColor)selected={...selected,ribbonColor:old.campaign.ribbonColor};}const sj=selected?json(selected):null;stable(CUR,{schemaVersion:1,campaign:sj});syncHome(sj);
const urls=[];for(const c of all){const lead=days(t,c.startDate),on=active(c,t)||(lead>=0&&lead<=Number(cal.leadDays||45))||(days(c.endExclusive,t)>=0&&days(c.endExclusive,t)<3),file=path.join(ROOT,'awareness',c.id,'index.html');if(on){const ok=await verify(c);if(!ok&&!fs.existsSync(file))continue;fs.mkdirSync(path.dirname(file),{recursive:true});const owned=botOwned(file,c),ribbonOk=!c.ribbonSourceUrl||await verifyRibbon(c);if(owned&&(ribbonOk||!fs.existsSync(file))){const pageCampaign=ribbonOk?c:{...c,ribbonColorName:'',ribbonSourceName:'',ribbonSourceUrl:'',ribbonVerifyTerm:''};fs.writeFileSync(file,generic(pageCampaign));}robots(file,true);urls.push('https://matchapp.tv'+c.pageUrl);}else if(c.endExclusive<=t&&fs.existsSync(file))robots(file,false);}stable(URLS,[...new Set(urls)].sort());console.log('Awareness bot',t,selected?selected.id:'none',urls.length);
