#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.join(__dirname,'..'),NEWS=path.join(ROOT,'news'),ART=path.join(NEWS,'articles'),SITE='https://matchapp.tv';
const SOURCES={'reuters.com':'Reuters','cnn.com':'CNN','hollywoodreporter.com':'The Hollywood Reporter','bbc.com':'BBC','g1.globo.com':'G1'};
const SOURCE_COUNTRY={'reuters.com':'GLOBAL','cnn.com':'US','hollywoodreporter.com':'US','bbc.com':'GB','g1.globo.com':'BR'};
const COUNTRY={'Brazil':'BR','UnitedStates':'US','UnitedKingdom':'GB','Canada':'CA','Australia':'AU','Portugal':'PT','Spain':'ES','France':'FR','Germany':'DE','Italy':'IT','Mexico':'MX','Argentina':'AR','India':'IN','Japan':'JP','SouthKorea':'KR'};
const TERMS='(actor OR actress OR singer OR musician OR movie OR film OR television OR streaming OR album OR song OR concert OR celebrity OR awards)';
const RUMOR=/\b(rumou?r|reportedly|allegedly|speculation|unconfirmed|sources say|might be|could be|is said to|insider claims?)\b/i;
const NON_NEWS=/\b(opinion|shopping|coupon|horoscope|quiz)\b/i;
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'news';
const hash=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,8);
function domain(url){try{return new URL(url).hostname.toLowerCase().replace(/^www\./,'');}catch(_){return'';}}
function allowed(url){const d=domain(url);return Object.keys(SOURCES).find(x=>d===x||d.endsWith('.'+x))||null;}
function image(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:null;}catch(_){return null;}}
function date(v){const s=String(v||'');const m=s.match(/^(\d{4})(\d{2})(\d{2})T?(\d{2})?(\d{2})?(\d{2})?/);return m?new Date(`${m[1]}-${m[2]}-${m[3]}T${m[4]||'00'}:${m[5]||'00'}:${m[6]||'00'}Z`).toISOString():new Date().toISOString();}
function event(title){const t=title.toLowerCase();if(/\b(dies|died|dead|death|obituary)\b/.test(t))return'Obituary';if(/\b(cast|joins|role|stars in|to star)\b/.test(t))return'Casting';if(/\b(album|single|song|tour|concert|music video)\b/.test(t))return'Music';if(/\b(release|premiere|debut|trailer|launch)\b/.test(t))return'Release';if(/\b(award|emmy|oscar|grammy|wins|nominated|nomination)\b/.test(t))return'Awards';return'Entertainment';}
function person(title){const m=clean(title).match(/^([A-ZÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ][\p{L}'’.-]+(?:\s+[A-ZÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ][\p{L}'’.-]+){1,3})\b/u);return m?m[1]:'';}
async function query(source){const q=`${TERMS} domain:${source}`,u=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(q)}&mode=artlist&maxrecords=40&format=json&sort=datedesc&timespan=48h`,ac=new AbortController(),tm=setTimeout(()=>ac.abort(),12000);try{const r=await fetch(u,{signal:ac.signal,headers:{accept:'application/json','user-agent':'MatchAppNewsBot/1.0 (+https://matchapp.tv/)'}});if(!r.ok)throw new Error(String(r.status));const j=await r.json();return Array.isArray(j.articles)?j.articles:[];}catch(e){console.warn(`[news] ${source}: ${e.message}`);return [];}finally{clearTimeout(tm);}}
function page(i){const d=esc(i.description),t=esc(i.title),src=esc(i.source),orig=esc(i.url),canon=esc(i.matchapp_url);return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t} | MatchApp Entertainment News</title><meta name="description" content="${d}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${canon}"><meta property="og:title" content="${t}"><meta property="og:description" content="${d}"><meta property="og:url" content="${canon}"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:i.title,url:i.matchapp_url,datePublished:i.published_at,dateModified:i.published_at,description:i.description,isBasedOn:i.url,publisher:{'@type':'Organization',name:'MatchApp TV Ai',url:SITE}})}</script><link rel="stylesheet" href="/style.css?v=187"></head><body><main style="max-width:780px;margin:40px auto;padding:20px"><article class="premium-card" style="padding:24px"><p style="color:#E5C158;font-weight:800">LATEST NEWS · ${esc(i.event_type)}</p><h1>${t}</h1><p>${d}</p><p>${src} · <time datetime="${esc(i.published_at)}">${new Date(i.published_at).toLocaleDateString('en-US',{dateStyle:'long'})}</time></p><p><a href="${orig}" target="_blank" rel="noopener noreferrer">Read the original report at ${src} ↗</a></p><p style="font-size:13px;color:#aaa">MatchApp links to the original publisher and does not republish the article body.</p><p><a href="/news/">More entertainment news</a> · <a href="/">Back to MatchApp</a></p></article></main></body></html>`;}
function hub(items,generated){const cards=items.slice(0,24).map(i=>`<article><p>${esc(i.source)} · ${esc(i.event_type)}</p><h2><a href="${esc(i.matchapp_url)}">${esc(i.title)}</a></h2><p>${esc(i.description)}</p><a href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">Original source ↗</a></article>`).join('');return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Latest Entertainment News | Actors & Singers | MatchApp TV</title><meta name="description" content="Verified entertainment headlines about actors, singers, films and music from trusted publishers, refreshed hourly by MatchApp TV."><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${SITE}/news/"><link rel="stylesheet" href="/style.css?v=187"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage',name:'Latest Entertainment News',url:`${SITE}/news/`,dateModified:generated})}</script></head><body><main style="max-width:1120px;margin:36px auto;padding:18px"><a href="/">← MatchApp</a><h1>Latest Entertainment News</h1><p>Verified actor, singer, film and music updates from trusted publishers. Updated hourly.</p><section style="display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px">${cards}</section></main></body></html>`;}
(async()=>{const rows=(await Promise.all(Object.keys(SOURCES).map(query))).flat(),seen=new Set(),items=[];for(const r of rows){const url=String(r.url||''),src=allowed(url),title=clean(r.title);if(!src||title.length<18||title.length>220||RUMOR.test(title)||NON_NEWS.test(title))continue;const k=title.toLowerCase().replace(/[^a-z0-9]+/g,' ');if(seen.has(k))continue;seen.add(k);const id=hash(url),p=person(title),ev=event(title),countryRaw=String(r.sourcecountry||'').replace(/\s+/g,''),country=COUNTRY[countryRaw]||SOURCE_COUNTRY[src]||'GLOBAL',matchapp_url=`${SITE}/news/articles/${slug(title)}-${id.slice(0,6)}/`;items.push({id,title,url,source:SOURCES[src],source_domain:src,country,published_at:date(r.seendate),event_type:ev,person:p,description:`${p?p+': ':''}${ev.toLowerCase()} update covered by ${SOURCES[src]}. Open the original report for full context.`,image:image(r.socialimage),matchapp_url});if(items.length>=40)break;}items.sort((a,b)=>b.published_at.localeCompare(a.published_at));if(items.length<5)throw new Error(`trusted feed returned only ${items.length} usable items`);const generated=new Date().toISOString();fs.mkdirSync(NEWS,{recursive:true});fs.rmSync(ART,{recursive:true,force:true});fs.mkdirSync(ART,{recursive:true});for(const i of items){const dir=path.join(ART,new URL(i.matchapp_url).pathname.split('/').filter(Boolean).pop());fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),page(i));}fs.writeFileSync(path.join(NEWS,'data.json'),JSON.stringify({generated_at:generated,source_policy:'trusted-publisher-allowlist',items},null,2)+'\n');fs.writeFileSync(path.join(NEWS,'index.html'),hub(items,generated));fs.writeFileSync(path.join(ROOT,'tools','news-urls.json'),JSON.stringify([`${SITE}/news/`,...items.slice(0,30).map(i=>i.matchapp_url)],null,2)+'\n');console.log(JSON.stringify({ok:true,items:items.length,sources:[...new Set(items.map(i=>i.source))],countries:[...new Set(items.map(i=>i.country))]}));})().catch(e=>{console.error(e);process.exit(1);});