create schema if not exists match_private;

create table if not exists match_private.support_threads (
  id uuid primary key default gen_random_uuid(),
  channel text not null check (channel in ('email','whatsapp')),
  external_thread_key text not null,
  sender text not null,
  user_id uuid null references auth.users(id) on delete set null,
  status text not null default 'open' check (status in ('open','waiting_user','escalated','resolved')),
  category text not null default 'unknown',
  severity text not null default 'normal' check (severity in ('low','normal','high','urgent')),
  language text null,
  summary text null,
  metadata jsonb not null default '{}'::jsonb,
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(channel, external_thread_key)
);

create table if not exists match_private.support_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references match_private.support_threads(id) on delete cascade,
  channel text not null check (channel in ('email','whatsapp')),
  direction text not null check (direction in ('inbound','outbound','internal')),
  external_message_id text null,
  subject text null,
  sender text null,
  body text not null,
  ai_provider text null,
  ai_model text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists support_messages_external_id_uq
  on match_private.support_messages(channel, external_message_id)
  where external_message_id is not null;
create index if not exists support_threads_user_idx
  on match_private.support_threads(user_id, last_message_at desc);
create index if not exists support_threads_status_idx
  on match_private.support_threads(status, last_message_at desc);
create index if not exists support_messages_thread_idx
  on match_private.support_messages(thread_id, created_at desc);

create table if not exists match_private.support_escalations (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references match_private.support_threads(id) on delete cascade,
  reason text not null,
  summary text not null,
  status text not null default 'open' check (status in ('open','resolved','dismissed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz null
);
create index if not exists support_escalations_open_idx
  on match_private.support_escalations(status, created_at desc);

alter table match_private.support_threads enable row level security;
alter table match_private.support_messages enable row level security;
alter table match_private.support_escalations enable row level security;
revoke all on match_private.support_threads from anon, authenticated;
revoke all on match_private.support_messages from anon, authenticated;
revoke all on match_private.support_escalations from anon, authenticated;
grant usage on schema match_private to service_role;
grant select, insert, update, delete on match_private.support_threads to service_role;
grant select, insert, update, delete on match_private.support_messages to service_role;
grant select, insert, update, delete on match_private.support_escalations to service_role;
grant usage, select on all sequences in schema match_private to service_role;

create or replace function public.support_account_context(p_email text default null,p_phone text default null)
returns jsonb
language sql
security definer
set search_path = ''
as $$
  with matched as (
    select u.id
    from auth.users u
    where (
      nullif(trim(p_email),'') is not null
      and lower(coalesce(u.email,'')) = lower(trim(p_email))
    ) or (
      nullif(trim(p_phone),'') is not null
      and regexp_replace(coalesce(u.phone,''), '[^0-9]', '', 'g')
          = regexp_replace(trim(p_phone), '[^0-9]', '', 'g')
    )
    limit 1
  )
  select coalesce(
    (
      select jsonb_build_object(
        'found', true,
        'user_id', m.id,
        'country', p.country,
        'language', p.preferred_language,
        'region', p.preferred_region,
        'is_vip', coalesce(p.is_vip,false),
        'is_business', coalesce(p.is_business,false),
        'subscription_status', p.subscription_status,
        'subscription_plan', p.subscription_plan,
        'credits', p.credits,
        'profile_locked', coalesce(p.profile_locked,false)
      )
      from matched m
      left join public.profiles p on p.id=m.id
    ),
    '{"found":false}'::jsonb
  );
$$;
revoke all on function public.support_account_context(text,text) from public, anon, authenticated;
grant execute on function public.support_account_context(text,text) to service_role;

create or replace function public.support_server_secret(p_name text)
returns text
language sql
security definer
set search_path = ''
as $$
  select decrypted_secret
  from vault.decrypted_secrets
  where name=p_name
    and p_name in (
      'resend_api_key',
      'resend_support_webhook_secret',
      'whatsapp_support_access_token',
      'whatsapp_support_app_secret',
      'whatsapp_support_verify_token',
      'whatsapp_support_phone_number_id'
    )
  limit 1
$$;
revoke all on function public.support_server_secret(text) from public, anon, authenticated;
grant execute on function public.support_server_secret(text) to service_role;

create or replace function public.support_ingest_inbound(
  p_channel text,p_external_thread_key text,p_sender text,p_external_message_id text,
  p_subject text,p_body text,p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_thread_id uuid;
  v_message_id bigint;
  v_context jsonb;
  v_user_id uuid;
begin
  if p_channel not in ('email','whatsapp') then raise exception 'unsupported support channel'; end if;
  if nullif(trim(p_external_thread_key),'') is null
     or nullif(trim(p_sender),'') is null
     or nullif(trim(p_body),'') is null then
    raise exception 'missing support message fields';
  end if;

  v_context := public.support_account_context(
    case when p_channel='email' then p_sender else null end,
    case when p_channel='whatsapp' then p_sender else null end
  );
  if coalesce((v_context->>'found')::boolean,false) then
    v_user_id := nullif(v_context->>'user_id','')::uuid;
  end if;

  insert into match_private.support_threads(
    channel,external_thread_key,sender,user_id,metadata,last_message_at,updated_at
  ) values (
    p_channel,p_external_thread_key,p_sender,v_user_id,coalesce(p_metadata,'{}'::jsonb),now(),now()
  )
  on conflict (channel,external_thread_key) do update
    set sender=excluded.sender,
        user_id=coalesce(match_private.support_threads.user_id,excluded.user_id),
        metadata=match_private.support_threads.metadata || excluded.metadata,
        last_message_at=now(),updated_at=now()
  returning id into v_thread_id;

  insert into match_private.support_messages(
    thread_id,channel,direction,external_message_id,subject,sender,body,metadata
  ) values (
    v_thread_id,p_channel,'inbound',nullif(p_external_message_id,''),p_subject,p_sender,
    left(p_body,12000),coalesce(p_metadata,'{}'::jsonb)
  )
  on conflict (channel,external_message_id) where external_message_id is not null do nothing
  returning id into v_message_id;

  if v_message_id is null and nullif(p_external_message_id,'') is not null then
    select m.thread_id into v_thread_id
    from match_private.support_messages m
    where m.channel=p_channel and m.external_message_id=p_external_message_id
    limit 1;
  end if;

  return jsonb_build_object('thread_id',v_thread_id,'inserted',v_message_id is not null,'account',v_context);
end;
$$;
revoke all on function public.support_ingest_inbound(text,text,text,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.support_ingest_inbound(text,text,text,text,text,text,jsonb) to service_role;

create or replace function public.support_thread_history(p_thread_id uuid,p_limit integer default 8)
returns jsonb
language sql
security definer
set search_path = ''
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object('direction',q.direction,'body',q.body,'created_at',q.created_at)
      order by q.created_at asc
    ),
    '[]'::jsonb
  )
  from (
    select direction,left(body,4000) as body,created_at
    from match_private.support_messages
    where thread_id=p_thread_id
    order by created_at desc
    limit greatest(1,least(coalesce(p_limit,8),20))
  ) q;
$$;
revoke all on function public.support_thread_history(uuid,integer) from public, anon, authenticated;
grant execute on function public.support_thread_history(uuid,integer) to service_role;

create or replace function public.support_record_outbound(
  p_thread_id uuid,p_channel text,p_external_message_id text,p_body text,
  p_ai_provider text,p_ai_model text,p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into match_private.support_messages(
    thread_id,channel,direction,external_message_id,sender,body,ai_provider,ai_model,metadata
  ) values(
    p_thread_id,p_channel,'outbound',nullif(p_external_message_id,''),'MatchApp Ai Support',
    left(p_body,12000),p_ai_provider,p_ai_model,coalesce(p_metadata,'{}'::jsonb)
  )
  on conflict (channel,external_message_id) where external_message_id is not null do nothing;

  update match_private.support_threads
  set last_message_at=now(),updated_at=now()
  where id=p_thread_id;
end;
$$;
revoke all on function public.support_record_outbound(uuid,text,text,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.support_record_outbound(uuid,text,text,text,text,text,jsonb) to service_role;

create or replace function public.support_update_thread(
  p_thread_id uuid,p_category text,p_severity text,p_language text,p_summary text,
  p_needs_human boolean,p_escalation_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update match_private.support_threads
  set category=coalesce(nullif(p_category,''),'unknown'),
      severity=case when p_severity in ('low','normal','high','urgent') then p_severity else 'normal' end,
      language=nullif(p_language,''),
      summary=left(nullif(p_summary,''),2000),
      status=case when p_needs_human then 'escalated' else 'waiting_user' end,
      updated_at=now()
  where id=p_thread_id;

  if p_needs_human then
    insert into match_private.support_escalations(thread_id,reason,summary)
    select p_thread_id,
           left(coalesce(nullif(p_escalation_reason,''),'Human review requested'),1000),
           left(coalesce(nullif(p_summary,''),'Support conversation needs human review'),2000)
    where not exists (
      select 1 from match_private.support_escalations
      where thread_id=p_thread_id and status='open'
    );
  end if;
end;
$$;
revoke all on function public.support_update_thread(uuid,text,text,text,text,boolean,text) from public, anon, authenticated;
grant execute on function public.support_update_thread(uuid,text,text,text,text,boolean,text) to service_role;
